/** Egne løsningsforslag. Ikke Udirs sensorveiledning. */

export const SOLUTIONS: Record<string, Record<number, string>> = {
  v2026: {
    1: "Vinden rundt et lavtrykk på nordlige halvkule går mot urviseren (Buys-Ballot: ryggen mot vinden, lavtrykk til venstre). Når senteret treffer Nordland, avgjør plasseringen av X relativt til senteret. Ligger X sør for senteret, kommer vinden typisk fra sørvest. Ligger X nord for senteret, kommer den fra nordøst. Åpne analysekartet hos Udir og plasser X mot L-et.",
    2: "Vulkanisme (3) og «hele Middelhavet like hardt» (5) er usanne. Lite vind og klarvær (4) er sant: da varmes overflaten opp, og blandingen nedover svekkes. Påstand 1 (~10 °C anomali) er usann — slike hetebølger ligger vanligvis på noen få grader over 1991–2020. Påstand 2 må sjekkes mot figuren. Blant alternativene er «2 og 4» det som passer hvis figuren viser 28,67 °C som rekord.",
    3: "Riktig årsak–virkning: høyere global middeltemperatur gir hyppigere hetebølger, som øker tørke og vannmangel. Urbanisering kjøler ikke byer (varmeøy). Mer vegetasjon gir ikke mer skogbrann som hovedlenke. Luftforurensning som reduserer solinnstråling gir ikke sterkere hetebølge.",
    4: "Tropiske sykloner lever av varmt hav. Langt nord mister de varmekilden og dør ut. Derfor når de sjelden Europa. Coriolis «for sterk» er feil, og vestavinden alene er ikke hovedårsaken — det er det kalde vannet.",
    5: "IPCC: færre og svakere kuldeekstremer i et varmere klima. En slakkere jet kan gi mer langvarige kuldeutbrudd i enkelte regioner, men det er ikke det mest sannsynlige hovedsvaret her. Velg at kuldebølgene blir færre og kortere.",
    6: "Gyda var en atmosfærisk elv: en smal stripe med svært fuktig luft fra Atlanteren. Prognosekartet viser mørkeblå fuktighet inn mot Vestlandet og Trøndelag. Der tvinges lufta opp av fjellene (orografisk heving), vanndampen kondenserer, og det kommer ekstremnedbør. Koble farevarselet til den samme fuktighetsplumen.",
    7: "Kaldt ferskvannssmeltevann er tyngre enn romtemperert ferskvann og synker. I saltvann er smeltevannet lettere enn saltvannet og blir liggende oppå. Glasset der fargen legger seg langs bunnen, er ferskvann.",
    8: "Les isopyknalene i T–S-diagrammet. Den vannmassen som ligger på høyere tetthetslinje, er tyngst og legger seg under. A er varmere og saltare enn B; uten figuren kan du ikke gjette — plott 1 °C / 29,7 PSU og −0,8 °C / 29,4 PSU og les hvilken som er tettest.",
    9: "August: varmere og ferskere i de øverste meterne (smeltevann og oppvarming). April: kaldere, mer gjennomblandet, ofte saltere i toppen. Velg temperatur- og salinitetsprofilene som matcher det.",
    10: "Medvirkende: is- og snøalbedo som synker, og endret vertikal temperaturgradient (lapse-rate-tilbakekobling). Ikke medvirkende: mer vanndamp enn i tropene, sterk vertikal blanding i arktisk troposfære, og «mer klimagasser enn andre regioner».",
    11: "Sett punktet der lang fetch, motgående strøm og bratt batymetri møtes — typisk eggakanten eller der Atlanterhavsbølger møter kyststrøm. Begrunn med de tre prosessene i oppgaveteksten, ikke med tilfeldig kystby.",
    12: "Les grafene bokstavelig. Kortvarig hopp 2015–2020 er ikke automatisk «kraftig global oppvarming». Smeltevann kan senke salinitet i toppen. Atlantisk vann som blir saltere, henger ikke automatisk på varmere klima. Polart vann er ferskere enn atlantisk, ikke saltere. Marker sann/usann og vis til riktig panel.",
    13: "Perihelium ved NH-vinter: mildere NH-vinter og kjøligere NH-sommer → små årstidsforskjeller i nord (sann). Aphelium ved NH-sommer er samme geometri; da får sør store årstidsforskjeller (sann). Aphelium ved NH-vinter gir varme NH-somre → mindre sjanse for istid (sann).",
    14: "Milanković betyr mest ved 65°N fordi sommersola der svinger mye, og det styrer om snøen overlever. Ved ekvator er innstrålingen jevn hele året. Rotasjonshastighet og «større avstandsendring ved 65°N» er feil.",
    15: "Positive tilbakekoblinger forsterker nedkjølingen (mer is → høyere albedo → enda kaldere). Negative tilbakekoblinger motvirker. Riktig: positive tilbakekoblinger øker nedkjølingen.",
    16: "Større isvolum betyr kjøligere klima. Positive tilbakekoblinger (albedo, CO₂ i havet) forsterker den orbitale nedkjølingen. Ikke «varmere» og ikke «mindre usikkerhet».",
    17: "Innlandsis dekker bakken og stenger for permafrost. Nord-Amerika hadde den største Laurentide-isen, derfor mindre permafrostareal der. Eurasia hadde mer bart, kaldt land — mer permafrost.",
    18: "Mindre sjøis gir lengre strøklengde, høyere bølger, mer kysterosjon og stormflo. Åpent hav avgir mer varme og fukt til lufta, så lavtrykk kan forsterkes. Isbjørn og kystsamfunn mister beskyttelsen isen ga.",
    19: "Ålfotbreen er maritim (vest, mye vinternedbør), Hellstugubreen er kontinental (øst, tørrere). Etter 2000 er massebalansen gjennomgående negativ — det peker på oppvarming. Volum øker ikke når sommerbalansen er «større» enn vinterbalansen (det er motsatt: vinterpålagring må slå sommersmelting).",
    20: "Positiv NAO: sterke vestavinder, milde og våte vintre på Vestlandet. Negativ NAO: svakere vestavind, ofte kaldere og tørrere vestlandsvintre og dårligere vinterbalanse. Blant alternativene er negativ NAO → kaldt og tørt → lite snø det som treffer.",
    21: "Første påstand er fønvind, ikke katabatisk (feil). Katabatisk vind er kald luft som renner nedover, ofte fra isbre (riktig). Synkende katabatisk luft er tørr — den lager sjelden skyer (feil).",
    22: "Loside 14 °C. Tørradiabat 1 °C/100 m opp til skybase 800 m → 6 °C. Våtadiabat 0,5 °C/100 m videre 1200 m til 2000 m → 0 °C på toppen. Leside tørradiabat 2000 m ned → 20 °C. Svar: 0 °C på toppen, 20 °C ved foten på lesiden.",
    23: "Mer sol i Norge er usikkert (mer skyer kan spise gevinsten). Smeltende breer gir mer vannkraft en stund, så mindre. Stabile fønvinder som «vindsikkerhet» er spekulasjon. Global oppvarming gir ikke automatisk mer nyttbar vind i Norge. Vurder sannsynlighet, ikke ja/nei.",
  },
  v2025: {
    1: "Svekket nordatlantisk strøm / AMOC gir mindre varmetransport mot Norge. Vestlandet blir kaldere. Mindre varme og fukt fra havet gir også mindre nedbør. Velg lavere temperatur og mindre nedbør.",
    2: "To mekanismer: varmere, lettere overflatevann synker dårligere, og smeltevann fra Grønland gjør toppvannet ferskere og lettere. Det kan stanse dypvannsdannelsen. Økt fordamping som «lik densitet» er feil. Regn som stanser sjøis er ikke hovedforklaringen.",
    3: "Påstand 1 og 2 er sanne (sol, lite sky, svak vind og sterk sjiktning). La Niña gir ikke typisk marine hetebølger i Stillehavet på samme måte som El Niño. Hetebølger gir sterkere, ikke svakere, tropiske orkaner. Velg 1 og 2.",
    4: "Ozon i 20–30 km er stratosfærisk ozon. Mer ozon der absorberer UV og endrer stratosfæren; det globale overflatetemperaturpådrivet er lite sammenlignet med CO₂. Velg at global temperatur ikke påvirkes i særlig grad — sjekk figuren Udir har brukt.",
    5: "Lavere albedo → mer absorbert sol (rett). Permafrost som tiner gir ikke alltid lavere albedo (myr, vann, vegetasjon varierer) (galt). Satellitter måler albedo (rett).",
    6: "Ekvator: jevn innstråling, to små topper. Nordlig halvkule: maksimum i juni–juli. Sørlig: maksimum i desember–januar. Koble farge/symbol til den kurven som matcher.",
    7: "Les trykk, front og vind i ringen over Finnmark. Velg farevarselet som matcher det analysekartet faktisk viser (vind, snø, skogbrann eller flom). Uten kartet er det gjetning.",
    8: "Lufttrykk synker med høyden. Bruk hydrostatisk likevekt / barometrisk formel hvis tall er gitt. Ellers: lavest trykk høyest oppe, og i et lavtrykkssenter.",
    9: "ITCZ og monsun styrer tropisk nedbør. Polarfronten styrer midlere breddegrader. Les kartet og plasser høy/lav nedbør der de to beltene ligger.",
    10: "Coriolis bøyer til høyre på nordlige, til venstre på sørlige. Geostrofisk vind følger isobarene. Kryss av påstandene deretter.",
    11: "Jetstrømmen ligger der temperaturgradienten i troposfæren er størst (polarfronten). En sørlig buktning bringer kaldluft sør, en nordlig buktning varmluft nord.",
    12: "ENSO: El Niño = varmt østlig Stillehav, forskjøvet konveksjon. La Niña = kaldt øst, sterkere passat. Les figuren og match fase.",
    13: "Paleoklima på millionårsskala: havbunnssediment og bergarter/fossiler. Iskjerner og treringer rekker ikke 2 millioner år i Norge.",
    14: "Strålingspådriv: mer drivhusgass = positivt pådriv. Aerosoler ofte negativt. Les hvilke stolper som peker opp og ned.",
    15: "Tetthet i havet styres av temperatur og saltholdighet. Kaldt og salt er tettest. Middelhavet er tett på grunn av fordamping (høy saltholdighet), ikke fordi det er «Indiahavet».",
    16: "Tropisk orkan trenger hav over ca. 26,5 °C, coriolis og svak skjærvind. Den dør over land og kaldt vann.",
    17: "Fønvind: fuktig luft tvinges opp, våtadiabat på losiden, tørradiabat på lesiden → varm og tørr leside. Katabatisk er kald fallvind.",
    18: "Klikk / marker der figuren ber om det. Bruk definisjonene i oppgaven, ikke utenforliggende kunnskap.",
    19: "Samme prinsipp: les aksene, enheter og hva som faktisk er tegnet før du krysser.",
    20: "Siste interaktive: ofte sammensatt av kart + påstand. En påstand om årsak må ha både riktig prosess og riktig sted.",
    21: "Kortsvar: bruk vedlegget om AMOC. Skill Golfstrøm (vinddrevet gryre) fra AMOC (termohalin omveltning). Si hva modellene er enige om (svekkelse) og uenige om (kollaps).",
    22: "Langsvar: mekanismer, usikkerhet, og konsekvens for Norge. Henvis til Udir-vedlegget med forfatter og år.",
    23: "Langsvar: felt, figur eller klimaindikator. Vis at du kan lese data, ikke bare gjengi læreboka.",
  },
  v2024: {
    1: "Vindstyrke leses av isobaravstand: tette isobarer = sterk vind. Marker det området kartet viser med minst avstand mellom isobarene.",
    2: "Drivhusgasser absorberer langbølget utstråling. CO₂, vanndamp, metan og lystgass. N₂ og O₂ er ikke drivhusgasser.",
    3: "Foran en varmfront: varm luft sklir over kald, jevn nedbør, falling pressure. Bak kaldfronten: byger, klarere, ofte nordvestlig vind i Norge.",
    4: "Biomasse som energi: fornybar hvis tilveksten matcher uttak, men den slipper CO₂ ved forbrenning og kan konkurrere med mat og natur.",
    5: "Tropisk orkan: varmt hav, coriolis, fuktig luft, lav skjærvind. Dør over land. Øyet er rolig, veggen har den sterkeste vinden.",
    6: "Vind driver overflatestrømmer. Ekman: transport 90° til høyre for vinden på nordlige halvkule. Det bygger opp gyre og opp/nedveling.",
    7: "Jorda emitterer IR. Høyere temperatur → mer utstråling (σT⁴). Skyer og drivhusgasser fanger noe av det. Les figuren for hvilket belte som emitterer mest til verdensrommet.",
    8: "Over innlandsis: katabatisk utstrømning, høytrykk over isen. Vind retning ut fra isen, bøyd av coriolis.",
    9: "Ekmantransport 90° til høyre (NH). Langs en kyst med vind mot nord på vestkysten av et kontinent: oppveling. Motsatt: nedveling.",
    10: "Tettest vann: kaldt og salt. I Norskehavet / Grønlandshavet synker slikt vann og driver AMOC.",
    11: "Overflatestrømmer følger vinden og gyren. Dypvann følger tetthet. Golfstrømmen er vestlig randstrøm i den subtropiske gryra.",
    12: "Orkaner dannes over tropisk hav, ikke på ekvator (for svak coriolis) og ikke over kaldt vann. De svinger med de storskala vindene.",
    13: "Positivt strålingspådriv varmer, negativt kjøler. CO₂ er positivt. Sulfataerosoler er ofte negative.",
    14: "Permafrost: bakke som er frosset i minst to år. Styres av lufttemperatur, snødekke, vegetasjon og vann. Tining slipper karbon og metan.",
    15: "Orografisk nedbør på losiden av fjell. Regnskygge på lesiden. Polarfrontnedbør der varm og kald luft møtes.",
    16: "Snøskred: nysnø, vindtransportert snø, mildvær og regn på snø. Knytt værsituasjonen til skredproblem, ikke bare «det snødde».",
    17: "Klimadiagram: temperaturkurve og nedbørsøyler. Les tørke når evapotranspirasjon > nedbør, og sesong når kurven svinger mest.",
    18: "Mest sannsynlige: vulkanutbrudd (aerosoler), lav solflekkaktivitet (Maunder-minimum) og langvarig negativ NAO. Platetektonikk og Milanković virker på millionår, ikke århundrer. La Niña alene holder ikke en 300-års kuldeperiode. Velg påstand 2, 4 og 6.",
    19: "Jetstrømmen følger polarfronten. Sterk temperaturkontrast = sterk jet. Den styrer lavtrykkenes bane mot Norge.",
    20: "El Niño: varmt overflatevann i østlige Stillehav, svekket passat. La Niña: tvert om. Telekoblinger flytter nedbør og tørke.",
    21: "a) Les satellitt, radar og observasjon sammen: skytype, front og nedbør på Blindern kl. 09. b) Temperatur følger adveksjon og skydekke utover dagen. c) Nedbør følger frontpassasje — byger bak kaldfront, jevn nedbør ved varmfront.",
    22: "Drøft tidevann, bølge, havvind, havvarme og sol mot miljø, forutsigbarhet og norsk geografi. Ikke konkluder med ett «beste» uten forbehold.",
  },
  h2023: {
    1: "Lavere albedo kommer først og fremst av at is og snø viker for mørkere hav og land. «Havet utgjør en større del av overflaten» er den mekanismen. Flere hvite skyer øker albedo. Is-albedo er en positiv, ikke negativ, tilbakekobling. Permafrost tining er først karbon, ikke albedo.",
    2: "Luftas tetthet styres mest av trykket, som faller raskt med høyden. Temperatur og fuktighet betyr også noe, men trykkendringen med høyde er den store gradienten.",
    3: "Positiv ozonutvikling i stratosfæren (ca. 30–45 km) etter Montreal-protokollen: mer ozon der oppe. Ikke forveksle med bakkenært ozon. Velg påstanden som sier mer ozon i det høydeintervallet.",
    4: "Klare netter: bakken stråler IR til verdensrommet. Skyer absorberer og emitterer IR tilbake, så nettotapet blir mindre. Det er derfor overskyede netter er mildere.",
    5: "Årlig solinnstråling i Norge er størst i sør og innland med lite sky, ikke nødvendigvis kysten. Klikk der julikartet og januar-kartet sammen gir mest Wh/m².",
    6: "800 Wh/m² per dag × 365 × 25 m² = 7 300 kWh/år før virkningsgrad. Solceller tar typisk 15–20 %, altså rundt 1 100–1 500 kWh — langt under 16 000 kWh. Familien klarer seg ikke på den flaten alene.",
    7: "Tidevannskraft: høydeforskjell flo/fjære og bevegelsesenergi i strømmen. Ikke bølgekraft og ikke termisk energi.",
    8: "Havnivå stiger ikke jevnt. Vind, strøm og gravitasjon (smeltende iskapper) gir regionalt fall noen steder. Les fargeskalaen; den hvite linjen er nullendring.",
    9: "Les oppgaven og figuren. Bruk enhetene. Ikke gjett på farger uten skala.",
    10: "To millioner år i Norge: havbunnssediment og bergarter/fossiler. Iskjerner, pollen, treringer og historiske kilder rekker ikke så langt her.",
    11: "Følg instruksen i oppgaven. Koble prosess til figur, ikke til et ferdig memorert kart.",
    12: "Samme: les aksene først, så påstanden.",
    13: "Beste iskjernested: tjukk is, liten flyt, isskille / høyt platå — ikke isstrøm. På Grønland: indre høyland, ikke kysten.",
    14: "Fortsett å lese kart og profiler. Vis at du skiller flytretning fra mektighet.",
    15: "Når oppgaven ber om flere kryss, er det ofte to riktige. Ikke marker alle.",
    16: "Paleoklima vs instrumentell tid: iskjerne og sediment for det lange, termometer for det korte.",
    17: "Katabatisk vind: kald, tett luft som renner nedover av tyngdekraften, typisk fra innlandsis. Ikke monsun og ikke lavtrykksvind.",
    18: "Sjekk definisjonen i læreboka mot alternativene. Ett er presist, de andre blander fenomener.",
    19: "Bruk figuren. En påstand uten dekning i data er usann selv om den høres geofaglig ut.",
    20: "Siste interaktive i kategorien: ofte et kartvalg. Marker der prosessen faktisk skjer.",
    21: "Fem figurer om varmeutveksling hav–atmosfære. a) Hvor havet avgir varme til lufta (typisk Golfstrømmen om vinteren). b) Atmosfæren over det varme vannet. c) Konsekvens for klima i Nord-Europa. Les alle delene før du skriver.",
    22: "a) Permafrost: temperatur, snø, vegetasjon, vann, eksponering. b) Metan er en sterk, kortlevd drivhusgass — stort strålingspådriv per kilo. c) Permafrostgrensa flytter seg med klima og er derfor indikator. d) Naturlige kilder (våtmark, hydrater) vs menneske; hold de to fra hverandre.",
  },
  h2024: {
    1: "Farevarsel for sterk vind matcher værkartet der isobarene er tettest og vinden peker samme vei som varslet. Klikk det kartet, ikke det med slakt trykkfelt.",
    2: "Coriolis: avbøyning til høyre på nordlige, til venstre på sørlige, for både luft og hav. Påstand 1 er sann. Påstand 2 er usann (skal være høyre i nord). Resten følger samme regel.",
    3: "Lavtrykkssenter: skyene spinner mot urviseren, og det er ofte et roligere øye / kommakommen. Klikk midt i spiralen, ikke i fronten.",
    4: "Under ~500 m varierer tettheten lite fordi vannet er kaldt, sjiktningen er svak og blandingen er god. Overflaten sjiktes av varme og ferskvann. Marker de to dyp-forklaringene, ikke overflateforklaringene.",
    5: "ITCZ er det våte beltet nær ekvator. Polarfronten er et smalere, svakere nedbørsbelte. Påstanden om mer nedbør langs ITCZ enn polarfronten er sann.",
    6: "På sørlige halvkule spinner lavtrykk med urviseren. Videoen viser trykksenteret i midten — det er et L hvis lufta går inn og rundt med urviseren.",
    7: "Høyest overflatetemperatur der skydekket er tynnest og innstrålingen størst, eller der luftmassen er tropisk. Klikk boksen over det klareste, laveste skydekket — ikke den tykke fronten.",
    8: "Tidevann er forutsigbart (astro), fremdeles ganske dyrt, og det påvirker flora og fauna i fjord/estuarium. Ikke «ustabil» og ikke «billig og ferdig utviklet». Velg påstand 2, 3 og 6.",
    10: "Ekvator: netto pluss (mottar mer enn den sender ut). Polene: netto minus. Det er energitransporten mot polene. Velg påstand 1 og 2.",
    13: "Havet tar >90 % av ekstraenergien, men havnivået reagerer tregt: termisk utvidelse og issmelting tar tiår–århundrer. Atmosfæren har lav varmekapasitet og varmes raskere. Velg at havnivået er koblet til tregere prosesser.",
    17: "E ∝ v³. Dobbelt så høy vind (5 → 10 m/s) gir 2³ = 8 ganger så mye energi. Åttedobling.",
    20: "a) Like utenfor LGM-isranden: kjernen kan vise når isen sto der, smeltevann, sjøis og produktivitet (proxyer, planktonmarkører). Si hva hver figurtype faktisk måler. b) Les proxyene mot sjøisklassene i figur 3 — ikke gjett på farger uten skala.",
    21: "a) Katabatisk = kald fallvind; føn = varm, tørr leside etter orografisk heving. Du kjenner temperatur og fukt, ikke bare retning. b) Varmere klima: mer vanndamp, høyere skynivå, ofte mer ekstremnedbør på losiden. c) Mindre arktisk is → svakere temperaturgradient → jet og stormbane kan ligge lenger nord. d) Fønvind + mildvær på lesiden av Jostedalsbreen øker skredfare der snøen blir våt og vinden laster lesider.",
  },
  h2025: {
    1: "Strålingsbalanse ved bakken er i likevekt i figuren: inn = ut. Velg påstanden som sier det, ikke at jorda «mangler» energi eller at sola alene forklarer alt.",
    2: "For varme Arktis i Holocen-modellen: albedo (is/snø) er den klassiske feilen. Metan og vegetasjon kan også mangle, men oppgaven spør etter den mekanismen som ikke er godt nok med.",
    3: "Kraftig nedbør ved fronten / der fuktig luft heves, ikke i høytrykket. Sted  med tettest isobarer og frontsymbol vinner. Les MET-kartet.",
    4: "Tyngst overflatevann: kaldt og salt. Middelhavet er tett på grunn av fordamping (salt), ikke Indiahavet. Marker sann/usann deretter.",
    5: "Årringer: kaldt år = tynn ring hvis veksten styres av temperatur; vått år = tykk ring hvis den styres av nedbør. Les linjalen og velg den tynneste / tykkeste ringen.",
    6: "Coriolis er null på ekvator og sterkest ved polene (2Ω sin φ). Klikk sirkelen nærmest en pol, ikke tropene.",
    7: "Dyphavsstrømmer drives av tetthetsforskjeller (temperatur og salinitet) — termohalin sirkulasjon. Vind driver overflaten. Coriolis bøyer, tidevann er lokalt.",
    8: "Elvevann er ferskere og dermed lettere enn kystvann. Det legger seg oppå. Temperatur alene er ikke hovedgrunnen i en typisk fjord.",
    10: "Høy eksentrisitet gir større årstidsforskjeller og mer sjanse for at sommersnø overlever på 65°N. Les figuren og velg tidspunktet med høyest eksentrisitet.",
    13: "Anomalien mot 1920–1940 blir større enn mot 2010–2024 hvis den tidlige perioden var kaldere. Det er den: 1920–1940 var kaldere enn 2010–2024.",
    17: "Alpin permafrost er lite areal sammenlignet med arktisk. Metanutslipp derfra er den minste trusselen av de tre. Skred i tinet arktisk permafrost og isskred i alpine fjell rammer folk og infrastruktur hardere.",
    20: "Smeltevann øker stratifisering (motsatt av «mindre»). Salinitet i polaroverflaten synker, ikke øker. Varmere overflate blir lettere, ikke tettere. Av alternativene er svekket trykkgradient / svakere vind det som kan redusere nordlig varmetransport. De tre første feilene er vanlige feller.",
    21: "Global oppvarming: mer IR tilbake fra drivhusgasser, bakken og troposfæren varmer, utgående langbølge øker til ny likevekt på høyere temperatur. Kortbølge endres via albedo og skyer. Bruk Bjerknes-figuren og si hvilke piler som endres.",
    22: "Blått = permafrost som kan forsvinne mot 2060, grønt = som kan bli igjen. A (kyst, blå) er mer utsatt enn B (kyst, grønn) og C (innland, blå) mer enn D. Sjøis påvirker bølge, stormflo og kysterosjon i A — den fjerde påstanden er usann.",
    23: "Vestavindsbeltet driver Den antarktiske sirkumpolare strømmen østover. Polar østavind nærmest kysten driver kyststrømmen vestover («East Wind Drift»). Si celle + coriolis, ikke bare «vinden blåser».",
  },
  eksempel: {
    1: "To Europakart for juli 2025. Polen: les om det er hete, tørke eller flom i kartet, og koble til naturfare (skogbrann, tørke, oversvømmelse).",
    2: "Hellas: samme kartpar. Hetebølge og tørke peker på skogbrann og vannmangel, ikke snøskred.",
    3: "Temperaturanomali over hav: positiv anomali = marin hetebølge-risiko. Koble lufttemperatur, havtemperatur og værtype.",
    4: "Alpebreer: varm juli-anomali → negativ massebalanse. Les kartet, ikke anta alle breer smelter likt.",
    5: "Plassholder i Udirs eksempel. Hopp over, eller øv på marin hetebølge i Lofoten med egne kart.",
    6: "Skrive: menneskelig pådriv vs naturlig variasjon. Bruk kartene som evidens, ikke som pynt. Henvis til Climate Reanalyzer.",
    7: "Tema 2 åpner AMOC. Skill Golfstrøm (vindgyre) og AMOC (omveltning).",
    8: "Vil AMOC kollapse? Referer argumentene: ferskvann og oppvarming mot vinddrevet Golfstrøm og urealistiske modelldoser. Si hva som er enighet (svekkelse) og uenighet (kollaps).",
    9: "Interaktiv AMOC-figur. Marker der vannet synker (Nord-Atlanteren / Grønlandshavet), ikke i Mexicogolfen alene.",
    10: "Dataoppgave. Les enheter. En modellbane er ikke en observasjon.",
    11: "Skrive: AMOC og modeller. Bruk Udirs vedlegg. Skill scenario, usikkerhet og konsekvens for Norge.",
    12: "Skrive: fortsett på samme spor. Vis kilder.",
    13: "Felt: GPS, profil, usikkerhet, HMS. Skriv hva dataene faktisk viser, ikke hva du ønsket å finne. CTD: les T, S og tetthet sammen — tropisk profil er varm og fersk i toppen, subpolar er kald og gjennomblandet.",
    23: "Plassholder hos Udir: ekstremvær mot havvind. Tenk bølger, ising, stormflo og tilkomst. Ikke et ferdig fasitsvar.",
    24: "Plassholder: værvarsling for havvind. Skill prognosehorisont, usikkerhet og operasjonelle terskler (vind, bølger).",
    25: "Plassholder: bærekraft. Avvei energi, natur, fiskeri og forsyningssikkerhet. Ikke konkluder med ja/nei uten forbehold.",
  },
};

export function solutionFor(slug: string, number: number): string | undefined {
  return SOLUTIONS[slug]?.[number];
}
