/** Løsningsforslag. Interaktive nøkler for V2026, H2025, V2025 og V2024 er sjekket mot Udirs publiserte forhåndssensur/sensorveiledning. Teksten er omskrevet — ikke avskrift av Udir. */

export const SOLUTIONS: Record<string, Record<number, string>> = {
  v2026: {
    1: "Udir-fasit: alternativ d — vinden kommer fra sørvest. Lavtrykket i Norskehavet spinner mot urviseren. Når senteret treffer Nordland, ligger X sør for senteret, så innsuget der er sørvestlig. Nordøst, nordvest, nord og øst er feil for den plasseringen.",
    2: "Udir-fasit: alternativ c — påstand 2 og 4 er sanne. Påstand 2: 28,67 °C som rekord siden 1991 stemmer med figuren. Påstand 4: lite vind og klarvær øker innstråling og svekker blanding, og det fremmer marin hetebølge. 1 (~10 °C anomali) er usann. 3 (vulkanisme) er usann. 5 (hele Middelhavet like hardt) er usann.",
    3: "Udir-fasit: alternativ b. Høyere global middeltemperatur gir hyppigere hetebølger, som øker tørke og vannmangel. Urbanisering kjøler ikke byer. Mer vegetasjon gir ikke mer skogbrann som hovedlenke. Luftforurensning som reduserer solinnstråling gir ikke sterkere hetebølge.",
    4: "Udir-fasit: alternativ c. Tropiske sykloner lever av varmt hav. Langt nord mister de varmekilden og dør ut. Derfor når de sjelden Europa. Coriolis «for sterk» og vestavinden som river syklonen i stykker er ikke hovedårsaken.",
    5: "Udir-fasit: alternativ a — flere og mer langvarige kuldebølger. Oppgaven peker på at den polare jetstrømmen endrer bane ved global oppvarming (slakkere, mer meandrerende jet og blocking). Det er dette Udir teller som riktig, ikke IPCC-hovedfunnet om færre kuldeekstremer globalt.",
    6: "Skriv om værsituasjonen, ikke om hvorfor Met sender farevarsel generelt. Gyda er en smal, fuktig luftstrøm fra varmt hav inn mot Vestlandet og Trøndelag (atmosfærisk elv — ordet er ikke påkrevd). Orografisk heving mot fjellene gir ekstremnedbør. Bruk både prognosekartet (mørkeblå fuktighet) og farevarselet, og koble dem. Kartene teller som kilder.",
    7: "Udir-fasit: alternativ a. Kaldt ferskvannssmeltevann er tyngre enn romtemperert ferskvann og synker. I saltvann er smeltevannet lettere og blir liggende oppå. Glasset til venstre, der fargen legger seg langs bunnen, er ferskvann.",
    8: "Udir-fasit: alternativ b. Vannmasse A (1 °C, 29,7 PSU) er tyngre enn B (−0,8 °C, 29,4 PSU) og legger seg under. Les isopyknalene: A ligger på høyere tetthetslinje.",
    9: "Udir-fasit: B og C er fra april, A og D fra august. April: kaldere, mer gjennomblandet, ofte saltere i toppen. August: varmere og ferskere i de øverste meterne (smeltevann og oppvarming). Velg temperaturprofil B + salinitetsprofil C for april, og A + D for august.",
    10: "Udir-fasit: medvirkende c og e, ikke a, b og d. Medvirkende: is- og snøalbedo som synker, og endret vertikal temperaturgradient (lapse-rate). Ikke: mer vanndamp enn i tropene, sterk vertikal blanding i arktisk troposfære, eller «mer klimagasser enn andre regioner».",
    11: "Sett punktet i overgangen fra mørkt til lyst på batymetrikartet (dypt til grunt). Begrunn med alle tre: motgående havstrøm som bremser og steiler bølger, brå dybdeendring som konsentrerer energi, og vind som bygger bølger. Vind og strøm skal ha motsatt retning. Navn på strømmer er ikke krav — prosessene er det.",
    12: "Vurder alle fire. 1 og 4 er usanne ut fra grafene (kortvarig hopp 2015–2020 er ikke «kraftig global oppvarming»; polart vann er ikke saltere enn atlantisk). 3 er sann: atlantisk vann blir saltere, knyttet til varmere klima og fordamping. 2 kan argumenteres begge veier — smeltevann kan senke temperatur og salinitet i toppen; selvstendig vurdering teller. Les riktig panel for hver påstand.",
    13: "Udir-fasit: alle tre er sanne. Perihelium ved NH-vinter: små årstidsforskjeller i nord. Aphelium ved NH-sommer er samme geometri og gir store årstidsforskjeller i sør. Aphelium ved NH-vinter gir varme NH-somre og mindre sjanse for istid. To av tre rette ga 0,5 poeng i sensuren.",
    14: "Udir-fasit: alternativ b. Ved 65°N svinger sommersola mye og styrer om snøen overlever. Ved ekvator er innstrålingen jevn hele året. Rotasjonshastighet og «større avstandsendring ved 65°N» er feil.",
    15: "Udir-fasit: alternativ b. Positive tilbakekoblinger øker nedkjølingen ytterligere. Negative motvirker. «Alltid tilbake til balanse» og «negative dominerer i kaldt klima» er feil.",
    16: "Udir-fasit: alternativ d. Større isvolum 750–450 ka betyr kjøligere klima, forsterket av positive tilbakekoblinger. Ikke «varmere», ikke «mindre usikkerhet», ikke negative tilbakekoblinger som hovedforklaring.",
    17: "Udir-fasit: alternativ d. Innlandsis dekker bakken og stenger for permafrost. Nord-Amerika hadde den største Laurentide-isen, derfor mindre permafrostareal der. Eurasia hadde mer bart, kaldt land.",
    18: "Knytt naturfarene til overgangen istid → mellomistid og til tapt sjøis, minst to farer: endret lavtrykksaktivitet (polare lavtrykk), høyere bølger og kysterosjon, tining av kystnær permafrost, mer fukt og nedbør (eventuelt skred), mer smelting av innlandsis. Smeltende sjøis hever ikke havnivået alene.",
    19: "Udir-fasit: alternativ b. Massebalansen etter 2000 er gjennomgående negativ — det peker på oppvarming. Ålfotbreen er den maritime (mer vinternedbør), Hellstugubreen den kontinentale. Volum øker ikke når sommerbalansen slår vinterbalansen. Hellstugubreen ligger ikke vest for Ålfotbreen.",
    20: "Udir-fasit: alternativ a. Negativ NAO: kalde og tørre vestlandsvintre, lite snø, negativ vinterbalanse. Positiv NAO gir milde, våte vintre — ikke tørre eller kalde.",
    21: "Udir-fasit: feil — riktig — feil. Første påstand beskriver fønvind, ikke katabatisk. Katabatisk dannes ofte på lesiden av isdekte fjell (kald fallvind). Synkende katabatisk luft er tørr og lager sjelden skyer.",
    22: "Udir-fasit: alternativ b. Loside 14 °C. Tørradiabat 1 °C/100 m opp til skybase 800 m → 6 °C. Våtadiabat 0,5 °C/100 m videre 1200 m til toppen → 0 °C. Leside tørradiabat 2000 m ned → 20 °C.",
    23: "Udir forventer vurdering av alle fire: 1 usannsynlig (solvinkel endres ikke; mer fukt kan gi mer sky). 2 betinget sann (mer vannkraft under smelting, mindre når breen er borte; bærekraft og naturinngrep). 3 usann (varmere klima gir mer ustabilitet, ikke stabile fønvinder; lite vindkraftpotensial i føn). 4 sannsynlig (mer vind kan øke produksjon). Argumentasjonen teller mer enn om du lander «rett» merkelapp.",
  },
  v2025: {
    1: "Udir-fasit: alternativ a. Svekket nordatlantisk strøm / AMOC gir mindre varmetransport mot Norge. Vestlandet blir kaldere. Mindre varme og fukt fra havet gir også mindre nedbør.",
    2: "Udir-fasit: alternativ b. To mekanismer i ett: Grønlandsisen smelter og tilfører kaldt ferskvann som kan stanse dypvannsdannelsen. Økt fordamping som «lik densitet» er feil. Regn som stanser sjøis er ikke hovedforklaringen.",
    3: "Udir-fasit: alternativ c — påstand 1 og 2. Sol og lite sky, pluss svak vind og sterk sjiktning, fremmer marin hetebølge. La Niña gir ikke typisk slike hetebølger i østlige Stillehav. Hetebølger gir sterkere, ikke svakere, tropiske orkaner.",
    4: "Udir trakk oppgaven (skrivefeil i bokmålsutgaven: to like alternativ). I nøkkelen sto b: global temperatur påvirkes lite av mer ozon i 20–30 km. Tell den ikke med i øvingen.",
    5: "Udir-fasit: rett — galt — rett. Lavere albedo øker absorbert sol. Permafrost som tiner gir ikke alltid lavere albedo. Satellitter kan måle albedo.",
    6: "Udir-fasit: ekvator = svart graf med rundinger, sørlig halvkule = grønne grafer med streker, nordlig = oransje graf med trekanter. Ekvator er jevnest (to små topper). NH har maksimum i juni–juli, SH i desember–januar.",
    7: "Udir-fasit: farevarsel 2. Les trykk, front og vind i ringen over Finnmark og match det varselet som faktisk hører til analysekartet — ikke skogbrann eller et varsel som ikke passer situasjonen.",
    8: "Udir-fasit: alternativ a. Det ekvatorielle lavtrykksbeltet ligger litt nord for ekvator — det er ITCZ om NH-sommer. Det er ikke høytrykk ved ekvator. Sirkulasjon med klokken i det markerte senteret er ikke automatisk høytrykk uten å vite halvkule. Blått i Sørishavet er ikke «høytrykk».",
    9: "Udir-fasit: alternativ a. Høyere ¹⁸O/¹⁶O i foraminiferer oppover i kjernen betyr kaldere hav. Varmere vann, høyere havnivå og «mer salt» er feil slutning her.",
    10: "Udir-fasit: alternativ c — påstand 1, 2 og 3. Vulkanutbrudd, lav solflekkaktivitet og langvarig negativ NAO er de sannsynlige årsakene til den lille istiden. Platetektonikk og Milanković virker på millionår. La Niña alene holder ikke en 300-års kuldeperiode.",
    11: "Udir-fasit: alternativ 1 — påstand 1 og 2 er sanne. Polare lavtrykk intensiveres raskt og dannes der det er få stasjoner. De dannes over åpent, isfritt hav, ikke «langt inne på sjøisen», og de synes på satellitt.",
    12: "Udir-fasit: usann — usann — usann — usann — sann. Høyre panel er ikke NH. Årstidsutslaget er ikke like stort på begge. Venstre har ikke større årstidsvariasjon enn høyre. Sjøis påvirker lufttemperatur. Septemberutbredelsen i venstre panel er lavere 2010–2024 enn 1980–2000.",
    13: "Udir-fasit: alternativ a — sterkest vind ved X på Island. Vindstyrke leses av isobaravstand: tette isobarer = sterk vind. Y og Z har slakere trykkfelt.",
    14: "Udir-fasit: alternativ c — bare påstand 2 er sann. Høy fordamping relativt til nedbør gir høy salinitet. Elvemunninger fortynner. Mye nedbør senker salinitet. Kaldt vann er ikke automatisk saltere.",
    15: "Udir-fasit: alternativ d. Klimagasser absorberer utgående langbølge. De stanser ikke solinnstrålingen, senker ikke albedo, og øker ikke utstrålingen fra bakken som primær mekanisme.",
    16: "Udir-fasit: alternativ b. Troposfæren varmes primært nedenfra av langbølge fra jordoverflaten. Direkte solvarme i lufta, varmeledning og bakkenært ozon er ikke hovedårsaken.",
    17: "Udir-fasit: alternativ a. I stratosfæren stiger temperaturen med høyden (stabil sjiktning), så konveksjon og skyer stanses. «Ustabil» er feil. Vanndampmengden alene er ikke Udirs valgte forklaring.",
    18: "Udir-fasit: alternativ d — stormflo. Vind, hagl og lyn tar færre liv enn vannet som presses på land.",
    19: "Udir-fasit: alternativ d. Lite sol og tørr bakke om sommeren begrenser tining og holder permafrosten. Tykt tidlig snødekke isolerer mot vinterkulde (kan svekke permafrost). Tynt torvdekke og mye vann som fryser øker varmeledning og er ikke det som «opprettholder» den best.",
    20: "Udir-fasit: usann — usann — usann — sann — sann. Golfstrømmen er ikke én kontinuerlig elv inn i Norskehavet. AMOC er ikke vinddrevne overflatestrømmer. Golfstrømsystemet er ikke et vertikalt omveltningssystem. Subtropiske gyre drives av vind og gravitasjon. AMOC kan svekkes uten at gyren stopper.",
    21: "a) Bilde 1 er varmfront (tynnere, mer utstrakt sky, sakte heving). Bilde 2 er kaldfront (tykkere sky, rask heving). Beskriv hva du ser, og forklar prosessen. b) Fem påstander om varme/kalde skyer: 1 sann (kartet er rødt / positiv endring). 2 usann (Peru har fortsatt flest varme skyer). 3 usann (varme skyer reflekterer mer → negativt pådriv). 4 sann (flere kalde skyer → mindre refleksjon → positivt pådriv). 5 sann (lengre levetid forsterker pådrivet). Begrunn alle fem.",
    22: "a) To sanne: 1 (avslått AMOC = ingen dypvannsdannelse, synlig i figur 1a) og 3 (høy CO₂ krever mer negativ ferskvannstilførsel for sterk AMOC, figur 2d). 2 og 4 er usanne. b) Paleodata og AMOC: velg proxyer fra kartet (havbunn, iskjerme, innsjø, myr), si tidsskala og hva ¹⁸O, plankton og fossiler faktisk måler, og knytt det til Nord-Atlanteren. Ikke avskrift.",
    23: "a) Velg et avgrenset område i Norge. Økt årsnedbør kommer ujevnt: mer styrtregn og flom/skred noen sesonger, tørke i andre, pluss kryosfærefarer. b) Drøft om den økonomiske modellen er realistisk for Norge: lengre vekstsesong og turisme mot flom, skred, stormflo, kortere snøsesong og internasjonale kostnader. Usikkerhet i modellen skal med.",
  },
  v2024: {
    1: "Udir-fasit: stedet merket med trekant har den sterkeste vinden. Les isobaravstanden — trekanten står der linjene er tettest.",
    2: "Udir-fasit: CO₂, CH₄, H₂O. CO₂ fjernes over geologisk tid i havet. Ved oksygenfattig nedbryting dannes metan. Av CO₂, CH₄ og H₂O har vanndamp kortest levetid. Alle tre må være rett.",
    3: "Udir-fasit: A. Varmfronten skal ligge der temperaturkontrasten og den varme sektoren faktisk er, ikke tvers gjennom kaldlufta.",
    4: "Udir-fasit: både a og b er sanne. Klorofyllkartet viser at produksjonen ikke følger «varmest = mest» — næringsstoffer og oppveling styrer mer enn direkte sol. c og d er usanne.",
    5: "Udir-fasit: påstand 1, 4 og 6. Pilen peker på øyet: nesten vindstille, uten nedbør, og vannstanden rundt øya er høy. Sterk vind, kraftig regn og lav vannstand hører til øyeveggen, ikke øyet.",
    6: "Udir-fasit: A og B. Overflatestrømmen er sterkest der vinden er sterkest i figuren — de to posisjonene i den kraftigste delen av lavtrykket.",
    7: "Udir-fasit: H₂O = blå, CO₂ = rød, O₃ med flere = svart. Match absorpsjonsdalene i spekteret A mot grafene i B.",
    8: "Udir-fasit: pilen ned fra isen. Innlandsisen lager katabatisk utstrømning — kald luft renner nedover mot kysten.",
    9: "Udir-fasit: vestlig retning. Vind fra sør langs vestkysten av Australia (sørlige halvkule): Ekmantransport 90° til venstre, altså vestover, bort fra kysten (oppveling).",
    10: "Udir-fasit: A og D. Overflatevann ved ekvator er lett fordi det er varmt og har lav salinitet (mye nedbør i ITCZ).",
    11: "Udir-fasit: 1 og 3. Termohalin sirkulasjon transporterer energi. Dypvann dannes når vannet blir kaldere og/eller saltere. Mindre fordamping driver ikke overflatestrømmene. Ferskvann svekker, ikke øker, den termohaline transporten.",
    12: "Udir-fasit: lavtrykk · litt nord eller sør for ekvator · vanndamp · stormflo · i Mexicogolfen · avta. Fem eller seks rett ga poeng.",
    13: "Udir-fasit: kan føre til positivt strålingspådriv. Mindre havis senker albedo og øker absorbert sol.",
    14: "Udir-fasit: permafrosten på Jansonhaugen har blitt svekket. Nullgradersisotermen flytter seg slik figuren viser dypere tining / slakere gradient — ikke tynnere aktivt lag og ikke «dypere permafrost».",
    15: "Udir-fasit: på den sørøstlige siden. Øya ligger på 20–25°S i passaten. Fuktig sørøstpassat tvinges opp på losiden; lesiden ligger i regnskygge.",
    16: "Udir-fasit: moderat nedbør, kraftig vind og stigende temperatur før skredet. Det er nysnø pluss vindtransport og mildvær — ikke fallende temperatur og lite vind.",
    17: "Udir-fasit: diagrammet øverst til venstre. Innlandsklima: stor årlig temperaturamplitude og ofte et tydelig sommernedbørsmønster, ikke maritimt flatt.",
    18: "Udir-fasit: påstand 2, 4 og 6. Vulkaner, Maunder-minimum og negativ NAO. Platetektonikk og Milanković er feil tidsskala. La Niña alene holder ikke 300 år.",
    19: "Udir-fasit: A, D og E. Mildt sørvest der jetten ligger over/nærmest, kaldt i nordøst bak den kalde siden, og fukt i midtre Norge under jetens nedbørsbelte. Les fargene mot Norge.",
    20: "Udir-fasit: hendelse 1, 2 og 3. El Niño: tørke i Indonesia 1997–98, flom i Paraguay/Uruguay/Argentina 2010, flom i Øst-Afrika 2019. Europa-flommen 2021 og Peru-tørke 2022 er ikke de klassiske El Niño-koblingene Udir teller her.",
    21: "a) Bruk analysekart, satellitt, observasjon og radar sammen: temperatur, vind, nedbør og skydekke på Blindern kl. 09. Forklar, ikke bare beskriv. b) Temperatur mot midnatt: mulig varmfront hever temperaturen; kaldfronten kan rekke å passere og senke den igjen. At kaldfronter går fortere enn varmfronter er nok — beregning er bonus. c) Nedbør følger frontene: jevn nedbør ved varmfront, byger bak kaldfront. Usikkerhet belønnes.",
    22: "Dette er opplastingsoppgaven (kategori 3). Drøft fornybar energi mot norsk geografi, forutsigbarhet og miljø — tidevann, bølge, havvind, havvarme, sol. Ikke konkluder med ett «beste» uten forbehold. Oppgi kilder. 22c var lavt vektet i sensuren fordi formuleringen traff læreplanen dårlig.",
  },
  h2023: {
    1: "Lavere albedo kommer først og fremst av at is og snø viker for mørkere hav og land. «Havet utgjør en større del av overflaten» er den mekanismen. Flere hvite skyer øker albedo. Is-albedo er en positiv, ikke negativ, tilbakekobling. Permafrost tining er først karbon, ikke albedo. (Ingen publisert Udir-fasit for H2023.)",
    2: "Luftas tetthet styres mest av trykket, som faller raskt med høyden. Temperatur og fuktighet betyr også noe, men trykkendringen med høyde er den store gradienten.",
    3: "Positiv ozonutvikling i stratosfæren (ca. 30–45 km) etter Montreal-protokollen: mer ozon der oppe. Ikke forveksle med bakkenært ozon. Velg påstanden som sier mer ozon i det høydeintervallet.",
    4: "Klare netter: bakken stråler IR til verdensrommet. Skyer absorberer og emitterer IR tilbake, så nettotapet blir mindre. Det er derfor overskyede netter er mildere.",
    5: "Årlig solinnstråling i Norge er størst i sør og innland med lite sky, ikke nødvendigvis kysten. Klikk der julikartet og januar-kartet sammen gir mest Wh/m².",
    6: "800 Wh/m² per dag × 365 × 25 m² = 7 300 kWh/år før virkningsgrad. Solceller tar typisk 15–20 %, altså rundt 1 100–1 500 kWh — langt under 16 000 kWh. Familien klarer seg ikke på den flaten alene.",
    7: "Tidevannskraft: høydeforskjell flo/fjære og bevegelsesenergi i strømmen. Ikke bølgekraft og ikke termisk energi.",
    8: "Havnivå stiger ikke jevnt. Vind, strøm og gravitasjon (smeltende iskapper) gir regionalt fall noen steder. Les fargeskalaen; den hvite linjen er nullendring.",
    9: "Les oppgaven og figuren. Bruk enhetene. Ikke gjett på farger uten skala.",
    10: "To millioner år i Norge: havbunnssediment og bergarter/fossiler. Iskjerner, pollen, treringer og historiske kilder rekker ikke så langt her.",
    11: "Følg instruksen i oppgaven. Koble prosess til figur, ikke til et ferdig memorert kart.",
    12: "Samme: les aksene først, så påstanden.",
    13: "Beste iskjernested: tjukk is, liten flyt, isskille / høyt platå — ikke isstrøm. På Grønland: indre høyland, ikke kysten.",
    14: "Fortsett å lese kart og profiler. Vis at du skiller flytretning fra mektighet.",
    15: "Når oppgaven ber om flere kryss, er det ofte to riktige. Ikke marker alle.",
    16: "Paleoklima vs instrumentell tid: iskjerne og sediment for det lange, termometer for det korte.",
    17: "Katabatisk vind: kald, tett luft som renner nedover av tyngdekraften, typisk fra innlandsis. Ikke monsun og ikke lavtrykksvind.",
    18: "Sjekk definisjonen i læreboka mot alternativene. Ett er presist, de andre blander fenomener.",
    19: "Bruk figuren. En påstand uten dekning i data er usann selv om den høres geofaglig ut.",
    20: "Siste interaktive i kategorien: ofte et kartvalg. Marker der prosessen faktisk skjer.",
    21: "Fem figurer om varmeutveksling hav–atmosfære. a) Hvor havet avgir varme til lufta (typisk Golfstrømmen om vinteren). b) Atmosfæren over det varme vannet. c) Konsekvens for klima i Nord-Europa. Les alle delene før du skriver.",
    22: "a) Permafrost: temperatur, snø, vegetasjon, vann, eksponering. b) Metan er en sterk, kortlevd drivhusgass — stort strålingspådriv per kilo. c) Permafrostgrensa flytter seg med klima og er derfor indikator. d) Naturlige kilder (våtmark, hydrater) vs menneske; hold de to fra hverandre.",
  },
  h2024: {
    1: "Farevarsel for sterk vind matcher værkartet der isobarene er tettest og vinden peker samme vei som varslet. Klikk det kartet, ikke det med slakt trykkfelt. (Ingen publisert Udir-fasit for H2024.)",
    2: "Coriolis: avbøyning til høyre på nordlige, til venstre på sørlige, for både luft og hav. Påstand 1 er sann. Påstand 2 er usann (skal være høyre i nord). Resten følger samme regel.",
    3: "Lavtrykkssenter: skyene spinner mot urviseren, og det er ofte et roligere øye / kommakommen. Klikk midt i spiralen, ikke i fronten.",
    4: "Under ~500 m varierer tettheten lite fordi vannet er kaldt, sjiktningen er svak og blandingen er god. Overflaten sjiktes av varme og ferskvann. Marker de to dyp-forklaringene, ikke overflateforklaringene.",
    5: "ITCZ er det våte beltet nær ekvator. Polarfronten er et smalere, svakere nedbørsbelte. Påstanden om mer nedbør langs ITCZ enn polarfronten er sann.",
    6: "På sørlige halvkule spinner lavtrykk med urviseren. Videoen viser trykksenteret i midten — det er et L hvis lufta går inn og rundt med urviseren.",
    7: "Høyest overflatetemperatur der skydekket er tynnest og innstrålingen størst, eller der luftmassen er tropisk. Klikk boksen over det klareste, laveste skydekket — ikke den tykke fronten.",
    8: "Tidevann er forutsigbart (astro), fremdeles ganske dyrt, og det påvirker flora og fauna i fjord/estuarium. Ikke «ustabil» og ikke «billig og ferdig utviklet». Velg påstand 2, 3 og 6.",
    10: "Ekvator: netto pluss (mottar mer enn den sender ut). Polene: netto minus. Det er energitransporten mot polene. Velg påstand 1 og 2.",
    13: "Havet tar >90 % av ekstraenergien, men havnivået reagerer tregt: termisk utvidelse og issmelting tar tiår–århundrer. Atmosfæren har lav varmekapasitet og varmes raskere. Velg at havnivået er koblet til tregere prosesser.",
    17: "E ∝ v³. Dobbelt så høy vind (5 → 10 m/s) gir 2³ = 8 ganger så mye energi. Åttedobling.",
    20: "a) Like utenfor LGM-isranden: kjernen kan vise når isen sto der, smeltevann, sjøis og produktivitet (proxyer, planktonmarkører). Si hva hver figurtype faktisk måler. b) Les proxyene mot sjøisklassene i figur 3 — ikke gjett på farger uten skala.",
    21: "a) Katabatisk = kald fallvind; føn = varm, tørr leside etter orografisk heving. Du kjenner temperatur og fukt, ikke bare retning. b) Varmere klima: mer vanndamp, høyere skynivå, ofte mer ekstremnedbør på losiden. c) Mindre arktisk is → svakere temperaturgradient → jet og stormbane kan ligge lenger nord. d) Fønvind + mildvær på lesiden av Jostedalsbreen øker skredfare der snøen blir våt og vinden laster lesider.",
  },
  h2025: {
    1: "Udir-fasit: alternativ b. Figuren viser balanse ved bakken: like mye energi ned mot overflaten som ut fra den (inkludert langbølge fra atmosfæren). Det er ikke «like mye fra sola som fra bakken», og drivhuseffekten er med i figuren.",
    2: "Udir-fasit: alternativ a. For varme Arktis i Holocen-modellen er snø- og isalbedo mekanismen som ikke er godt nok med. Metan, boreal skog og vulkan-aerosoler er ikke det Udir peker på.",
    3: "Udir-fasit: alternativ b — sted 2. Kraftig nedbør hører til fronten / der fuktig luft heves, ikke i høytrykket. Åpne MET-kartet og sjekk hvilket tall som ligger i frontsonen.",
    4: "Udir-fasit: usann — sann — usann — sann. Tyngst overflatevann er ikke i Indiahavet. Middelhavet er tett på grunn av fordamping. Høyest tetthet er ikke kystnært (elveferskvann senker den). Lavest tetthet i tropene stemmer (varmt, ofte ferskere).",
    5: "Udir-fasit: kaldest = år K, våtest = år B. Tynnest ring hvis veksten styres av temperatur, tykkest hvis den styres av nedbør. Les linjalen mot merkene A–K.",
    6: "Udir-fasit: sirkelen i Nordishavet. Coriolis er 2Ω sin φ — null på ekvator, størst ved polene.",
    7: "Udir-fasit: alternativ c. Dyphavsstrømmer drives av tetthetsforskjeller (temperatur og salinitet) — termohalin sirkulasjon. Vind driver overflaten. Coriolis bøyer. Tidevann er lokalt.",
    8: "Udir-fasit: alternativ c. Elvevann har lavere salinitet og er derfor lettere enn kystvann. Det legger seg oppå. Temperatur alene er ikke hovedgrunnen.",
    10: "Udir-fasit: alternativ c — for 1,68 millioner år siden. Det er tidspunktet med høyest eksentrisitet i figuren (større årstidsforskjell, mer sjanse for at sommersnø overlever på 65°N).",
    13: "Udir-fasit: alternativ c. 1920–1940 var kaldere enn 2010–2024. Derfor blir anomalien mot den tidlige perioden større enn mot den sene.",
    17: "Udir-fasit: alternativ a. Metanutslipp fra alpin permafrost er den minste trusselen — arealet er lite. Skred i tinet arktisk permafrost og isskred i alpine fjell rammer folk og infrastruktur hardere.",
    20: "Udir-fasit: alternativ c. Svekket trykkgradient mellom tropene og polene kan gi svakere vind og mindre nordlig varmetransport. Smeltevann øker stratifisering (motsatt av «mindre»). Polar salinitet synker, ikke øker. Varmere overflate blir lettere, ikke tettere.",
    21: "a) Minst fire prosesser: mer absorpsjon og emisjon av langbølge fra drivhusgasser, mer fordamping, lavere albedo, og skyer (mer refleksjon og/eller mer langbølge — usikkerhet er også gyldig). Bruk tallene i Bjerknes-figuren. b) Hurtige endringer med lang virkning: fossilt brensel, endret jordoverflate, fotosyntese via arealendring. Vulkan-aerosoler alene er for kortvarige.",
    22: "Udir-fasit: 1 umulig å avgjøre (A og B er begge kyst). 2 sann (A mister permafrost ved kysten, C er innland). 3 usann (D beholder permafrost i innlandet). 4 usann (sjøis styrer bølge, stormflo og erosjon i A). b) Videreutvikle modellen: metan → drivhus → tilbakekoblinger (albedo, fotosyntese, areal). Figuren får mer blått og mindre grønt.",
    23: "a) Polar østavind (polarcelle) nærmest kysten driver kyststrømmen vestover. Vestavindsbeltet (Ferrel) driver den sirkumpolare strømmen østover. Ekman dreier til venstre på sørlige halvkule. b) Ved ~60°S divergerer Ekmantransporten (nord med vestavind, sør med polar østavind) → oppveling og høy primærproduksjon.",
  },
  eksempel: {
    1: "To Europakart for juli 2025. Polen: les om det er hete, tørke eller flom i kartet, og koble til naturfare (skogbrann, tørke, oversvømmelse). (Ingen Udir-fasit for eksempelsettet.)",
    2: "Hellas: samme kartpar. Hetebølge og tørke peker på skogbrann og vannmangel, ikke snøskred.",
    3: "Temperaturanomali over hav: positiv anomali = marin hetebølge-risiko. Koble lufttemperatur, havtemperatur og værtype.",
    4: "Alpebreer: varm juli-anomali → negativ massebalanse. Les kartet, ikke anta alle breer smelter likt.",
    5: "Plassholder i Udirs eksempel. Hopp over, eller øv på marin hetebølge i Lofoten med egne kart.",
    6: "Skrive: menneskelig pådriv vs naturlig variasjon. Bruk kartene som evidens, ikke som pynt. Henvis til Climate Reanalyzer.",
    7: "Tema 2 åpner AMOC. Skill Golfstrøm (vindgyre) og AMOC (omveltning).",
    8: "Vil AMOC kollapse? Referer argumentene: ferskvann og oppvarming mot vinddrevet Golfstrøm og urealistiske modelldoser. Si hva som er enighet (svekkelse) og uenighet (kollaps).",
    9: "Interaktiv AMOC-figur. Marker der vannet synker (Nord-Atlanteren / Grønlandshavet), ikke i Mexicogolfen alene.",
    10: "Dataoppgave. Les enheter. En modellbane er ikke en observasjon.",
    11: "Skrive: AMOC og modeller. Bruk Udirs vedlegg. Skill scenario, usikkerhet og konsekvens for Norge.",
    12: "Skrive: fortsett på samme spor. Vis kilder.",
    13: "Felt: GPS, profil, usikkerhet, HMS. Skriv hva dataene faktisk viser, ikke hva du ønsket å finne. CTD: les T, S og tetthet sammen — tropisk profil er varm og fersk i toppen, subpolar er kald og gjennomblandet.",
    23: "Plassholder hos Udir: ekstremvær mot havvind. Tenk bølger, ising, stormflo og tilkomst. Ikke et ferdig fasitsvar.",
    24: "Plassholder: værvarsling for havvind. Skill prognosehorisont, usikkerhet og operasjonelle terskler (vind, bølger).",
    25: "Plassholder: bærekraft. Avvei energi, natur, fiskeri og forsyningssikkerhet. Ikke konkluder med ja/nei uten forbehold.",
  },
};

export function solutionFor(slug: string, number: number): string | undefined {
  return SOLUTIONS[slug]?.[number];
}
