import type { Kilde } from "@/lib/kilder";

export const KILDER_G2 = {
  vaerkart: [
    {
      prefix: "National Oceanic and Atmospheric Administration [NOAA]. (u.å.-a). ",
      italic: "Air masses",
      suffix: ".",
      href: "https://www.noaa.gov/jetstream/synoptic/air-masses",
    },
    {
      prefix: "National Oceanic and Atmospheric Administration [NOAA]. (u.å.-b). ",
      italic: "Norwegian cyclone model",
      suffix: ".",
      href: "https://www.noaa.gov/jetstream/synoptic/norwegian-cyclone-model",
    },
    {
      prefix: "National Oceanic and Atmospheric Administration [NOAA]. (u.å.-c). ",
      italic: "How to read surface weather maps",
      suffix: ".",
      href: "https://www.noaa.gov/jetstream/wxmaps",
    },
    {
      prefix: "National Oceanic and Atmospheric Administration [NOAA]. (u.å.-d). ",
      italic: "Constant pressure charts: 500 mb",
      suffix: ".",
      href: "https://www.noaa.gov/jetstream/upper-air-charts/constant-pressure-charts-500-mb",
    },
    {
      prefix: "National Oceanic and Atmospheric Administration [NOAA]. (u.å.-e). ",
      italic: "Z-time (Coordinated Universal Time)",
      suffix: ".",
      href: "https://www.noaa.gov/jetstream/time",
    },
    {
      prefix: "National Oceanic and Atmospheric Administration [NOAA]. (u.å.-f). ",
      italic: "Surface weather plot symbols",
      suffix: ".",
      href: "https://www.noaa.gov/jetstream/wxmaps-max/jetstream-max-surface-weather-plot-symbols",
    },
    {
      prefix: "Sivle, A. (2009, 31. august). ",
      italic: "Værkart og fronter",
      suffix: ". Yr.",
      href: "https://www.yr.no/artikkel/vaerkart-og-fronter-1.6750800",
    },
    {
      prefix: "Store norske leksikon. (u.å.-a). ",
      italic: "Front (meteorologi)",
      suffix: ".",
      href: "https://snl.no/front_-_meteorologi",
    },
    {
      prefix: "Store norske leksikon. (u.å.-b). ",
      italic: "Polarfront",
      suffix: ".",
      href: "https://snl.no/polarfront",
    },
    {
      prefix: "Store norske leksikon. (u.å.-c). ",
      italic: "Isobar",
      suffix: ".",
      href: "https://snl.no/isobar",
    },
    {
      prefix: "Store norske leksikon. (u.å.-d). ",
      italic: "Den norske syklonmodellen",
      suffix: ". Tekst av Marit Kollstuen, Meteorologisk institutt.",
      href: "https://snl.no/Den_norske_syklonmodellen",
    },
    {
      prefix: "Utdanningsdirektoratet [Udir]. (u.å.-a). ",
      italic: "Kjerneelementer",
      suffix: ".",
      href: "https://www.udir.no/lk20/gfg01-03/om-faget/kjerneelementer",
    },
    {
      prefix: "Utdanningsdirektoratet [Udir]. (u.å.-b). ",
      italic: "Kompetansemål etter geofag 2",
      suffix: ".",
      href: "https://www.udir.no/lk20/gfg01-03/kompetansemaal-og-vurdering/kv973",
    },
  ],
  lokale: [
    {
      prefix: "National Oceanic and Atmospheric Administration [NOAA]. (u.å.-a). ",
      italic: "The sea breeze",
      suffix: ". JetStream.",
      href: "https://www.noaa.gov/jetstream/ocean/sea-breeze",
    },
    {
      prefix: "National Oceanic and Atmospheric Administration [NOAA]. (u.å.-b). ",
      italic: "Norwegian cyclone model",
      suffix: ". JetStream.",
      href: "https://www.noaa.gov/jetstream/synoptic/norwegian-cyclone-model",
    },
    {
      prefix: "Sivle, A. (2009, 31. august). ",
      italic: "Værkart og fronter",
      suffix: ". Yr.",
      href: "https://www.yr.no/artikkel/vaerkart-og-fronter-1.6750800",
    },
    {
      prefix: "Store norske leksikon. (u.å.-a). ",
      italic: "Polarfront",
      suffix: ".",
      href: "https://snl.no/polarfront",
    },
    {
      prefix: "Store norske leksikon. (u.å.-b). ",
      italic: "Sjøbris",
      suffix: ".",
      href: "https://snl.no/sj%C3%B8bris",
    },
    {
      prefix: "Store norske leksikon. (u.å.-c). ",
      italic: "Orografisk nedbør",
      suffix: ".",
      href: "https://snl.no/orografisk_nedb%C3%B8r",
    },
    {
      prefix: "Store norske leksikon. (u.å.-d). ",
      italic: "Regnskygge",
      suffix: ".",
      href: "https://snl.no/regnskygge",
    },
    {
      prefix: "Store norske leksikon. (u.å.-e). ",
      italic: "Solgangsvind",
      suffix: ".",
      href: "https://snl.no/solgangsvind",
    },
    {
      prefix: "Store norske leksikon. (u.å.-f). ",
      italic: "Landbris",
      suffix: ".",
      href: "https://snl.no/landbris",
    },
    {
      prefix: "Store norske leksikon. (u.å.-g). ",
      italic: "Føn",
      suffix: ".",
      href: "https://snl.no/f%C3%B8n",
    },
    {
      prefix: "Store norske leksikon. (u.å.-h). ",
      italic: "Berg- og dalvind",
      suffix: ".",
      href: "https://snl.no/berg-_og_dalvind",
    },
    {
      prefix: "Store norske leksikon. (u.å.-i). ",
      italic: "Dalvind",
      suffix: ".",
      href: "https://snl.no/dalvind",
    },
    {
      prefix: "Store norske leksikon. (u.å.-j). ",
      italic: "Bergvind",
      suffix: ".",
      href: "https://snl.no/bergvind",
    },
    {
      prefix: "Store norske leksikon. (u.å.-k). ",
      italic: "Katabatisk vind",
      suffix: ".",
      href: "https://snl.no/katabatisk_vind",
    },
    {
      prefix: "Store norske leksikon. (u.å.-l). ",
      italic: "Anabatisk vind",
      suffix: ".",
      href: "https://snl.no/anabatisk_vind",
    },
    {
      prefix: "Store norske leksikon. (u.å.-m). ",
      italic: "Inversjon (meteorologi)",
      suffix: ".",
      href: "https://snl.no/inversjon_-_meteorologi",
    },
    {
      prefix: "Utdanningsdirektoratet. (u.å.-a). ",
      italic: "Kjerneelementer",
      suffix: ". Læreplan i geofag (GFG01-03).",
      href: "https://www.udir.no/lk20/gfg01-03/om-faget/kjerneelementer",
    },
    {
      prefix: "Utdanningsdirektoratet. (u.å.-b). ",
      italic: "Kompetansemål etter geofag 2",
      suffix: ". Læreplan i geofag (GFG01-03).",
      href: "https://www.udir.no/lk20/gfg01-03/kompetansemaal-og-vurdering/kv973",
    },
  ],
  kryosfare: [
    {
      prefix: "National Snow and Ice Data Center [NSIDC]. (u.å.). ",
      italic: "All about sea ice",
      suffix: ".",
      href: "https://nsidc.org/learn/parts-cryosphere/sea-ice",
    },
    {
      prefix: "Norges vassdrags- og energidirektorat [NVE]. (u.å.-a). ",
      italic: "Bre",
      suffix: ".",
      href: "https://www.nve.no/vann-og-vassdrag/vannets-kretsloep/bre/",
    },
    {
      prefix: "Norges vassdrags- og energidirektorat [NVE]. (u.å.-b). ",
      italic: "Snøskredvarsling",
      suffix: ".",
      href: "https://www.varsom.no/snoskred",
    },
    {
      prefix: "Store norske leksikon. (u.å.). ",
      italic: "Permafrost",
      suffix: ".",
      href: "https://snl.no/permafrost",
    },
    {
      prefix: "Intergovernmental Panel on Climate Change [IPCC]. (2021). ",
      italic:
        "Climate change 2021: The physical science basis. Contribution of Working Group I to the Sixth Assessment Report",
      suffix: ".",
      href: "https://www.ipcc.ch/report/ar6/wg1/",
    },
  ],
  energi: [
    {
      prefix: "Norges vassdrags- og energidirektorat [NVE]. (u.å.-a). ",
      italic: "Havvind",
      suffix: ".",
      href: "https://www.nve.no/energi/energisystem/havvind/",
    },
    {
      prefix: "Norges vassdrags- og energidirektorat [NVE]. (u.å.-b). ",
      italic: "Vindkraft",
      suffix: ".",
      href: "https://www.nve.no/energi/energisystem/vindkraft/",
    },
    {
      prefix: "Store norske leksikon. (u.å.). ",
      italic: "Tidevann",
      suffix: ".",
      href: "https://snl.no/tidevann",
    },
    {
      prefix: "Utdanningsdirektoratet. (2020). ",
      italic: "Læreplan i geofag (GFG01-03)",
      suffix: ".",
      href: "https://www.udir.no/lk20/gfg01-03",
    },
  ],
  feltG2: [
    {
      prefix: "Meteorologisk institutt [MET Norway]. (u.å.). ",
      italic: "Yr — værvarsel og observasjoner",
      suffix: ".",
      href: "https://www.yr.no",
    },
    {
      prefix: "Utdanningsdirektoratet. (2020). ",
      italic: "Læreplan i geofag (GFG01-03)",
      suffix: ".",
      href: "https://www.udir.no/lk20/gfg01-03",
    },
    {
      prefix: "Norges vassdrags- og energidirektorat [NVE]. (u.å.). ",
      italic: "Snøskredvarsling",
      suffix: ".",
      href: "https://www.varsom.no/snoskred",
    },
  ],
  tilpasning: [
    {
      prefix: "Norsk klimaservicesenter [NCCS]. (u.å.). ",
      italic: "Klima i Norge og fylkesvise klimaprofiler",
      suffix: ".",
      href: "https://klimaservicesenter.no/",
    },
    {
      prefix: "Intergovernmental Panel on Climate Change [IPCC]. (2022). ",
      italic:
        "Climate change 2022: Impacts, adaptation and vulnerability. Contribution of Working Group II to the Sixth Assessment Report",
      suffix: ".",
      href: "https://www.ipcc.ch/report/ar6/wg2/",
    },
    {
      prefix: "Store norske leksikon. (u.å.). ",
      italic: "Klima i Norge",
      suffix: ".",
      href: "https://snl.no/Klima_i_Norge",
    },
    {
      prefix: "Utdanningsdirektoratet. (2020). ",
      italic: "Læreplan i geofag (GFG01-03)",
      suffix: ".",
      href: "https://www.udir.no/lk20/gfg01-03",
    },
  ],
} as const satisfies Record<string, readonly Kilde[]>;
