#!/usr/bin/env python3
"""Download open datasets and write the TypeScript data for the v2026 exam figures.

Sources (all fetched at runtime, nothing is traced from Udir):
- ETOPO 2022, 60 arc-second, NOAA NCEI via ERDDAP
- NOAA OISST v2.1 daily, CoastWatch ERDDAP
- NCEP/NCAR reanalysis daily precipitable water and sea-level pressure, PSL
- NHC best track / tropical cyclone report for Hurricane Gabrielle (AL072025)
- NVE glacier mass balance (glacier.nve.no)
- EPICA Dome C temperature (Jouzel et al. 2007, NOAA Paleoclimatology)
- Spratt & Lisiecki 2016 sea-level stack (NOAA Paleoclimatology)
"""

from __future__ import annotations

import gzip
import json
import math
import re
import urllib.request
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

OUT = Path("/workspace/src/lib/eksamen/figures/v2026")
RAW = Path("/tmp/geo-data")
RAW.mkdir(parents=True, exist_ok=True)
OUT.mkdir(parents=True, exist_ok=True)

UA = {"User-Agent": "geofag-exam-figures/1.0 (educational; open-data redraw)"}


def get(url: str, dest: Path | None = None, timeout: int = 180) -> bytes:
    req = urllib.request.Request(url, headers=UA)
    with urllib.request.urlopen(req, timeout=timeout) as res:
        data = res.read()
    if dest is not None:
        dest.write_bytes(data)
    return data


def ts_string(name: str, payload: object) -> str:
    body = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    return (
        "// Generated by scripts/build-v2026-figure-data.py. Do not edit by hand.\n"
        f"export const {name} = {body} as const;\n"
    )


def write_ts(filename: str, name: str, payload: object) -> None:
    path = OUT / filename
    path.write_text(ts_string(name, payload), encoding="utf-8")
    print(f"wrote {path} ({path.stat().st_size} bytes)")


# ---------------------------------------------------------------------------
# ETOPO 2022
# ---------------------------------------------------------------------------

def fetch_etopo_slab(lat0: float, lat1: float, lon0: float, lon1: float, stride: int) -> list[tuple[float, float, float]]:
    # This ERDDAP grid stores longitude from 0 to 360.
    lon0 = lon0 % 360
    lon1 = lon1 % 360
    url = (
        "https://oceanwatch.pifsc.noaa.gov/erddap/griddap/ETOPO_2022_v1_60s.csv?"
        f"z[({lat0}):{stride}:({lat1})][({lon0}):{stride}:({lon1})]"
    )
    print("ETOPO", url)
    text = get(url).decode("utf-8", "replace")
    rows = []
    for line in text.splitlines()[2:]:
        parts = line.split(",")
        if len(parts) < 3:
            continue
        lat, lon, z = float(parts[0]), float(parts[1]), float(parts[2])
        if lon > 180:
            lon -= 360
        rows.append((lat, lon, z))
    return rows


def fetch_etopo(lat0: float, lat1: float, lon0: float, lon1: float, stride: int) -> dict:
    # Split slabs that cross the Greenwich meridian on a 0–360 axis.
    step = stride / 60.0
    if lon0 < 0 < lon1:
        rows = fetch_etopo_slab(lat0, lat1, lon0 % 360, 360 - step, stride)
        rows += fetch_etopo_slab(lat0, lat1, 0, lon1, stride)
    elif lon0 < 0:
        rows = fetch_etopo_slab(lat0, lat1, lon0 % 360, lon1 % 360, stride)
    else:
        rows = fetch_etopo_slab(lat0, lat1, lon0, lon1, stride)
    lats = sorted({round(r[0], 5) for r in rows}, reverse=True)
    lons = sorted({round(r[1], 5) for r in rows})
    lat_i = {v: i for i, v in enumerate(lats)}
    lon_i = {v: i for i, v in enumerate(lons)}
    grid = [0] * (len(lats) * len(lons))
    for lat, lon, z in rows:
        grid[lat_i[round(lat, 5)] * len(lons) + lon_i[round(lon, 5)]] = int(round(z))
    return {
        "lat0": lats[0],
        "lat1": lats[-1],
        "lon0": lons[0],
        "lon1": lons[-1],
        "ny": len(lats),
        "nx": len(lons),
        "z": grid,
        "source": "NOAA NCEI ETOPO 2022 v1, 60 arc-second ice surface",
    }


# ---------------------------------------------------------------------------
# Mediterranean OISST
# ---------------------------------------------------------------------------

MED = [
    (-5.61, 35.88), (-5.30, 36.18), (-2.10, 36.45), (-0.20, 38.60),
    (-0.40, 43.00), (1.40, 43.35), (3.40, 43.30), (5.60, 43.25),
    (8.20, 44.15), (10.30, 43.90), (12.50, 45.45), (13.75, 45.70),
    (12.90, 43.80), (15.80, 42.20), (18.40, 40.30), (19.60, 41.90),
    (23.20, 40.80), (26.15, 40.55), (26.40, 39.20), (28.40, 36.80),
    (32.40, 36.20), (36.20, 36.15), (35.40, 33.40), (34.20, 31.40),
    (32.20, 31.15), (24.00, 31.80), (18.00, 32.40), (10.20, 33.00),
    (9.70, 37.10), (4.50, 36.80), (0.50, 36.20), (-2.20, 35.30),
    (-5.40, 35.45), (-5.61, 35.88),
]


def inside(lon: float, lat: float, poly: list[tuple[float, float]]) -> bool:
    n = len(poly)
    hit = False
    j = n - 1
    for i in range(n):
        xi, yi = poly[i]
        xj, yj = poly[j]
        if ((yi > lat) != (yj > lat)) and (lon < (xj - xi) * (lat - yi) / (yj - yi + 1e-15) + xi):
            hit = not hit
        j = i
    return hit


def oisst_year(year: int) -> Path:
    dest = RAW / "oisst" / f"{year}.csv"
    if dest.exists() and dest.stat().st_size > 1000:
        return dest
    dest.parent.mkdir(parents=True, exist_ok=True)
    url = (
        "https://coastwatch.pfeg.noaa.gov/erddap/griddap/ncdcOisst21Agg_LonPM180.csv?"
        f"sst[({year}-06-01T12:00:00Z):1:({year}-10-31T12:00:00Z)][(0.0)]"
        "[(30.125):4:(45.125)][(-5.875):4:(36.125)]"
    )
    print("OISST", year)
    get(url, dest, timeout=180)
    return dest


def oisst_aug13(year: int) -> list[tuple[float, float, float]]:
    dest = RAW / "oisst" / f"aug13-{year}.csv"
    if not dest.exists() or dest.stat().st_size < 100:
        url = (
            "https://coastwatch.pfeg.noaa.gov/erddap/griddap/ncdcOisst21Agg_LonPM180.csv?"
            f"sst[({year}-08-13T12:00:00Z)][(0.0)]"
            "[(30.125):2:(45.125)][(-5.875):2:(36.125)]"
        )
        print("OISST aug13", year)
        get(url, dest, timeout=120)
    pts = []
    for line in dest.read_text(encoding="utf-8", errors="replace").splitlines()[2:]:
        parts = line.split(",")
        if len(parts) < 5:
            continue
        lat, lon, sst = float(parts[2]), float(parts[3]), parts[4]
        if sst == "NaN":
            continue
        pts.append((lon, lat, float(sst)))
    return pts


def basin_series(path: Path) -> list[float | None]:
    """Daily Mediterranean mean, 1 Jun–31 Oct, area-weighted, NaN if empty."""
    buckets: dict[str, list[tuple[float, float]]] = {}
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines()[2:]:
        parts = line.split(",")
        if len(parts) < 5 or parts[4] == "NaN":
            continue
        day, lat, lon, sst = parts[0][:10], float(parts[2]), float(parts[3]), float(parts[4])
        if not inside(lon, lat, MED):
            continue
        buckets.setdefault(day, []).append((lat, sst))
    days = sorted(buckets)
    out: list[float | None] = []
    for day in days:
        acc = 0.0
        wsum = 0.0
        for lat, sst in buckets[day]:
            w = math.cos(math.radians(lat))
            acc += sst * w
            wsum += w
        out.append(round(acc / wsum, 3) if wsum else None)
    return out


def build_oisst() -> None:
    years = list(range(1982, 2025))
    with ThreadPoolExecutor(max_workers=6) as pool:
        futures = [pool.submit(oisst_year, y) for y in years]
        for fut in as_completed(futures):
            fut.result()
    series = {str(y): basin_series(RAW / "oisst" / f"{y}.csv") for y in years}
    # climatology 1991–2020 on the common June–October length
    n = min(len(series[str(y)]) for y in range(1991, 2021))
    clim = []
    for i in range(n):
        vals = [series[str(y)][i] for y in range(1991, 2021) if series[str(y)][i] is not None]
        clim.append(round(sum(vals) / len(vals), 3) if vals else None)
    # anomaly map, 13 August, 0.5°
    aug_years = list(range(1991, 2021)) + [2024]
    with ThreadPoolExecutor(max_workers=6) as pool:
        aug = {y: pool.submit(oisst_aug13, y) for y in aug_years}
        aug = {y: fut.result() for y, fut in aug.items()}
    # align on rounded lon/lat
    def key(lon: float, lat: float) -> tuple[float, float]:
        return (round(lon, 3), round(lat, 3))

    clim_acc: dict[tuple[float, float], list[float]] = {}
    for y in range(1991, 2021):
        for lon, lat, sst in aug[y]:
            if inside(lon, lat, MED):
                clim_acc.setdefault(key(lon, lat), []).append(sst)
    anom = []
    for lon, lat, sst in aug[2024]:
        if not inside(lon, lat, MED):
            continue
        base = clim_acc.get(key(lon, lat))
        if not base:
            continue
        anom.append([round(lon, 3), round(lat, 3), round(sst - sum(base) / len(base), 2)])
    peak = max((v for v in series["2024"] if v is not None), default=None)
    peak_i = series["2024"].index(peak) if peak is not None else None
    write_ts(
        "oisst.ts",
        "medSst",
        {
            "years": years,
            "series": series,
            "climatology1991to2020": clim,
            "anomaly20240813": anom,
            "peak2024": peak,
            "peakIndexFromJune1": peak_i,
            "note": "Basin mean of NOAA OISST v2.1 over a Mediterranean polygon, 1° grid, cosine-weighted. Anomaly is 13 August 2024 minus the 13 August mean 1991–2020 on a 0.5° grid.",
        },
    )


# ---------------------------------------------------------------------------
# Gyda: precipitable water and SLP, 12 January 2022
# ---------------------------------------------------------------------------

def parse_grid_ascii(text: str, var: str) -> tuple[list[float], list[float], list[list[float]]]:
    lats = [float(v) for v in re.search(r"lat\[\d+\]\n([0-9., \-]+)", text).group(1).split(",")]
    lons = [float(v) for v in re.search(r"lon\[\d+\]\n([0-9., \-]+)", text).group(1).split(",")]
    block = re.search(rf"{var}\.{var}\[\d+\]\[\d+\]\[\d+\]\n(.*?)(?:\n\n|\n{var}\.)", text, re.S)
    rows = []
    for line in block.group(1).strip().splitlines():
        nums = [float(v) for v in line.split(",")[1:]]
        rows.append(nums)
    return lats, lons, rows


def build_gyda() -> None:
    # North Atlantic–Europe window. Lat index: 90 - 2.5*i. Lon index: 2.5*j, 0..357.5.
    # lat 75N..40N -> index (90-75)/2.5=6 through (90-40)/2.5=20
    # lon 40W..50E -> 320E..50E, indices 128..20 wrapping. Fetch full lon, crop later.
    url_pw = (
        "https://psl.noaa.gov/thredds/dodsC/Datasets/ncep.reanalysis.dailyavgs/"
        "surface/pr_wtr.eatm.2022.nc.ascii?lat[6:1:22],lon[0:1:143],pr_wtr[11:1:11][6:1:22][0:1:143]"
    )
    url_slp = (
        "https://psl.noaa.gov/thredds/dodsC/Datasets/ncep.reanalysis.dailyavgs/"
        "surface/slp.2022.nc.ascii?lat[6:1:22],lon[0:1:143],slp[11:1:11][6:1:22][0:1:143]"
    )
    print("NCEP pr_wtr")
    pw_lats, pw_lons, pw = parse_grid_ascii(get(url_pw).decode(), "pr_wtr")
    print("NCEP slp")
    slp_lats, slp_lons, slp = parse_grid_ascii(get(url_slp).decode(), "slp")
    # SLP from NCEP is Pascals.
    slp_hpa = [[round(v / 100.0, 1) for v in row] for row in slp]
    pw_r = [[round(v, 2) for v in row] for row in pw]
    write_ts(
        "gyda.ts",
        "gyda",
        {
            "date": "2022-01-12",
            "lat": pw_lats,
            "lon": pw_lons,
            "precipitableWaterMm": pw_r,
            "slpHpa": slp_hpa,
        },
    )


# ---------------------------------------------------------------------------
# NVE mass balance
# ---------------------------------------------------------------------------

def parse_nve(html: str) -> list[dict]:
    cells = re.findall(r"<td[^>]*>\s*(?:&nbsp;)?([0-9.\-]+)\s*</td>", html)
    rows = []
    for i in range(0, len(cells) - 3, 4):
        year = int(float(cells[i]))
        if year < 1900 or year > 2100:
            continue
        rows.append(
            {
                "year": year,
                "winter": float(cells[i + 1]),
                "summer": float(cells[i + 2]),
                "annual": float(cells[i + 3]),
            }
        )
    # The page repeats the table; keep the first contiguous run.
    dedup = []
    seen = set()
    for row in rows:
        if row["year"] in seen:
            break
        seen.add(row["year"])
        dedup.append(row)
    return dedup


def build_nve() -> None:
    alfot = (RAW / "nve-alfot.html").read_text(encoding="utf-8", errors="replace")
    hell = (RAW / "nve-hell.html").read_text(encoding="utf-8", errors="replace")
    if "Winter balance" not in alfot:
        alfot = get(
            "https://glacier.nve.no/Glacier/viewer/CI/en/nve/ClimateIndicatorInfo/2078?name=%C3%85lfotbreen"
        ).decode("utf-8", "replace")
    if "Winter balance" not in hell:
        hell = get(
            "https://glacier.nve.no/Glacier/viewer/CI/en/nve/ClimateIndicatorInfo/2768?name=Hellstugubreen"
        ).decode("utf-8", "replace")
    a = parse_nve(alfot)
    h = parse_nve(hell)
    print("NVE Ålfot", len(a), a[0]["year"], a[-1]["year"])
    print("NVE Hellstugu", len(h), h[0]["year"], h[-1]["year"])
    write_ts("nve.ts", "nveBalance", {"alfotbreen": a, "hellstugubreen": h})


# ---------------------------------------------------------------------------
# Gabrielle best track
# ---------------------------------------------------------------------------

def build_gabrielle() -> None:
    points = []
    try:
        raw = get("https://ftp.nhc.noaa.gov/atcf/archive/2025/bal072025.dat.gz", timeout=60)
        text = gzip.decompress(raw).decode("utf-8", "replace")
        for line in text.splitlines():
            cols = [c.strip() for c in line.split(",")]
            if len(cols) < 11 or cols[4] != "BEST":
                continue
            # Only the synoptic hours already in the final best track (forecast hour 0).
            if cols[5] not in {"0", "00"}:
                continue
            lat_s, lon_s = cols[6], cols[7]
            lat = int(lat_s[:-1]) / 10
            lon = int(lon_s[:-1]) / 10
            if lat_s.endswith("S"):
                lat = -lat
            if lon_s.endswith("W"):
                lon = -lon
            wind = int(cols[8])
            pressure = int(cols[9]) if cols[9] not in {"", "-999"} else None
            points.append(
                {
                    "time": cols[2],
                    "lat": lat,
                    "lon": lon,
                    "windKt": wind,
                    "pressureHpa": pressure,
                }
            )
        print("b-deck points", len(points))
    except Exception as exc:  # noqa: BLE001
        print("b-deck failed", exc)
    if len(points) < 10:
        # Official Table 1 in the NHC tropical cyclone report AL072025 (Blake, 2025).
        table = """
        17/1800 19.0 47.7 1005 45
        18/0000 19.3 48.9 1004 45
        18/0600 19.6 50.0 1004 45
        18/1200 20.0 51.2 1004 45
        18/1800 20.5 52.2 1004 45
        19/0000 21.0 53.1 1004 45
        19/0600 21.4 54.1 1004 45
        19/1200 21.7 55.1 1004 45
        19/1800 22.1 56.1 1004 45
        20/0000 22.9 57.0 1004 45
        20/0600 23.9 57.7 1004 45
        20/1200 24.6 58.3 1001 50
        20/1800 25.2 58.6 996 55
        21/0000 25.9 59.0 996 55
        21/0600 26.6 59.8 995 55
        21/1200 27.3 60.7 995 60
        21/1800 28.1 61.5 993 65
        22/0000 28.9 62.1 985 70
        22/0600 29.6 62.5 977 80
        22/1200 30.4 62.5 958 100
        22/1800 31.3 62.1 951 115
        23/0000 32.1 61.4 944 120
        23/0600 32.8 60.4 945 120
        23/1200 33.5 59.2 946 120
        23/1800 34.3 57.4 947 115
        24/0000 34.9 55.2 953 110
        24/0600 35.4 52.8 958 100
        24/1200 35.8 50.2 965 90
        24/1800 35.9 47.2 970 85
        25/0000 35.9 44.0 974 75
        25/0600 36.1 40.2 976 70
        25/1200 36.4 36.7 979 65
        25/1800 36.8 33.6 982 60
        26/0000 37.6 30.6 983 55
        26/0600 38.6 27.5 984 55
        26/1200 39.6 24.2 986 55
        26/1800 40.4 21.4 985 60
        27/0000 41.0 18.5 984 65
        27/0600 41.4 15.7 988 60
        27/1200 41.8 13.1 992 50
        27/1800 41.4 11.2 993 50
        28/0000 41.0 9.5 994 45
        28/0600 40.4 8.1 1005 40
        28/1200 39.5 7.4 1010 35
        28/1800 38.5 6.5 1012 25
        """
        points = []
        for line in table.strip().splitlines():
            day, lat, lon, pres, wind = line.split()
            dd, hh = day.split("/")
            points.append(
                {
                    "time": f"202509{int(dd):02d}{hh}",
                    "lat": float(lat),
                    "lon": -float(lon),
                    "windKt": int(wind),
                    "pressureHpa": int(pres),
                }
            )
    # Drop duplicate times (b-decks repeat radii lines).
    uniq = []
    seen = set()
    for p in points:
        if p["time"] in seen:
            continue
        seen.add(p["time"])
        uniq.append(p)
    uniq.sort(key=lambda p: p["time"])
    write_ts("gabrielle.ts", "gabrielleTrack", uniq)
    print("gabrielle", len(uniq), "max wind", max(p["windKt"] for p in uniq))


# ---------------------------------------------------------------------------
# Paleo: EPICA temperature and Spratt sea level
# ---------------------------------------------------------------------------

def build_paleo() -> None:
    epica_path = RAW / "edc.txt"
    if not epica_path.exists():
        get(
            "https://www.ncei.noaa.gov/pub/data/paleo/icecore/antarctica/epica_domec/edc3deuttemp2007.txt",
            epica_path,
        )
    epica = []
    for line in epica_path.read_text(encoding="utf-8", errors="replace").splitlines():
        parts = line.split()
        if len(parts) < 5:
            continue
        try:
            age_yr = float(parts[2])
            temp = float(parts[4])
        except ValueError:
            continue
        if age_yr < 0:
            continue
        epica.append((age_yr / 1000.0, temp))
    # Keep about one point per 0.5 ka so the file stays small.
    slim = []
    last = -999.0
    for age, temp in epica:
        if age >= last + 0.5 or age > 800:
            slim.append([round(age, 2), round(temp, 2)])
            last = age
    spratt_path = RAW / "spratt2016.txt"
    if not spratt_path.exists():
        get(
            "https://www.ncei.noaa.gov/pub/data/paleo/contributions_by_author/spratt2016/spratt2016.txt",
            spratt_path,
        )
    text = spratt_path.read_text(encoding="utf-8", errors="replace")
    print("--- spratt head ---")
    print("\n".join(text.splitlines()[:40]))
    sea = []
    for line in text.splitlines():
        parts = line.split()
        if len(parts) < 2:
            continue
        try:
            nums = [float(p) for p in parts[:4]]
        except ValueError:
            continue
        # Common layout: age_ka, sea_level_m, ...
        age, level = nums[0], nums[1]
        if 0 <= age <= 800 and -200 < level < 50:
            sea.append([round(age, 2), round(level, 2)])
    if len(sea) < 50:
        # Try other column orders later by printing a sample of numeric lines.
        print("sea-level parse short", len(sea))
        numeric = []
        for line in text.splitlines():
            parts = line.split()
            try:
                numeric.append([float(p) for p in parts])
            except ValueError:
                continue
            if len(numeric) > 8:
                break
        print("sample", numeric[:8])
    # subsample ~1 ka
    sea_slim = []
    last = -999.0
    for age, level in sea:
        if age >= last + 1:
            sea_slim.append([age, level])
            last = age
    write_ts(
        "paleo.ts",
        "paleo",
        {"epicaTempC": slim, "sprattSeaLevelM": sea_slim},
    )
    if sea_slim:
        window = [lv for age, lv in sea_slim if 450 <= age <= 750]
        print("sea level 750–450 ka min/max", min(window), max(window), "n", len(window))
        print("sea level near 0", [lv for age, lv in sea_slim if age < 2])


def main() -> None:
    # Published figures use the Nordic ETOPO grid and the Gyda reanalysis only.
    # NVE, Gabrielle, the Mediterranean heatwave and the ice-core panels are
    # licensed originals, not plots from this script.
    nordic = fetch_etopo(50, 82, -40, 40, 15)
    write_ts("nordic-grid.ts", "nordicGrid", nordic)
    build_gyda()
    print("done")


if __name__ == "__main__":
    main()
