/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Geofag2RouteImport } from './routes/geofag-2'
import { Route as Geofag1IndexRouteImport } from './routes/geofag-1/index'
import { Route as Geofag1SlugRouteImport } from './routes/geofag-1/$slug'
import { Route as TemaCoriolisRouteImport } from './routes/tema/coriolis'
import { Route as TemaHavstrommerRouteImport } from './routes/tema/havstrommer'
import { Route as TemaHoytrykkLavtrykkRouteImport } from './routes/tema/hoytrykk-lavtrykk'
import { Route as TemaKlimaRouteImport } from './routes/tema/klima'
import { Route as TemaVaerkatastroferRouteImport } from './routes/tema/vaerkatastrofer'
import { Route as TemaVindsystemetRouteImport } from './routes/tema/vindsystemet'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Geofag2Route = Geofag2RouteImport.update({
  id: '/geofag-2',
  path: '/geofag-2',
  getParentRoute: () => rootRouteImport,
} as any)
const Geofag1IndexRoute = Geofag1IndexRouteImport.update({
  id: '/geofag-1/',
  path: '/geofag-1/',
  getParentRoute: () => rootRouteImport,
} as any)
const Geofag1SlugRoute = Geofag1SlugRouteImport.update({
  id: '/geofag-1/$slug',
  path: '/geofag-1/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TemaCoriolisRoute = TemaCoriolisRouteImport.update({
  id: '/tema/coriolis',
  path: '/tema/coriolis',
  getParentRoute: () => rootRouteImport,
} as any)
const TemaHavstrommerRoute = TemaHavstrommerRouteImport.update({
  id: '/tema/havstrommer',
  path: '/tema/havstrommer',
  getParentRoute: () => rootRouteImport,
} as any)
const TemaHoytrykkLavtrykkRoute = TemaHoytrykkLavtrykkRouteImport.update({
  id: '/tema/hoytrykk-lavtrykk',
  path: '/tema/hoytrykk-lavtrykk',
  getParentRoute: () => rootRouteImport,
} as any)
const TemaKlimaRoute = TemaKlimaRouteImport.update({
  id: '/tema/klima',
  path: '/tema/klima',
  getParentRoute: () => rootRouteImport,
} as any)
const TemaVaerkatastroferRoute = TemaVaerkatastroferRouteImport.update({
  id: '/tema/vaerkatastrofer',
  path: '/tema/vaerkatastrofer',
  getParentRoute: () => rootRouteImport,
} as any)
const TemaVindsystemetRoute = TemaVindsystemetRouteImport.update({
  id: '/tema/vindsystemet',
  path: '/tema/vindsystemet',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/geofag-2': typeof Geofag2Route
  '/geofag-1/$slug': typeof Geofag1SlugRoute
  '/tema/coriolis': typeof TemaCoriolisRoute
  '/tema/havstrommer': typeof TemaHavstrommerRoute
  '/tema/hoytrykk-lavtrykk': typeof TemaHoytrykkLavtrykkRoute
  '/tema/klima': typeof TemaKlimaRoute
  '/tema/vaerkatastrofer': typeof TemaVaerkatastroferRoute
  '/tema/vindsystemet': typeof TemaVindsystemetRoute
  '/geofag-1/': typeof Geofag1IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/geofag-2': typeof Geofag2Route
  '/geofag-1/$slug': typeof Geofag1SlugRoute
  '/tema/coriolis': typeof TemaCoriolisRoute
  '/tema/havstrommer': typeof TemaHavstrommerRoute
  '/tema/hoytrykk-lavtrykk': typeof TemaHoytrykkLavtrykkRoute
  '/tema/klima': typeof TemaKlimaRoute
  '/tema/vaerkatastrofer': typeof TemaVaerkatastroferRoute
  '/tema/vindsystemet': typeof TemaVindsystemetRoute
  '/geofag-1': typeof Geofag1IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/geofag-2': typeof Geofag2Route
  '/geofag-1/$slug': typeof Geofag1SlugRoute
  '/tema/coriolis': typeof TemaCoriolisRoute
  '/tema/havstrommer': typeof TemaHavstrommerRoute
  '/tema/hoytrykk-lavtrykk': typeof TemaHoytrykkLavtrykkRoute
  '/tema/klima': typeof TemaKlimaRoute
  '/tema/vaerkatastrofer': typeof TemaVaerkatastroferRoute
  '/tema/vindsystemet': typeof TemaVindsystemetRoute
  '/geofag-1/': typeof Geofag1IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/geofag-2'
    | '/geofag-1/$slug'
    | '/tema/coriolis'
    | '/tema/havstrommer'
    | '/tema/hoytrykk-lavtrykk'
    | '/tema/klima'
    | '/tema/vaerkatastrofer'
    | '/tema/vindsystemet'
    | '/geofag-1/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/geofag-2'
    | '/geofag-1/$slug'
    | '/tema/coriolis'
    | '/tema/havstrommer'
    | '/tema/hoytrykk-lavtrykk'
    | '/tema/klima'
    | '/tema/vaerkatastrofer'
    | '/tema/vindsystemet'
    | '/geofag-1'
  id:
    | '__root__'
    | '/'
    | '/geofag-2'
    | '/geofag-1/$slug'
    | '/tema/coriolis'
    | '/tema/havstrommer'
    | '/tema/hoytrykk-lavtrykk'
    | '/tema/klima'
    | '/tema/vaerkatastrofer'
    | '/tema/vindsystemet'
    | '/geofag-1/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Geofag2Route: typeof Geofag2Route
  Geofag1SlugRoute: typeof Geofag1SlugRoute
  TemaCoriolisRoute: typeof TemaCoriolisRoute
  TemaHavstrommerRoute: typeof TemaHavstrommerRoute
  TemaHoytrykkLavtrykkRoute: typeof TemaHoytrykkLavtrykkRoute
  TemaKlimaRoute: typeof TemaKlimaRoute
  TemaVaerkatastroferRoute: typeof TemaVaerkatastroferRoute
  TemaVindsystemetRoute: typeof TemaVindsystemetRoute
  Geofag1IndexRoute: typeof Geofag1IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geofag-2': {
      id: '/geofag-2'
      path: '/geofag-2'
      fullPath: '/geofag-2'
      preLoaderRoute: typeof Geofag2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geofag-1/': {
      id: '/geofag-1/'
      path: '/geofag-1'
      fullPath: '/geofag-1/'
      preLoaderRoute: typeof Geofag1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geofag-1/$slug': {
      id: '/geofag-1/$slug'
      path: '/geofag-1/$slug'
      fullPath: '/geofag-1/$slug'
      preLoaderRoute: typeof Geofag1SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tema/coriolis': {
      id: '/tema/coriolis'
      path: '/tema/coriolis'
      fullPath: '/tema/coriolis'
      preLoaderRoute: typeof TemaCoriolisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tema/havstrommer': {
      id: '/tema/havstrommer'
      path: '/tema/havstrommer'
      fullPath: '/tema/havstrommer'
      preLoaderRoute: typeof TemaHavstrommerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tema/hoytrykk-lavtrykk': {
      id: '/tema/hoytrykk-lavtrykk'
      path: '/tema/hoytrykk-lavtrykk'
      fullPath: '/tema/hoytrykk-lavtrykk'
      preLoaderRoute: typeof TemaHoytrykkLavtrykkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tema/klima': {
      id: '/tema/klima'
      path: '/tema/klima'
      fullPath: '/tema/klima'
      preLoaderRoute: typeof TemaKlimaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tema/vaerkatastrofer': {
      id: '/tema/vaerkatastrofer'
      path: '/tema/vaerkatastrofer'
      fullPath: '/tema/vaerkatastrofer'
      preLoaderRoute: typeof TemaVaerkatastroferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tema/vindsystemet': {
      id: '/tema/vindsystemet'
      path: '/tema/vindsystemet'
      fullPath: '/tema/vindsystemet'
      preLoaderRoute: typeof TemaVindsystemetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Geofag2Route: Geofag2Route,
  Geofag1SlugRoute: Geofag1SlugRoute,
  TemaCoriolisRoute: TemaCoriolisRoute,
  TemaHavstrommerRoute: TemaHavstrommerRoute,
  TemaHoytrykkLavtrykkRoute: TemaHoytrykkLavtrykkRoute,
  TemaKlimaRoute: TemaKlimaRoute,
  TemaVaerkatastroferRoute: TemaVaerkatastroferRoute,
  TemaVindsystemetRoute: TemaVindsystemetRoute,
  Geofag1IndexRoute: Geofag1IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
