/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Geofag2RouteImport } from './routes/geofag-2'
import { Route as EksamenIndexRouteImport } from './routes/eksamen/index'
import { Route as EksamenSlugRouteImport } from './routes/eksamen/$slug'
import { Route as Geofag1IndexRouteImport } from './routes/geofag-1/index'
import { Route as Geofag1SlugRouteImport } from './routes/geofag-1/$slug'
import { Route as Geofag1BergarterOgLandformerRouteImport } from './routes/geofag-1/bergarter-og-landformer'
import { Route as Geofag1FeltarbeidRouteImport } from './routes/geofag-1/feltarbeid'
import { Route as Geofag1GeologiskeRessurserRouteImport } from './routes/geofag-1/geologiske-ressurser'
import { Route as Geofag1JordsystemeneRouteImport } from './routes/geofag-1/jordsystemene'
import { Route as Geofag1PlatetektonikkRouteImport } from './routes/geofag-1/platetektonikk'
import { Route as Geofag1RessurserOgFeltRouteImport } from './routes/geofag-1/ressurser-og-felt'
import { Route as Geofag1SkredRouteImport } from './routes/geofag-1/skred'
import { Route as Geofag1VannFlomOgSkredRouteImport } from './routes/geofag-1/vann-flom-og-skred'
import { Route as Geofag1VannOgFlomRouteImport } from './routes/geofag-1/vann-og-flom'
import { Route as Geofag1VulkanerOgJordskjelvRouteImport } from './routes/geofag-1/vulkaner-og-jordskjelv'
import { Route as TemaCoriolisRouteImport } from './routes/tema/coriolis'
import { Route as TemaEnergiHavLuftRouteImport } from './routes/tema/energi-hav-luft'
import { Route as TemaFeltHavLuftIsRouteImport } from './routes/tema/felt-hav-luft-is'
import { Route as TemaHavstrommerRouteImport } from './routes/tema/havstrommer'
import { Route as TemaHoytrykkLavtrykkRouteImport } from './routes/tema/hoytrykk-lavtrykk'
import { Route as TemaJetstrommerRouteImport } from './routes/tema/jetstrommer'
import { Route as TemaKryosfareRouteImport } from './routes/tema/kryosfare'
import { Route as TemaLokaleVaersystemerRouteImport } from './routes/tema/lokale-vaersystemer'
import { Route as TemaMilankovitchRouteImport } from './routes/tema/milankovitch'
import { Route as TemaNumeriskeModellerRouteImport } from './routes/tema/numeriske-modeller'
import { Route as TemaPaleoklimaRouteImport } from './routes/tema/paleoklima'
import { Route as TemaTilpasningRouteImport } from './routes/tema/tilpasning'
import { Route as TemaVaerkartRouteImport } from './routes/tema/vaerkart'
import { Route as TemaVaerkatastroferRouteImport } from './routes/tema/vaerkatastrofer'
import { Route as TemaVindsystemetRouteImport } from './routes/tema/vindsystemet'
import { Route as TemaKlimaIndexRouteImport } from './routes/tema/klima/index'
import { Route as TemaKlimaAmocRouteImport } from './routes/tema/klima/amoc'
import { Route as TemaKlimaEnsoRouteImport } from './routes/tema/klima/enso'
import { Route as TemaKlimaIodRouteImport } from './routes/tema/klima/iod'
import { Route as TemaKlimaNaoRouteImport } from './routes/tema/klima/nao'
import { Route as TemaKlimaOversiktRouteImport } from './routes/tema/klima/oversikt'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Geofag2Route = Geofag2RouteImport.update({
  id: '/geofag-2',
  path: '/geofag-2',
  getParentRoute: () => rootRouteImport,
} as any)
const EksamenIndexRoute = EksamenIndexRouteImport.update({
  id: '/eksamen/',
  path: '/eksamen/',
  getParentRoute: () => rootRouteImport,
} as any)
const EksamenSlugRoute = EksamenSlugRouteImport.update({
  id: '/eksamen/$slug',
  path: '/eksamen/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const Geofag1IndexRoute = Geofag1IndexRouteImport.update({
  id: '/geofag-1/',
  path: '/geofag-1/',
  getParentRoute: () => rootRouteImport,
} as any)
const Geofag1SlugRoute = Geofag1SlugRouteImport.update({
  id: '/geofag-1/$slug',
  path: '/geofag-1/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const Geofag1BergarterOgLandformerRoute =
  Geofag1BergarterOgLandformerRouteImport.update({
    id: '/geofag-1/bergarter-og-landformer',
    path: '/geofag-1/bergarter-og-landformer',
    getParentRoute: () => rootRouteImport,
  } as any)
const Geofag1FeltarbeidRoute = Geofag1FeltarbeidRouteImport.update({
  id: '/geofag-1/feltarbeid',
  path: '/geofag-1/feltarbeid',
  getParentRoute: () => rootRouteImport,
} as any)
const Geofag1GeologiskeRessurserRoute =
  Geofag1GeologiskeRessurserRouteImport.update({
    id: '/geofag-1/geologiske-ressurser',
    path: '/geofag-1/geologiske-ressurser',
    getParentRoute: () => rootRouteImport,
  } as any)
const Geofag1JordsystemeneRoute = Geofag1JordsystemeneRouteImport.update({
  id: '/geofag-1/jordsystemene',
  path: '/geofag-1/jordsystemene',
  getParentRoute: () => rootRouteImport,
} as any)
const Geofag1PlatetektonikkRoute = Geofag1PlatetektonikkRouteImport.update({
  id: '/geofag-1/platetektonikk',
  path: '/geofag-1/platetektonikk',
  getParentRoute: () => rootRouteImport,
} as any)
const Geofag1RessurserOgFeltRoute = Geofag1RessurserOgFeltRouteImport.update({
  id: '/geofag-1/ressurser-og-felt',
  path: '/geofag-1/ressurser-og-felt',
  getParentRoute: () => rootRouteImport,
} as any)
const Geofag1SkredRoute = Geofag1SkredRouteImport.update({
  id: '/geofag-1/skred',
  path: '/geofag-1/skred',
  getParentRoute: () => rootRouteImport,
} as any)
const Geofag1VannFlomOgSkredRoute = Geofag1VannFlomOgSkredRouteImport.update({
  id: '/geofag-1/vann-flom-og-skred',
  path: '/geofag-1/vann-flom-og-skred',
  getParentRoute: () => rootRouteImport,
} as any)
const Geofag1VannOgFlomRoute = Geofag1VannOgFlomRouteImport.update({
  id: '/geofag-1/vann-og-flom',
  path: '/geofag-1/vann-og-flom',
  getParentRoute: () => rootRouteImport,
} as any)
const Geofag1VulkanerOgJordskjelvRoute =
  Geofag1VulkanerOgJordskjelvRouteImport.update({
    id: '/geofag-1/vulkaner-og-jordskjelv',
    path: '/geofag-1/vulkaner-og-jordskjelv',
    getParentRoute: () => rootRouteImport,
  } as any)
const TemaCoriolisRoute = TemaCoriolisRouteImport.update({
  id: '/tema/coriolis',
  path: '/tema/coriolis',
  getParentRoute: () => rootRouteImport,
} as any)
const TemaEnergiHavLuftRoute = TemaEnergiHavLuftRouteImport.update({
  id: '/tema/energi-hav-luft',
  path: '/tema/energi-hav-luft',
  getParentRoute: () => rootRouteImport,
} as any)
const TemaFeltHavLuftIsRoute = TemaFeltHavLuftIsRouteImport.update({
  id: '/tema/felt-hav-luft-is',
  path: '/tema/felt-hav-luft-is',
  getParentRoute: () => rootRouteImport,
} as any)
const TemaHavstrommerRoute = TemaHavstrommerRouteImport.update({
  id: '/tema/havstrommer',
  path: '/tema/havstrommer',
  getParentRoute: () => rootRouteImport,
} as any)
const TemaHoytrykkLavtrykkRoute = TemaHoytrykkLavtrykkRouteImport.update({
  id: '/tema/hoytrykk-lavtrykk',
  path: '/tema/hoytrykk-lavtrykk',
  getParentRoute: () => rootRouteImport,
} as any)
const TemaJetstrommerRoute = TemaJetstrommerRouteImport.update({
  id: '/tema/jetstrommer',
  path: '/tema/jetstrommer',
  getParentRoute: () => rootRouteImport,
} as any)
const TemaKryosfareRoute = TemaKryosfareRouteImport.update({
  id: '/tema/kryosfare',
  path: '/tema/kryosfare',
  getParentRoute: () => rootRouteImport,
} as any)
const TemaLokaleVaersystemerRoute = TemaLokaleVaersystemerRouteImport.update({
  id: '/tema/lokale-vaersystemer',
  path: '/tema/lokale-vaersystemer',
  getParentRoute: () => rootRouteImport,
} as any)
const TemaMilankovitchRoute = TemaMilankovitchRouteImport.update({
  id: '/tema/milankovitch',
  path: '/tema/milankovitch',
  getParentRoute: () => rootRouteImport,
} as any)
const TemaNumeriskeModellerRoute = TemaNumeriskeModellerRouteImport.update({
  id: '/tema/numeriske-modeller',
  path: '/tema/numeriske-modeller',
  getParentRoute: () => rootRouteImport,
} as any)
const TemaPaleoklimaRoute = TemaPaleoklimaRouteImport.update({
  id: '/tema/paleoklima',
  path: '/tema/paleoklima',
  getParentRoute: () => rootRouteImport,
} as any)
const TemaTilpasningRoute = TemaTilpasningRouteImport.update({
  id: '/tema/tilpasning',
  path: '/tema/tilpasning',
  getParentRoute: () => rootRouteImport,
} as any)
const TemaVaerkartRoute = TemaVaerkartRouteImport.update({
  id: '/tema/vaerkart',
  path: '/tema/vaerkart',
  getParentRoute: () => rootRouteImport,
} as any)
const TemaVaerkatastroferRoute = TemaVaerkatastroferRouteImport.update({
  id: '/tema/vaerkatastrofer',
  path: '/tema/vaerkatastrofer',
  getParentRoute: () => rootRouteImport,
} as any)
const TemaVindsystemetRoute = TemaVindsystemetRouteImport.update({
  id: '/tema/vindsystemet',
  path: '/tema/vindsystemet',
  getParentRoute: () => rootRouteImport,
} as any)
const TemaKlimaIndexRoute = TemaKlimaIndexRouteImport.update({
  id: '/tema/klima/',
  path: '/tema/klima/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemaKlimaAmocRoute = TemaKlimaAmocRouteImport.update({
  id: '/tema/klima/amoc',
  path: '/tema/klima/amoc',
  getParentRoute: () => rootRouteImport,
} as any)
const TemaKlimaEnsoRoute = TemaKlimaEnsoRouteImport.update({
  id: '/tema/klima/enso',
  path: '/tema/klima/enso',
  getParentRoute: () => rootRouteImport,
} as any)
const TemaKlimaIodRoute = TemaKlimaIodRouteImport.update({
  id: '/tema/klima/iod',
  path: '/tema/klima/iod',
  getParentRoute: () => rootRouteImport,
} as any)
const TemaKlimaNaoRoute = TemaKlimaNaoRouteImport.update({
  id: '/tema/klima/nao',
  path: '/tema/klima/nao',
  getParentRoute: () => rootRouteImport,
} as any)
const TemaKlimaOversiktRoute = TemaKlimaOversiktRouteImport.update({
  id: '/tema/klima/oversikt',
  path: '/tema/klima/oversikt',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/geofag-2': typeof Geofag2Route
  '/eksamen/$slug': typeof EksamenSlugRoute
  '/geofag-1/$slug': typeof Geofag1SlugRoute
  '/geofag-1/bergarter-og-landformer': typeof Geofag1BergarterOgLandformerRoute
  '/geofag-1/feltarbeid': typeof Geofag1FeltarbeidRoute
  '/geofag-1/geologiske-ressurser': typeof Geofag1GeologiskeRessurserRoute
  '/geofag-1/jordsystemene': typeof Geofag1JordsystemeneRoute
  '/geofag-1/platetektonikk': typeof Geofag1PlatetektonikkRoute
  '/geofag-1/ressurser-og-felt': typeof Geofag1RessurserOgFeltRoute
  '/geofag-1/skred': typeof Geofag1SkredRoute
  '/geofag-1/vann-flom-og-skred': typeof Geofag1VannFlomOgSkredRoute
  '/geofag-1/vann-og-flom': typeof Geofag1VannOgFlomRoute
  '/geofag-1/vulkaner-og-jordskjelv': typeof Geofag1VulkanerOgJordskjelvRoute
  '/tema/coriolis': typeof TemaCoriolisRoute
  '/tema/energi-hav-luft': typeof TemaEnergiHavLuftRoute
  '/tema/felt-hav-luft-is': typeof TemaFeltHavLuftIsRoute
  '/tema/havstrommer': typeof TemaHavstrommerRoute
  '/tema/hoytrykk-lavtrykk': typeof TemaHoytrykkLavtrykkRoute
  '/tema/jetstrommer': typeof TemaJetstrommerRoute
  '/tema/kryosfare': typeof TemaKryosfareRoute
  '/tema/lokale-vaersystemer': typeof TemaLokaleVaersystemerRoute
  '/tema/milankovitch': typeof TemaMilankovitchRoute
  '/tema/numeriske-modeller': typeof TemaNumeriskeModellerRoute
  '/tema/paleoklima': typeof TemaPaleoklimaRoute
  '/tema/tilpasning': typeof TemaTilpasningRoute
  '/tema/vaerkart': typeof TemaVaerkartRoute
  '/tema/vaerkatastrofer': typeof TemaVaerkatastroferRoute
  '/tema/vindsystemet': typeof TemaVindsystemetRoute
  '/eksamen/': typeof EksamenIndexRoute
  '/geofag-1/': typeof Geofag1IndexRoute
  '/tema/klima/amoc': typeof TemaKlimaAmocRoute
  '/tema/klima/enso': typeof TemaKlimaEnsoRoute
  '/tema/klima/iod': typeof TemaKlimaIodRoute
  '/tema/klima/nao': typeof TemaKlimaNaoRoute
  '/tema/klima/oversikt': typeof TemaKlimaOversiktRoute
  '/tema/klima/': typeof TemaKlimaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/geofag-2': typeof Geofag2Route
  '/eksamen/$slug': typeof EksamenSlugRoute
  '/geofag-1/$slug': typeof Geofag1SlugRoute
  '/geofag-1/bergarter-og-landformer': typeof Geofag1BergarterOgLandformerRoute
  '/geofag-1/feltarbeid': typeof Geofag1FeltarbeidRoute
  '/geofag-1/geologiske-ressurser': typeof Geofag1GeologiskeRessurserRoute
  '/geofag-1/jordsystemene': typeof Geofag1JordsystemeneRoute
  '/geofag-1/platetektonikk': typeof Geofag1PlatetektonikkRoute
  '/geofag-1/ressurser-og-felt': typeof Geofag1RessurserOgFeltRoute
  '/geofag-1/skred': typeof Geofag1SkredRoute
  '/geofag-1/vann-flom-og-skred': typeof Geofag1VannFlomOgSkredRoute
  '/geofag-1/vann-og-flom': typeof Geofag1VannOgFlomRoute
  '/geofag-1/vulkaner-og-jordskjelv': typeof Geofag1VulkanerOgJordskjelvRoute
  '/tema/coriolis': typeof TemaCoriolisRoute
  '/tema/energi-hav-luft': typeof TemaEnergiHavLuftRoute
  '/tema/felt-hav-luft-is': typeof TemaFeltHavLuftIsRoute
  '/tema/havstrommer': typeof TemaHavstrommerRoute
  '/tema/hoytrykk-lavtrykk': typeof TemaHoytrykkLavtrykkRoute
  '/tema/jetstrommer': typeof TemaJetstrommerRoute
  '/tema/kryosfare': typeof TemaKryosfareRoute
  '/tema/lokale-vaersystemer': typeof TemaLokaleVaersystemerRoute
  '/tema/milankovitch': typeof TemaMilankovitchRoute
  '/tema/numeriske-modeller': typeof TemaNumeriskeModellerRoute
  '/tema/paleoklima': typeof TemaPaleoklimaRoute
  '/tema/tilpasning': typeof TemaTilpasningRoute
  '/tema/vaerkart': typeof TemaVaerkartRoute
  '/tema/vaerkatastrofer': typeof TemaVaerkatastroferRoute
  '/tema/vindsystemet': typeof TemaVindsystemetRoute
  '/eksamen': typeof EksamenIndexRoute
  '/geofag-1': typeof Geofag1IndexRoute
  '/tema/klima/amoc': typeof TemaKlimaAmocRoute
  '/tema/klima/enso': typeof TemaKlimaEnsoRoute
  '/tema/klima/iod': typeof TemaKlimaIodRoute
  '/tema/klima/nao': typeof TemaKlimaNaoRoute
  '/tema/klima/oversikt': typeof TemaKlimaOversiktRoute
  '/tema/klima': typeof TemaKlimaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/geofag-2': typeof Geofag2Route
  '/eksamen/$slug': typeof EksamenSlugRoute
  '/geofag-1/$slug': typeof Geofag1SlugRoute
  '/geofag-1/bergarter-og-landformer': typeof Geofag1BergarterOgLandformerRoute
  '/geofag-1/feltarbeid': typeof Geofag1FeltarbeidRoute
  '/geofag-1/geologiske-ressurser': typeof Geofag1GeologiskeRessurserRoute
  '/geofag-1/jordsystemene': typeof Geofag1JordsystemeneRoute
  '/geofag-1/platetektonikk': typeof Geofag1PlatetektonikkRoute
  '/geofag-1/ressurser-og-felt': typeof Geofag1RessurserOgFeltRoute
  '/geofag-1/skred': typeof Geofag1SkredRoute
  '/geofag-1/vann-flom-og-skred': typeof Geofag1VannFlomOgSkredRoute
  '/geofag-1/vann-og-flom': typeof Geofag1VannOgFlomRoute
  '/geofag-1/vulkaner-og-jordskjelv': typeof Geofag1VulkanerOgJordskjelvRoute
  '/tema/coriolis': typeof TemaCoriolisRoute
  '/tema/energi-hav-luft': typeof TemaEnergiHavLuftRoute
  '/tema/felt-hav-luft-is': typeof TemaFeltHavLuftIsRoute
  '/tema/havstrommer': typeof TemaHavstrommerRoute
  '/tema/hoytrykk-lavtrykk': typeof TemaHoytrykkLavtrykkRoute
  '/tema/jetstrommer': typeof TemaJetstrommerRoute
  '/tema/kryosfare': typeof TemaKryosfareRoute
  '/tema/lokale-vaersystemer': typeof TemaLokaleVaersystemerRoute
  '/tema/milankovitch': typeof TemaMilankovitchRoute
  '/tema/numeriske-modeller': typeof TemaNumeriskeModellerRoute
  '/tema/paleoklima': typeof TemaPaleoklimaRoute
  '/tema/tilpasning': typeof TemaTilpasningRoute
  '/tema/vaerkart': typeof TemaVaerkartRoute
  '/tema/vaerkatastrofer': typeof TemaVaerkatastroferRoute
  '/tema/vindsystemet': typeof TemaVindsystemetRoute
  '/eksamen/': typeof EksamenIndexRoute
  '/geofag-1/': typeof Geofag1IndexRoute
  '/tema/klima/amoc': typeof TemaKlimaAmocRoute
  '/tema/klima/enso': typeof TemaKlimaEnsoRoute
  '/tema/klima/iod': typeof TemaKlimaIodRoute
  '/tema/klima/nao': typeof TemaKlimaNaoRoute
  '/tema/klima/oversikt': typeof TemaKlimaOversiktRoute
  '/tema/klima/': typeof TemaKlimaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/geofag-2'
    | '/eksamen/$slug'
    | '/geofag-1/$slug'
    | '/geofag-1/bergarter-og-landformer'
    | '/geofag-1/feltarbeid'
    | '/geofag-1/geologiske-ressurser'
    | '/geofag-1/jordsystemene'
    | '/geofag-1/platetektonikk'
    | '/geofag-1/ressurser-og-felt'
    | '/geofag-1/skred'
    | '/geofag-1/vann-flom-og-skred'
    | '/geofag-1/vann-og-flom'
    | '/geofag-1/vulkaner-og-jordskjelv'
    | '/tema/coriolis'
    | '/tema/energi-hav-luft'
    | '/tema/felt-hav-luft-is'
    | '/tema/havstrommer'
    | '/tema/hoytrykk-lavtrykk'
    | '/tema/jetstrommer'
    | '/tema/kryosfare'
    | '/tema/lokale-vaersystemer'
    | '/tema/milankovitch'
    | '/tema/numeriske-modeller'
    | '/tema/paleoklima'
    | '/tema/tilpasning'
    | '/tema/vaerkart'
    | '/tema/vaerkatastrofer'
    | '/tema/vindsystemet'
    | '/eksamen/'
    | '/geofag-1/'
    | '/tema/klima/amoc'
    | '/tema/klima/enso'
    | '/tema/klima/iod'
    | '/tema/klima/nao'
    | '/tema/klima/oversikt'
    | '/tema/klima/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/geofag-2'
    | '/eksamen/$slug'
    | '/geofag-1/$slug'
    | '/geofag-1/bergarter-og-landformer'
    | '/geofag-1/feltarbeid'
    | '/geofag-1/geologiske-ressurser'
    | '/geofag-1/jordsystemene'
    | '/geofag-1/platetektonikk'
    | '/geofag-1/ressurser-og-felt'
    | '/geofag-1/skred'
    | '/geofag-1/vann-flom-og-skred'
    | '/geofag-1/vann-og-flom'
    | '/geofag-1/vulkaner-og-jordskjelv'
    | '/tema/coriolis'
    | '/tema/energi-hav-luft'
    | '/tema/felt-hav-luft-is'
    | '/tema/havstrommer'
    | '/tema/hoytrykk-lavtrykk'
    | '/tema/jetstrommer'
    | '/tema/kryosfare'
    | '/tema/lokale-vaersystemer'
    | '/tema/milankovitch'
    | '/tema/numeriske-modeller'
    | '/tema/paleoklima'
    | '/tema/tilpasning'
    | '/tema/vaerkart'
    | '/tema/vaerkatastrofer'
    | '/tema/vindsystemet'
    | '/eksamen'
    | '/geofag-1'
    | '/tema/klima/amoc'
    | '/tema/klima/enso'
    | '/tema/klima/iod'
    | '/tema/klima/nao'
    | '/tema/klima/oversikt'
    | '/tema/klima'
  id:
    | '__root__'
    | '/'
    | '/geofag-2'
    | '/eksamen/$slug'
    | '/geofag-1/$slug'
    | '/geofag-1/bergarter-og-landformer'
    | '/geofag-1/feltarbeid'
    | '/geofag-1/geologiske-ressurser'
    | '/geofag-1/jordsystemene'
    | '/geofag-1/platetektonikk'
    | '/geofag-1/ressurser-og-felt'
    | '/geofag-1/skred'
    | '/geofag-1/vann-flom-og-skred'
    | '/geofag-1/vann-og-flom'
    | '/geofag-1/vulkaner-og-jordskjelv'
    | '/tema/coriolis'
    | '/tema/energi-hav-luft'
    | '/tema/felt-hav-luft-is'
    | '/tema/havstrommer'
    | '/tema/hoytrykk-lavtrykk'
    | '/tema/jetstrommer'
    | '/tema/kryosfare'
    | '/tema/lokale-vaersystemer'
    | '/tema/milankovitch'
    | '/tema/numeriske-modeller'
    | '/tema/paleoklima'
    | '/tema/tilpasning'
    | '/tema/vaerkart'
    | '/tema/vaerkatastrofer'
    | '/tema/vindsystemet'
    | '/eksamen/'
    | '/geofag-1/'
    | '/tema/klima/amoc'
    | '/tema/klima/enso'
    | '/tema/klima/iod'
    | '/tema/klima/nao'
    | '/tema/klima/oversikt'
    | '/tema/klima/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Geofag2Route: typeof Geofag2Route
  EksamenSlugRoute: typeof EksamenSlugRoute
  Geofag1SlugRoute: typeof Geofag1SlugRoute
  Geofag1BergarterOgLandformerRoute: typeof Geofag1BergarterOgLandformerRoute
  Geofag1FeltarbeidRoute: typeof Geofag1FeltarbeidRoute
  Geofag1GeologiskeRessurserRoute: typeof Geofag1GeologiskeRessurserRoute
  Geofag1JordsystemeneRoute: typeof Geofag1JordsystemeneRoute
  Geofag1PlatetektonikkRoute: typeof Geofag1PlatetektonikkRoute
  Geofag1RessurserOgFeltRoute: typeof Geofag1RessurserOgFeltRoute
  Geofag1SkredRoute: typeof Geofag1SkredRoute
  Geofag1VannFlomOgSkredRoute: typeof Geofag1VannFlomOgSkredRoute
  Geofag1VannOgFlomRoute: typeof Geofag1VannOgFlomRoute
  Geofag1VulkanerOgJordskjelvRoute: typeof Geofag1VulkanerOgJordskjelvRoute
  TemaCoriolisRoute: typeof TemaCoriolisRoute
  TemaEnergiHavLuftRoute: typeof TemaEnergiHavLuftRoute
  TemaFeltHavLuftIsRoute: typeof TemaFeltHavLuftIsRoute
  TemaHavstrommerRoute: typeof TemaHavstrommerRoute
  TemaHoytrykkLavtrykkRoute: typeof TemaHoytrykkLavtrykkRoute
  TemaJetstrommerRoute: typeof TemaJetstrommerRoute
  TemaKryosfareRoute: typeof TemaKryosfareRoute
  TemaLokaleVaersystemerRoute: typeof TemaLokaleVaersystemerRoute
  TemaMilankovitchRoute: typeof TemaMilankovitchRoute
  TemaNumeriskeModellerRoute: typeof TemaNumeriskeModellerRoute
  TemaPaleoklimaRoute: typeof TemaPaleoklimaRoute
  TemaTilpasningRoute: typeof TemaTilpasningRoute
  TemaVaerkartRoute: typeof TemaVaerkartRoute
  TemaVaerkatastroferRoute: typeof TemaVaerkatastroferRoute
  TemaVindsystemetRoute: typeof TemaVindsystemetRoute
  EksamenIndexRoute: typeof EksamenIndexRoute
  Geofag1IndexRoute: typeof Geofag1IndexRoute
  TemaKlimaAmocRoute: typeof TemaKlimaAmocRoute
  TemaKlimaEnsoRoute: typeof TemaKlimaEnsoRoute
  TemaKlimaIodRoute: typeof TemaKlimaIodRoute
  TemaKlimaNaoRoute: typeof TemaKlimaNaoRoute
  TemaKlimaOversiktRoute: typeof TemaKlimaOversiktRoute
  TemaKlimaIndexRoute: typeof TemaKlimaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geofag-2': {
      id: '/geofag-2'
      path: '/geofag-2'
      fullPath: '/geofag-2'
      preLoaderRoute: typeof Geofag2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eksamen/': {
      id: '/eksamen/'
      path: '/eksamen'
      fullPath: '/eksamen/'
      preLoaderRoute: typeof EksamenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eksamen/$slug': {
      id: '/eksamen/$slug'
      path: '/eksamen/$slug'
      fullPath: '/eksamen/$slug'
      preLoaderRoute: typeof EksamenSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geofag-1/': {
      id: '/geofag-1/'
      path: '/geofag-1'
      fullPath: '/geofag-1/'
      preLoaderRoute: typeof Geofag1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geofag-1/$slug': {
      id: '/geofag-1/$slug'
      path: '/geofag-1/$slug'
      fullPath: '/geofag-1/$slug'
      preLoaderRoute: typeof Geofag1SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geofag-1/bergarter-og-landformer': {
      id: '/geofag-1/bergarter-og-landformer'
      path: '/geofag-1/bergarter-og-landformer'
      fullPath: '/geofag-1/bergarter-og-landformer'
      preLoaderRoute: typeof Geofag1BergarterOgLandformerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geofag-1/feltarbeid': {
      id: '/geofag-1/feltarbeid'
      path: '/geofag-1/feltarbeid'
      fullPath: '/geofag-1/feltarbeid'
      preLoaderRoute: typeof Geofag1FeltarbeidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geofag-1/geologiske-ressurser': {
      id: '/geofag-1/geologiske-ressurser'
      path: '/geofag-1/geologiske-ressurser'
      fullPath: '/geofag-1/geologiske-ressurser'
      preLoaderRoute: typeof Geofag1GeologiskeRessurserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geofag-1/jordsystemene': {
      id: '/geofag-1/jordsystemene'
      path: '/geofag-1/jordsystemene'
      fullPath: '/geofag-1/jordsystemene'
      preLoaderRoute: typeof Geofag1JordsystemeneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geofag-1/platetektonikk': {
      id: '/geofag-1/platetektonikk'
      path: '/geofag-1/platetektonikk'
      fullPath: '/geofag-1/platetektonikk'
      preLoaderRoute: typeof Geofag1PlatetektonikkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geofag-1/ressurser-og-felt': {
      id: '/geofag-1/ressurser-og-felt'
      path: '/geofag-1/ressurser-og-felt'
      fullPath: '/geofag-1/ressurser-og-felt'
      preLoaderRoute: typeof Geofag1RessurserOgFeltRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geofag-1/skred': {
      id: '/geofag-1/skred'
      path: '/geofag-1/skred'
      fullPath: '/geofag-1/skred'
      preLoaderRoute: typeof Geofag1SkredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geofag-1/vann-flom-og-skred': {
      id: '/geofag-1/vann-flom-og-skred'
      path: '/geofag-1/vann-flom-og-skred'
      fullPath: '/geofag-1/vann-flom-og-skred'
      preLoaderRoute: typeof Geofag1VannFlomOgSkredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geofag-1/vann-og-flom': {
      id: '/geofag-1/vann-og-flom'
      path: '/geofag-1/vann-og-flom'
      fullPath: '/geofag-1/vann-og-flom'
      preLoaderRoute: typeof Geofag1VannOgFlomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geofag-1/vulkaner-og-jordskjelv': {
      id: '/geofag-1/vulkaner-og-jordskjelv'
      path: '/geofag-1/vulkaner-og-jordskjelv'
      fullPath: '/geofag-1/vulkaner-og-jordskjelv'
      preLoaderRoute: typeof Geofag1VulkanerOgJordskjelvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tema/coriolis': {
      id: '/tema/coriolis'
      path: '/tema/coriolis'
      fullPath: '/tema/coriolis'
      preLoaderRoute: typeof TemaCoriolisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tema/energi-hav-luft': {
      id: '/tema/energi-hav-luft'
      path: '/tema/energi-hav-luft'
      fullPath: '/tema/energi-hav-luft'
      preLoaderRoute: typeof TemaEnergiHavLuftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tema/felt-hav-luft-is': {
      id: '/tema/felt-hav-luft-is'
      path: '/tema/felt-hav-luft-is'
      fullPath: '/tema/felt-hav-luft-is'
      preLoaderRoute: typeof TemaFeltHavLuftIsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tema/havstrommer': {
      id: '/tema/havstrommer'
      path: '/tema/havstrommer'
      fullPath: '/tema/havstrommer'
      preLoaderRoute: typeof TemaHavstrommerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tema/hoytrykk-lavtrykk': {
      id: '/tema/hoytrykk-lavtrykk'
      path: '/tema/hoytrykk-lavtrykk'
      fullPath: '/tema/hoytrykk-lavtrykk'
      preLoaderRoute: typeof TemaHoytrykkLavtrykkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tema/jetstrommer': {
      id: '/tema/jetstrommer'
      path: '/tema/jetstrommer'
      fullPath: '/tema/jetstrommer'
      preLoaderRoute: typeof TemaJetstrommerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tema/kryosfare': {
      id: '/tema/kryosfare'
      path: '/tema/kryosfare'
      fullPath: '/tema/kryosfare'
      preLoaderRoute: typeof TemaKryosfareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tema/lokale-vaersystemer': {
      id: '/tema/lokale-vaersystemer'
      path: '/tema/lokale-vaersystemer'
      fullPath: '/tema/lokale-vaersystemer'
      preLoaderRoute: typeof TemaLokaleVaersystemerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tema/milankovitch': {
      id: '/tema/milankovitch'
      path: '/tema/milankovitch'
      fullPath: '/tema/milankovitch'
      preLoaderRoute: typeof TemaMilankovitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tema/numeriske-modeller': {
      id: '/tema/numeriske-modeller'
      path: '/tema/numeriske-modeller'
      fullPath: '/tema/numeriske-modeller'
      preLoaderRoute: typeof TemaNumeriskeModellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tema/paleoklima': {
      id: '/tema/paleoklima'
      path: '/tema/paleoklima'
      fullPath: '/tema/paleoklima'
      preLoaderRoute: typeof TemaPaleoklimaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tema/tilpasning': {
      id: '/tema/tilpasning'
      path: '/tema/tilpasning'
      fullPath: '/tema/tilpasning'
      preLoaderRoute: typeof TemaTilpasningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tema/vaerkart': {
      id: '/tema/vaerkart'
      path: '/tema/vaerkart'
      fullPath: '/tema/vaerkart'
      preLoaderRoute: typeof TemaVaerkartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tema/vaerkatastrofer': {
      id: '/tema/vaerkatastrofer'
      path: '/tema/vaerkatastrofer'
      fullPath: '/tema/vaerkatastrofer'
      preLoaderRoute: typeof TemaVaerkatastroferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tema/vindsystemet': {
      id: '/tema/vindsystemet'
      path: '/tema/vindsystemet'
      fullPath: '/tema/vindsystemet'
      preLoaderRoute: typeof TemaVindsystemetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tema/klima/': {
      id: '/tema/klima/'
      path: '/tema/klima'
      fullPath: '/tema/klima/'
      preLoaderRoute: typeof TemaKlimaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tema/klima/amoc': {
      id: '/tema/klima/amoc'
      path: '/tema/klima/amoc'
      fullPath: '/tema/klima/amoc'
      preLoaderRoute: typeof TemaKlimaAmocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tema/klima/enso': {
      id: '/tema/klima/enso'
      path: '/tema/klima/enso'
      fullPath: '/tema/klima/enso'
      preLoaderRoute: typeof TemaKlimaEnsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tema/klima/iod': {
      id: '/tema/klima/iod'
      path: '/tema/klima/iod'
      fullPath: '/tema/klima/iod'
      preLoaderRoute: typeof TemaKlimaIodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tema/klima/nao': {
      id: '/tema/klima/nao'
      path: '/tema/klima/nao'
      fullPath: '/tema/klima/nao'
      preLoaderRoute: typeof TemaKlimaNaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tema/klima/oversikt': {
      id: '/tema/klima/oversikt'
      path: '/tema/klima/oversikt'
      fullPath: '/tema/klima/oversikt'
      preLoaderRoute: typeof TemaKlimaOversiktRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Geofag2Route: Geofag2Route,
  EksamenSlugRoute: EksamenSlugRoute,
  Geofag1SlugRoute: Geofag1SlugRoute,
  Geofag1BergarterOgLandformerRoute: Geofag1BergarterOgLandformerRoute,
  Geofag1FeltarbeidRoute: Geofag1FeltarbeidRoute,
  Geofag1GeologiskeRessurserRoute: Geofag1GeologiskeRessurserRoute,
  Geofag1JordsystemeneRoute: Geofag1JordsystemeneRoute,
  Geofag1PlatetektonikkRoute: Geofag1PlatetektonikkRoute,
  Geofag1RessurserOgFeltRoute: Geofag1RessurserOgFeltRoute,
  Geofag1SkredRoute: Geofag1SkredRoute,
  Geofag1VannFlomOgSkredRoute: Geofag1VannFlomOgSkredRoute,
  Geofag1VannOgFlomRoute: Geofag1VannOgFlomRoute,
  Geofag1VulkanerOgJordskjelvRoute: Geofag1VulkanerOgJordskjelvRoute,
  TemaCoriolisRoute: TemaCoriolisRoute,
  TemaEnergiHavLuftRoute: TemaEnergiHavLuftRoute,
  TemaFeltHavLuftIsRoute: TemaFeltHavLuftIsRoute,
  TemaHavstrommerRoute: TemaHavstrommerRoute,
  TemaHoytrykkLavtrykkRoute: TemaHoytrykkLavtrykkRoute,
  TemaJetstrommerRoute: TemaJetstrommerRoute,
  TemaKryosfareRoute: TemaKryosfareRoute,
  TemaLokaleVaersystemerRoute: TemaLokaleVaersystemerRoute,
  TemaMilankovitchRoute: TemaMilankovitchRoute,
  TemaNumeriskeModellerRoute: TemaNumeriskeModellerRoute,
  TemaPaleoklimaRoute: TemaPaleoklimaRoute,
  TemaTilpasningRoute: TemaTilpasningRoute,
  TemaVaerkartRoute: TemaVaerkartRoute,
  TemaVaerkatastroferRoute: TemaVaerkatastroferRoute,
  TemaVindsystemetRoute: TemaVindsystemetRoute,
  EksamenIndexRoute: EksamenIndexRoute,
  Geofag1IndexRoute: Geofag1IndexRoute,
  TemaKlimaAmocRoute: TemaKlimaAmocRoute,
  TemaKlimaEnsoRoute: TemaKlimaEnsoRoute,
  TemaKlimaIodRoute: TemaKlimaIodRoute,
  TemaKlimaNaoRoute: TemaKlimaNaoRoute,
  TemaKlimaOversiktRoute: TemaKlimaOversiktRoute,
  TemaKlimaIndexRoute: TemaKlimaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
