import type { ExamSet } from "../types";

export const eksempel: ExamSet = {
  slug: "eksempel",
  label: "Eksempeloppgave",
  season: null,
  year: null,
  kind: "eksempel",
  complete: false,
  officialUrl: "https://kandidat.udir.no/epsmateriell/eksempeloppgave?fagkode=REA3043&malform=nb-NO",
  themes: [
    "Sommerværet i Europa 2025",
    "Hav og klima i og rundt Nord-Atlanteren",
    "Tolkning og presentasjon av feltdata",
    "Havvindutbygging i Nordsjøen",
  ],
  tasks: [
    {
      number: 1,
      title: "Sommerværet i Europa i 2025",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\nOppgave 1\nOppgave 1 – Sommerværet i Europa i 2025\n\nOppgave 1 av 6 til tema 1. \n\nDu skal svare på oppgaven nederst på siden.\n\nNaturfare i Polen\n\nNedenfor finner du to kart som viser hvordan været var i Europa i juli 2025.\n\nKart 1\nKart 2\nKilde: https://climatereanalyzer.org/research_tools/monthly_maps/output_png/era5-0p5deg_65.png\nForrige fane\nPDF\nNeste fane\nOppgave\n\nHva slags ekstremvær var det størst fare for at Polen ble rammet av i juli 2025?\n\nflom og hetebølger\nflom og styrtregn\ntropiske sykloner og flom\nhetebølger\ntørke, hetebølger og skogbranner",
    },
    {
      number: 2,
      title: "Sommerværet i Europa i 2025",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\nOppgave 2\nOppgave 2 – Sommerværet i Europa i 2025\n\nOppgave 2 av 6 til tema 1. \n\nDu skal svare på oppgaven nederst på siden.\n\nEkstremvær i Hellas\nNedenfor finner du to kart som viser hvordan været var i Europa i juli 2025.\nKart 1\nKart 2\nKilde: https://climatereanalyzer.org/research_tools/monthly_maps/output_png/era5-0p5deg_65.png\nForrige fane\nPDF\nNeste fane\nHva slags ekstremvær var det størst fare for at Hellas ble rammet av i juli 2025?\nflom og hetebølger\nflom og styrtregn\ntropiske sykloner og storm\nhetebølger\ntørke, hetebølger og skogbranner",
    },
    {
      number: 3,
      title: "Sommerværet i Europa i 2025",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\nOppgave 3\nOppgave 3 – Sommerværet i Europa i 2025\n\nOppgave 3 av 6 til tema 1. \n\nDu skal svare på oppgaven nederst på siden.\n\nTemperaturanomali i luften over havet\n\nNedenfor finner du to kart som viser hvordan været var i Europa i juli 2025 og et tredje kart som viser temperaturanomalier i havoverflaten i Europa i juli 2025. Legg merke til at Norskehavet og de sentrale delene av Østersjøen reagerte ulikt på været denne måneden. \n\n \n\nKart 1\nKart 2\nKart 3\nKilde: https://climatereanalyzer.org/research_tools/monthly_maps/output_png/era5-0p5deg_65.png\nForrige fane\nPDF\nNeste fane\nOppgave \n\nHva er den mest sannsynlige årsaken til at Norskehavet og Østersjøen responderte så forskjellig på været denne måneden? \n\nNorskehavet var unormalt kaldt, og Østersjøen var unormalt varm. Dette reflekterer lufttemperaturen på land, der elvene som renner ut i de to havområdene, kommer fra. \nNorskehavet var unormalt kaldt, og Østersjøen var unormalt varm. Dette kommer delvis som følge av at elvene i Norge fikk veldig høy vannføring etter mye nedbør, og dette vannet kjølte ned havoverflaten. Situasjonen i Østersjøen var motsatt.\nNorskehavet var unormalt varmt, og Østersjøen var unormalt kald. Dette kommer delvis som følge av økt solinnstråling til Nordsjøen på grunn av lite skyer, og redusert solinnstråling til Østersjøen på grunn av mye skyer og nedbør.\nNorskehavet var unormalt varmt, og Østersjøen var unormalt kald. Dette kan komme av at Norskehavet har sterkere tidevannsstrømmer, som bidrar til oppvarmingen, mens Østersjøen har svakere strømmer, som fører til avkjøling.",
    },
    {
      number: 4,
      title: "Sommerværet i Europa i 2025",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\nOppgave 4\nOppgave 4 – Sommerværet i Europa i 2025\n\nOppgave 4 av 6 til tema 1. \n\nDu skal svare på oppgaven nederst på siden.\n\nBreer i Alpene\n\nNedenfor finner du to kart som viser hvordan været var i Europa i juli 2025. \n\nI området mellom Frankrike, Sveits, Østerrike og Nord-Italia ligger Alpene. I Alpene er det mange isbreer som man frykter skal forsvinne.\n\nKart 1\nKart 2\nKilde: https://climatereanalyzer.org/research_tools/monthly_maps/output_png/era5-0p5deg_65.png\nForrige fane\nPDF\nNeste fane\nOppgave\nHva har sannsynligvis skjedd med breene i Alpene i juli 2025, ut fra kartene ovenfor?\nDe smeltet noe mindre enn de vanligvis gjør i juli.\nDe smeltet noe mer enn de vanligvis gjør i juli.\nDe smeltet like mye som de vanligvis gjør i juli.",
    },
    {
      number: 5,
      title: "Sommerværet i Europa i 2025",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "REA3043 Geofag 2\nOppgave 5\nOppgave 5 – Sommerværet i Europa i 2025\nOppgave 5 av 6 til tema 1.\nDu skal svare på oppgaven nederst på siden.\nMarin hetebølge i Lofoten\n\nDette er en plassholder for en oppgave. Oppgaven er ikke ferdiglaget. Plassholderen er bare for å vise tema og oppgavetyper. \n\nalternativ 1\nalternativ 2\nalternativ 3",
    },
    {
      number: 6,
      title: "Sommerværet i Europa i 2025",
      kind: "skrive",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\nOppgave 6\nOppgave 6 – Sommerværet i Europa i 2025\n\nOppgave 6 av 6 til tema 1.\n\nDu skal svare på oppgaven nederst på siden. \n\nDette er en skriveoppgave.\n\nMenneskelig påvirkning på været\n\nNedenfor finner du to kart som viser hvordan været var i Europa i juli 2025.\n\nKart 1\nKart 2\nKilde: https://climatereanalyzer.org/research_tools/monthly_maps/output_png/era5-0p5deg_65.png\nForrige fane\nPDF\nNeste fane\nOppgave\n\nDrøft om anomaliene i været i Europa i juli 2025 bare skyldes menneskelig aktivitet.",
    },
    {
      number: 7,
      title: "Hav og klima i og rundt Nord-Atlanteren",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "REA3043 Geofag 2\nOppgave 7\nOppgave 7 – Hav og klima i og rundt Nord-Atlanteren\n\nOppgave 1 av 6 til tema 2.\n\nDu skal svare på oppgaven nederst på siden.\nMarine hetebølger\n\nMarine hetebølger er perioder der havoverflatetemperaturen er høyere enn vanlig.\n\nNedenfor er det fire påstander om marine hetebølger.\n\nMye solinnstråling og redusert skydekke kan være årsaker til marine hetebølger.\nSvak vind, lite bølger og svake havstrømmer kan gi sterk lagdeling i havet. Dette er gunstige forhold for dannelse av marine hetebølger.\nI perioder med La Niña-forhold oppstår det ofte marine hetebølger.\nMarine hetebølger kan føre til svakere tropiske orkaner.\nOppgave\n\nHvilke påstander om marine hetebølger stemmer?\n\npåstand 1 og 2\npåstand 1 og 3\npåstand 2 og 3\npåstand 2 og 4",
    },
    {
      number: 8,
      title: "Hav og klima i og rundt Nord-Atlanteren",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\nOppgave 8\nOppgave 8 – Hav og klima i og rundt Nord-Atlanteren\n\nOppgave 2 av 6 til tema 2.\n\nDu skal svare på oppgaven nederst på siden.\n\nVil AMOC kunne kollapse? \n\nInformasjonen nedenfor vil du få bruk for i senere oppgaver i tema 2 også.\n\nAMOC\n\nGolfstrømmen utgjør den vestlige delen av den store subtropiske gyren i Nord-Atlanteren. Golfstrømmen eller Golfstrømsystemet er en del av den termohaline sirkulasjonen i Atlanterhavet. Den termohaline sirkulasjonen gir opphav til omveltningssirkulasjonen i Atlanterhavet, kjent som Atlantic Meridional Overturning Circulation (AMOC) på engelsk. \n\nAMOC er et viktig system av havstrømmer i Atlanterhavet. Dette systemet fungerer som en gigantisk varmepumpe: Varmt overflatevann strømmer nordover, blir avkjølt, synker ned i dypet og strømmer så sørover igjen. Denne sirkulasjonen er helt avgjørende for klimaet vårt, spesielt i Nord-Europa.\n\nEt 3D-blikk på havsirkulasjonen i Atlanterhavet sett fra 26 grader nord. I øvre lag frakter Golfstrømmen varmt vann nordover. Den subtropiske gyren sirkulerer med klokken, og den subpolare gyren sirkulerer mot klokken. Vertikalt kjøles varmt overflatevann ned og synker som en del av omveltningssirkulasjonen (AMOC). (Grafikk: J. Skrefsrud / H. Asbjørnsen. Kilde: Asbjørnsen, 2023)\n\nEn rekke forskere har brukt klimamodeller for å undersøke hvordan AMOC vil endre seg med en dobling av CO2 i atmosfæren, hvor den globale oppvarmingen fører til at innlandsisen på Grønland smelter. Modellen har blant annet gitt resultatet vi ser i figuren nedenfor.\n\nEndringer i årlig gjennomsnittlig temperaturendring i en tenkt framtid der CO2-nivåene er doblet og AMOC har kollapset fullstendig. Kilde: Liu et al., 2017.\n\nI dag er forskerne uenige om hvor sårbar AMOC er for klimaendringer. La oss se på argumentene:\n\nDe bekymrede forskerne peker på at global oppvarming kan forstyrre AMOC på to måter: For det første gjør varmere hav at vannet blir lettere og dermed vanskeligere synker ned. For det andre fører smelting av is på Grønland til mer ferskvann i havet. Siden ferskvann er lettere enn saltvann, kan dette hindre dypvannsdannelsen som driver sirkulasjonen. Noen forskere frykter at hvis vi når et bestemt punkt, et vippepunkt, kan hele systemet kollapse relativt raskt. En nederlandsk studie viser at hvis dette skjer, kan temperaturen i Bergen falle med opptil 30 grader.\n\nPå den andre siden mener flere norske forskere at frykten er overdrevet. De peker på to hovedgrunner: For det første drives Golfstrømmen hovedsakelig av vind og jordens rotasjon – krefter som vil fortsette uansett. For det andre viser de til at studiene som varsler om kollaps, bruker urealistiske mengder ferskvann i sine modeller.\n\nDet forskerne er enige om, er at AMOC sannsynligvis vil svekkes med omkring 30 prosent innen år 2100 hvis vi fortsetter med høye CO2-utslipp. Forskerne er altså uenige om hvor dramatisk situasjonen er, men de er enige om at klimaendringene påvirker havsirkulasjonen, og at dette er noe vi må ta på alvor.\n\nPDF\nOppgave\n\nHvorfor kan global oppvarming føre til at AMOC (omveltningssirkulasjonen i Atlanterhavet) kollapser?\n\nGlobal oppvarming vil føre til økt fordamping og dermed økt salinitet i havvannet. Dermed vil alt vannet få like høy densitet, og sirkulasjonen vil kollapse.\nGlobal oppvarming vil føre til at innlandsisen på Grønland smelter. Dermed tilføres det mye kaldt ferskvann i havet, noe som kan få sirkulasjonen til å kollapse.\nGlobal oppvarming vil føre til økt nedbør i form av regn i de nordlige delene av Atlanterhavet. Dermed kan det ikke dannes sjøis, og dette vil føre til at det ikke skjer noen dypvannsdannelse.",
    },
    {
      number: 9,
      title: "Hav og klima i og rundt Nord-Atlanteren",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "REA3043 Geofag 2\nOppgave 9\nOppgave 9 – Hav og klima i og rundt Nord-Atlanteren\n\nOppgave 3 av 6 til tema 2.\n\nDu skal svare på oppgaven nederst på siden.\n\nVæret langs vestkysten av Norge\n\nFullfør setningen nedenfor slik at den gir en riktig beskrivelse at hva som vil skje med med været langs vestkysten av Norge dersom Den nordatlantiske strømmen stopper opp eller svekkes kraftig på grunn av global oppvarming.\n\nVestkysten av Norge vil sannsynligvis få\nla stå tom\nlavere\nlik\nhøyere\n  temperatur og  \nla stå tom\nmer\nnesten like mye\nmindre\n nedbør.",
    },
    {
      number: 10,
      title: "Hav og klima i og rundt Nord-Atlanteren",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "REA3043 Geofag 2\nOppgave 10\nOppgave 10 – Hav og klima i og rundt Nord-Atlanteren\n\nOppgave 4 av 6 til tema 2.\n\nDu skal svare på oppgaven nederst på siden.\n\nAMOC og sirkulasjonen i Nord-Atlanteren\n\nLes påstandene om AMOC og sirkulasjonen i Nord-Atlanteren i tabellen nedenfor.\n\nKryss av for om påstandene i tabellen er riktige eller feil.\n\nKryss av for om påstandene i tabellen er riktige eller feil.\n\n\tRiktig\tFeil\nGolfstrømmen går hele veien fra Karibia og inn i Norskehavet.\n\nAMOC er overflatestrømmer drevet av vind.\n\nGolfstrømsystemet er et vertikalt sirkulasjonssystem i havet.\n\nDe subtropiske gyrene drives av både storstilte vindsystemer og gravitasjonskrefter i havet.\n\nAMOC kan stoppe opp uten at den subtropiske gyren stopper opp.",
    },
    {
      number: 11,
      title: "Hav og klima i og rundt Nord-Atlanteren",
      kind: "skrive",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\nOppgave 11\nOppgave 11 – Hav og klima i og rundt Nord-Atlanteren\n\nOppgave 5 av 6 til tema 2.\n\nDu skal svare på oppgaven nederst på siden.\n\nDette er en skriveoppgave.\n\nAMOC og modeller\nKlimaforskere modellerer ulike tilstander av AMOC\n\nForskere har identifisert fire forskjellige stabile tilstander for AMOC:\n\nAvslått: ingen dypvannsdannelse i Nord-Atlanteren\nSvak: konveksjon hovedsakelig sør for 55° N\nDagens: dypvannsdannelse i Labradorhavet, Grønlandshavet og Norskehavet\nSterk: konveksjon som strekker seg inn i Arktis\n\nFigur 1 nedenfor presenterer to figursett som viser modellerte data for de fire tilstandene. \n\na, b, c og d viser maksimal isutbredelse (grå linje) og i tillegg hvor dypt konveksjonen i havet går, altså hvor dypt blandingslaget går.\ne, f, g og h viser styrken på AMOC i Sv (Sverdrup). Positive verdier betyr at strømmen er nordgående, mens negative verdier betyr at strømmen er sørgående.\nFigur 1 er hentet fra Willeit, M. og Ganopolski, A. (2024). Generalized stability landscape of the Atlantic meridional overturning circulation. Earth System Dynamics, 15(6), 1417–1434. https://doi.org/10.5194/esd-15-1417-2024 \n\nForskerne undersøkte hvordan AMOC reagerer på endringer i atmosfærisk CO2-konsentrasjon og ferskvannstilførsel til Nord-Atlanteren. Generelt fant de at\n\nhøyere CO2-nivåer favoriserer sterkere AMOC-tilstander\nøkt ferskvannstilførsel svekker AMOC\n\nFigur 2 nedenfor viser sammensettinger av CO2-nivåer og ferskvannstilførsel ved de ulike stabile tilstandene av AMOC. \n\nDen horisontale aksen viser styrken på ferskvannstilførselen, og den vertikale viser CO2-nivåene i atmosfæren. Fargekoden angir hvor sterke havstrømmer det er (gitt i Sv) i de ulike stabile AMOC-tilstandene. Prikken markerer ingen endring i ferskvannstilførsel og førindustriell verdi av CO2.\n\nFigur 2 er hentet fra Willeit, M. og Ganopolski, A. (2024). Generalized stability landscape of the Atlantic meridional overturning circulation. Earth System Dynamics, 15(6), 1417–1434. https://doi.org/10.5194/esd-15-1417-2024\nPDF\n\nNedenfor finner du fire påstander om de ulike AMOC-tilstandene. To av påstandene er sanne, og to er usanne.\n\nNår AMOC er avslått, er det ingen dypvannsdannelse i Nord-Atlanteren.\nEn sterk AMOC oppstår bare dersom CO2-nivåene er lavere enn 280 ppm.\nVed høye CO2-konsentrasjoner (over 400 ppm) krever en sterk AMOC-tilstand en større negativ ferskvannstilførsel for å være stabil enn de andre tilstandene.\nSjøisutbredelsen i Nord-Atlanteren er størst i den sterke AMOC-tilstanden.\nOppgave\n\nDu skal gjøre rede for de to påstandene som du mener er sanne. Begrunn svaret ditt med utgangspunkt i figurene ovenfor.",
    },
    {
      number: 12,
      title: "Hav og klima i og rundt Nord-Atlanteren",
      kind: "skrive",
      needsFigure: false,
      prompt: "REA3043 Geofag 2\nOppgave 12\nOppgave 12 – Hav og klima i og rundt Nord-Atlanteren\n\nOppgave 6 av 6 til tema 2.\n\nDu skal svare på oppgaven nederst på siden.\n\nDette er en skriveoppgave.\n\nAMOC og paleoklimatiske data\nKilder til paleoklimatiske data\nFigur 3 er hentet fra NOAA, https://www.noaa.gov/climate.\nPDF\nOppgave\n\nTa utgangspunkt i figur 3 ovenfor og vurder hvordan de tilgjengelige paleoklimatiske dataene kan brukes til å si noe om hvordan AMOC har variert gjennom ulike tider.",
    },
    {
      number: 13,
      title: "Tolkning og presentasjon av feltdata",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "REA3043 Geofag 2\nOppgave 13\nOppgave 13 – Tolkning og presentasjon av feltdata \n\nOppgave 1 av 5 til tema 3.\n\nDu skal svare på oppgaven nederst på siden.\n\nTolkning av CTD-data\nNB: Denne oppgaven er ikke fullstendig, men gir et bilde av hvordan oppgaven kan se ut. Det mangler aktuelle grafer.\n \n\nEn CTD er et elektronisk måleinstrument som brukes i havet for å måle grunnleggende egenskaper i vannsøylen. Navnet er en forkortelse for de engelske ordene Conductivity (konduktivitet/ledningsevne), Temperature (temperatur) og Depth (dybde).\n\nEt CTD-instrument har sensorer som måler\n\nkonduktivitet: vannets evne til å lede elektrisk strøm. Dette målet brukes til å beregne saltholdigheten (saliniteten) i vannet. Saltvann leder strøm bedre enn ferskvann.\ntemperatur: vanntemperaturen på ulike dybder\ntrykk: det hydrostatiske trykket i vannet. Dette trykket øker jevnt med dybden og brukes til å bestemme nøyaktig hvor dypt instrumentet er.\n\nEn CTD er et av de viktigste verktøyene innenfor oseanografi (havforskning). En CTD kan brukes fra forskningsskip, på bøyer som er forankrede eller frittflytende, eller på autonome farkoster.\n\nKlassen din har fått tilgang på data fra en CTD som har vært brukt på et havforskningstokt gjennom store deler av Atlanterhavet. Du har fått tildelt profilene nedenfor. \n\nPå eksamen vil det være en figur her med tre grafer som viser vertikale profiler av temperatur, salinitet og tetthet.\n\nI hvilken del av Atlanterhavet er disse dataene samlet inn?\n\nOppgave\nKlikk på sirkelen som viser hvor CTD-dataene er samlet inn.",
    },
    {
      number: 23,
      title: "Havvindutbygging i Nordsjøen",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "REA3043 Geofag 2\nOppgave 23\nOppgave 23 – Havvindutbygging i Nordsjøen\n\nOppgave 6 av 8 til tema 4.\n\nDu skal svare på oppgaven nederst på siden.\n\nNaturfarer og ekstremvær i Nordsjøen\n\nDette er en plassholder for en oppgave. Oppgaven er ikke ferdiglaget. Plassholderen er bare for å vise tema og oppgavetyper. \n\nEn interaktiv oppgave om hvordan ekstremvær kan være en utfordring for infrastruktur knyttet til havvindparker\nalternativ 1\nalternativ 2\nalternativ 3",
    },
    {
      number: 24,
      title: "Havvindutbygging i Nordsjøen",
      kind: "skrive",
      needsFigure: false,
      prompt: "REA3043 Geofag 2\nOppgave 24\nOppgave 24 – Havvindutbygging i Nordsjøen\n\nOppgave 7 av 8 til tema 4.\n\nDu skal svare på oppgaven nederst på siden.\n\nDette er en skriveoppgave.\n\nVærvarsling\n\nDette er en plassholder for en oppgave. Oppgaven er ikke ferdiglaget. Plassholderen er bare for å vise tema og oppgavetyper. \n\nSkriveoppgave om værvarsling i tilknytning til utvinning av energi i Nordsjøen",
    },
    {
      number: 25,
      title: "Havvindutbygging i Nordsjøen",
      kind: "skrive",
      needsFigure: false,
      prompt: "REA3043 Geofag 2\nOppgave 25\nOppgave 25 – Havvindutbygging i Nordsjøen\n\nOppgave 8 av 8 til tema 4.\n\nDu skal svare på oppgaven nederst på siden.\n\nDette er en skriveoppgave.\n\nBærekraftig energiutvinnelse\n\nDette er en plassholder for en oppgave. Oppgaven er ikke ferdiglaget. Plassholderen er bare for å vise tema og oppgavetyper. \n\nSkriveoppgave om bærekraftig utvinnelse av energi.",
    },
  ],
};
