import type { ExamSet } from "../types";

export const h2023: ExamSet = {
  slug: "h2023",
  label: "Høst 2023",
  season: "H",
  year: 2023,
  kind: "eksamen",
  complete: true,
  officialUrl: "https://kandidat.udir.no/epsmateriell/eksamen?fagkode=REA3043&malform=nb-NO&semester=H&ar=2023&eksamensdeltype=Eksamen",
  themes: [
    "Kategori 1",
    "Kategori 2",
    "Kategori 3",
  ],
  tasks: [
    {
      number: 1,
      title: "Klimaendringer og lavere albedo",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "REA3043 Geofag 2\nOppgave 1\nOppgave 1: Klimaendringer og lavere albedo\nKryss av for den viktigste årsaken til at klimaendringer kan føre til en lavere global albedo\nmengden hvite skyer øker\nhavet utgjør en enda større del av jordoverflaten\ndet blir mer negative tilbakekoblinger som involverer is og snø på landjorden\npermafrosten tiner i Arktis",
    },
    {
      number: 2,
      title: "Luftens tetthet",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "REA3043 Geofag 2\nOppgave 2\nOppgave 2: Luftens tetthet\nSett kryss ved den viktigste faktoren som bestemmer luftens tetthet\nendring i kjemisk sammensetning med høyde\nmengde luftfuktighet\nvariasjon i temperatur\nendring i trykk med høyde",
    },
    {
      number: 3,
      title: "Ozonlaget",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\nOppgave 3\nOppgave 3: Ozonlaget\n\nFiguren nedenfor viser utviklingen av ozonlaget på tre ulike breddegrader, i ulike høyder over bakken, fra år 2000 til 2020. \n\nTil hver breddegrad tilhører det fire ulike grafer og et skravert område. Den tykke rosa grafen viser gjennomsnitt av observerte data, mens de tynne rosa graflinje viser usikkerhetsområdet til de observerte dataene. Den tykke sorte grafen viser gjennomsnitt av simulerte data, mens det skraverte området viser usikkerhetsområdet til de simulerte dataene. Grafene viser prosentvis endring per 10 år (førsteaksen). Verdiene langs andreaksen er gitt som trykk i hPa på venstre siden og høyde over havet i km på høyre siden.\nVis bildetekst\nKryss av for riktig påstand\nUtviklingen har vært negativ fordi det er blitt mer ozon ved bakken på alle breddegrader.\nUtviklingen har vært positiv fordi det er blitt mindre ozon fra ca. 30 til 45 kilometer over bakken på alle breddegrader.\nUtviklingen har vært positiv fordi det har blitt mer ozon fra ca. 30 til 45 kilometer over bakken på alle breddegrader.\nUtviklingen har vært negativ fordi det har blitt mindre ozon ved bakken på alle breddegrader.",
    },
    {
      number: 4,
      title: "Skyer og temperatur",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "REA3043 Geofag 2\nOppgave 4\nOppgave 4: Skyer og temperatur\nHvorfor er stille og klare netter vanligvis kaldere enn stille og overskyede netter?\nSkyene har absorbert infrarød stråling i løpet av dagen og emitterer det til bakken om natten.\nOm natten har vi en negativ strålingsbalanse som betyr at utstrålingen fra bakken er større enn innstrålingen fra solen. Skyer vil gjøre strålingsbalansen mindre negativ.\nSkyene fører til en positiv strålingsbalanse fordi de reflekterer stråling tilbake til jorden.",
    },
    {
      number: 5,
      title: "Solenergi",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\nOppgave 5\nOppgave 5: Solenergi\n\nI Norge er det store forskjeller på hvor sterk solinnstrålingen er i løpet av året, og det er store forskjeller mellom ulike deler av landet. På kartet nedenfor kan du se solinnstråling mot en horisontal flate i henholdsvis januar og juli.\n\nKilde: https://gemini.no/2018/03/hvor-godt-virker-egentlig-solceller-i-nordisk-klima/solinnstraling/\nBruk kartet nedenfor og klikk på det stedet i Norge som har mest solinnstråling totalt i løpet av året.",
    },
    {
      number: 6,
      title: "Solenergi",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "REA3043 Geofag 2\nOppgave 6\nOppgave 6: Solenergi\n\nEn bolig ligger et sted der solinnstrålingen per dag er 800 Wh/m2 i gjennomsnitt gjennom året. Familien som bor i boligen, har et behov for elektrisitet som er ca. 16 000 kWh totalt i året.\n\nKan familien klare seg med bare solenergi dersom den totale flaten de kan legge solceller på, utgjør 25 m2?\nNei, det blir for lite, de må kjøpe elektrisitet i tillegg.\nJa, det blir akkurat nok.\nJa, det blir i tillegg mye til overs som de kan selge.",
    },
    {
      number: 7,
      title: "Tidevannskraftverk",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "REA3043 Geofag 2\nOppgave 7\nOppgave 7: Tidevannskraftverk\nHvilke beskrivelser av et tidevannskraftverk er riktige?\n\nDu kan velge maksimalt 2 alternativer\n\net kraftverk som utnytter bevegelsesenergien i vann som strømmer fra høyvann til lavvann, og omvendt\net kraftverk som utnytter høydeforskjellen mellom flo og fjære\net kraftverk som utnytter bevegelsesenergien i vann som strømmer fra elver og bekker ut i havet\net kraftverk som utnytter bevegelsesenergien i bølger",
    },
    {
      number: 8,
      title: "Havnivåstigning",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\nOppgave 8\nOppgave 8: Havnivåstigning\n\nFiguren nedenfor er basert på satellittmålinger og modelldata fra år 2003 til 2009 og viser hvordan havnivåendringene er fordelt på kloden. Verdiene viser hvor store endringene er i gjennomsnitt per år. Endringene skyldes smeltende isbreer og iskapper. Den tykke hvite linjen viser den globale middelverdien på 1,0 mm per år.\n\nSatellittmålt (fra GRACE) og modellert fordeling av endret havnivå grunnet smeltende breer og iskapper mellom år 2003 og 2009. Tykk hvit linje viser global middelverdi på 1,0±0,4 mm per år. Omarbeidet figur 1 fra Riva mfl., Geophys. Res. Lett. (2010).\n \n\nHvilke påstander er sanne og usanne?\n\nDu må lage opptil 4 koblinger\n\nHvilke påstander er sanne og usanne?\n\n\tSant\tUsant\nHavnivået synker rundt kysten av Grønland.\n\nHavnivået stiger mest nær ekvator.\n\nHavnivået rundt kysten av Grønland stiger siden innlandsisen smelter.\n\nInnlandsisen i Antarktis smelter mest i øst, nærmere Australia, siden vi her får en havnivåstigning, mens den smelter minst i vest, nærmere Sør-Amerika, hvor vi ser at havnivået synker.",
    },
    {
      number: 9,
      title: "Overflatetemperatur i havet ved Sør-Afrika",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\nOppgave 9\nOppgave 9: Overflatetemperatur i havet ved Sør-Afrika\n\nKartet nedenfor viser Afrika, med et eksempel på hvordan overflatetemperaturen i havet kan variere mellom østsiden og vestsiden av Sør-Afrika på samme dag. I dette eksempelet er det 18 ºC på vestsiden og 28 ºC på østsiden.\n\n \n\nKilde: Utdanningsdirektoratet\n\n \n\n \n\nI teksten under skal du velge riktige ord fra menyene slik at teksten blir geofaglig korrekt. \n\nHovedgrunnen til denne forskjellen i vanntemperatur mellom vestsiden og østsiden av Sør-Afrika er\nla stå tom\nhavstrømmer\nluftstrømmer\n. På vestsiden kommer det en\nla stå tom\nkald\nvarm\n strøm\nla stå tom\nfra nord\nfra sør\n, mens det på østsiden kommer en\nla stå tom\nkald\nvarm\nstrøm\nla stå tom\nfra nord\nfra sør\n.",
    },
    {
      number: 10,
      title: "Kilder for å rekonstruere paleoklima",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "REA3043 Geofag 2\nOppgave 10\nOppgave 10: Kilder for å rekonstruere paleoklima\nHvilke av disse kildene kan vi bruke for å rekonstruere klimaet som var i Norge for 2 000 000 år siden?\n\nDu kan velge maksimalt 2 alternativer\n\nIskjerner\nPollen\nHavbunnssedimenter\nBergarter og fossiler\nTreringer\nHistoriske kilder\nLøsmasser på land",
    },
    {
      number: 11,
      title: "Flyruter og polarjetstrømmen",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\nOppgave 11\nOppgave 11: Flyruter og polarjetstrømmen\n\nDe to figurene nedenfor viser hendelser som skjedde samme dag.Den første figuren viser flyruter mellom Europa og Nord-Amerika. Disse flyrutene er av forskjellige årsaker forhåndsbestemte. Flyene flyr i en høyde på ca. 10 000–12 000 moh., og de drar stor nytte av medvind. Figuren inneholder en del tallkombinasjoner og punkter i ulike farger. Tallkombinasjonene er ikke relevante for denne oppgaven.\n\nFiguren viser flyruter mellom Nord-Amerika og Europa.\nKilde: https://flightplandatabase.com/nav/NATS. Hentet 31. mars 2023\nVis bildetekst\n\nFiguren nedenfor viser polarjetstrømmen over Nord-Atlanteren, på samme dag som bildet ovenfor. Rød farge indikerer høy vindhastighet.\n\nFiguren viser polarjetstrømmen. Kilde: https://www.netweather.tv/charts-and-data/jetstream. Hentet 31. mars 2023\nVis bildetekst\nKryss av for riktig påstand\nBåde flyrutene A og flyrutene B går fra øst mot vest.\nFlyrutene A går fra øst mot vest, og flyrutene B går fra vest mot øst.\nBåde flyrutene A og flyrutene B går fra vest mot øst.\nFlyrutene A går fra vest mot øst, og flyrutene B går fra øst mot vest.",
    },
    {
      number: 12,
      title: "Varmeekstremer over land",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\nOppgave 12\nOppgave 12: Varmeekstremer over land\nFiguren nedenfor viser hvordan intensiteten og hyppigheten av hetebølger forventes å øke med økende oppvarming.\n \nFiguren er hentet fra Miljødirektoratet, som har oversatt en figur fra FNs klimapanels sjette hovedrapport. Kilde: https://www.miljodirektoratet.no/ansvarsomrader/klima/fns-klimapanel-ipcc/dette-sier-fns-klimapanel/sjette-hovedrapport/ekstremvar/. Hentet 11. april 2023\nHvilke påstander er sanne og usanne?\n\nDu må lage opptil 4 koblinger\n\nFiguren nedenfor viser hvordan intensiteten og hyppigheten av hetebølger forventes å øke med økende oppvarming.\n \nFiguren er hentet fra Miljødirektoratet, som har oversatt en figur fra FNs klimapanels sjette hovedrapport. Kilde: https://www.miljodirektoratet.no/ansvarsomrader/klima/fns-klimapanel-ipcc/dette-sier-fns-klimapanel/sjette-hovedrapport/ekstremvar/. Hentet 11. april 2023\nHvilke påstander er sanne og usanne?\n\tSant\tUsant\nI dag er hetebølgene i gjennomsnitt 1,2 ºC varmere enn de var før menneskelig påvirkning.\n\nEn 50-årig hendelse er noe som skjedde en gang per 50 år i perioden 1850–1900.\n\nVed 2,6 ºC global oppvarming forventes vi å få 10-årige hendelser med 5,6 års mellomrom.\n\nVed 4 ºC global oppvarming vil 50-årige hendelser skje i omtrent 39 av 50 år.",
    },
    {
      number: 13,
      title: "Iskjerneboring på Grønland",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\nOppgave 13\nOppgave 13: Iskjerneboring på Grønland\n\nKartet til venstre viser isens flytemønster, og kartet til høyre viser høyden over havet på Grønland.\n\n \n\nHentet 30. mai 2023 fra https://earthenvironmentcommunity.nature.com/posts/decoding-traces-of-past-ice-stream-activity-in-the-northeast-greenland-ice-sheet\nHentet 30. mai 2023 fra https://www.researchgate.net/figure/Greenland-station-location-map-also-showing-elevation-contours_fig1_201169651\n   \nHvor mener du vil være det beste stedet å bore ut en iskjerne hvis isen skal være så gammel som mulig?\n \nved stedet som er markert med stjerne\nved stedet som er markert med firkant\nved stedet som er markert med trekant\nved stedet som er markert med sirkel",
    },
    {
      number: 14,
      title: "Paleoklima og Grønland",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\nOppgave 14\nOppgave 14: Paleoklima og Grønland\n\nFiguren nedenfor viser variasjonen i forholdet mellom oksygenisotopene 18O og 16O relativt til isdybden i en iskjerneprøve fra Grønland. \n\nFiguren er delt i to, der øverste del ligger til venstre, og nederste del ligger til høyre. \n\nDybdeaksen (gitt i km) finnes ytterst til høyre og venstre i figuren, mens aldersaksen (gitt i 1000 år) finnes i midten.\n\n \n\nKilde: Hentet 30.mai 2023 fra http://www2.ocean.washington.edu/oc540/lec01-31/?fbclid=IwAR1AZ0zfB11tNFM-5oIeTBa9JxWmO3uZlWGorzUWKK8eTDlVaeqJDVv0Smo\n   \n \nPå hvilken dybde i isen kan vi finne igjen siste istid?\n på 500–1500 meters dyp\npå 1900–3000 meters dyp\npå 1600–2800 meters dyp\npå 1750–2900 meters dyp",
    },
    {
      number: 15,
      title: "CO2-fluks mellom havet og atmosfæren",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\nOppgave 15\nOppgave 15: CO2-fluks mellom havet og atmosfæren\n\nFiguren nedenfor består av to kart.\n\nDet øverste kartet (a) viser fluksen (utvekslingen) av CO2 fra havet til atmosfæren, der blåfarge viser at CO2 går fra atmosfæren til havet, og rødfarge viser det motsatte. Dette kartet er basert på referanseåret 2000.\n\nDet nederste kartet (b) viser hvor store variasjoner i fluksen det har vært de siste 30 årene.\n\n \n\nKilde til figuren: \"Variability of global net sea–air CO2 fluxes over the last three decades using empirical relationships\". Tellus B, 62, 352–368. Hentet 3. mars 2023 fra https://b.tellusjournals.se/articles/10.1111/j.1600-0889.2010.00498.x\n \nUnder finner du en rekke påstander som handler om CO2, hav og atmosfære. Figuren ovenfor kan være til hjelp, men ikke til alle påstandene.  \n \nHvilke påstander under er sanne og usanne?\n\nDu må lage opptil 4 koblinger\n\nUnder finner du en rekke påstander som handler om CO2, hav og atmosfære. Figuren ovenfor kan være til hjelp, men ikke til alle påstandene.  \n \nHvilke påstander under er sanne og usanne?\n\tSant\tUsant\nLøseligheten til CO2 er høyest i varmt vann.\n\nHvis det går CO2 fra havet til atmosfæren, så kan en årsak være at konsentrasjonen av CO2 er høyere i havet enn i atmosfæren.\n\nDe største variasjonene finner vi bare i områder der CO2 går fra atmosfæren til havet.\n\nHavets opptak av CO2 har redusert den globale oppvarmingen.",
    },
    {
      number: 16,
      title: "Dannelse av snøkrystaller",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\nOppgave 16\nOppgave 16: Dannelse av snøkrystaller\n \n \nHva kalles typen snøkrystaller som er vist på bildet, og hvordan er de dannet?\nKilde: Utdanningsdirektoratet\nSnøkrystallene kalles begerkrystaller og dannes på overflaten i svært kaldt vær.\nSnøkrystallene kalles overflaterim og dannes ofte i varmt og fuktig vær. \nSnøkrystallene kalles fokksnø og dannes ofte under kraftig vind.\nSnøkrystallene kalles rimkrystaller og dannes ofte under kalde og klare netter.",
    },
    {
      number: 17,
      title: "Katabatiske vinder",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "REA3043 Geofag 2\nOppgave 17\nOppgave 17: Katabatiske vinder\nMerk av riktig alternativ:\nKatabatiske vinder er varme og fuktige vinder som oppstår under monsunen.\nKatabatiske vinder er kalde og tørre vinder som oppstår i forbindelse med kraftige lavtrykk.\nKatabatiske vinder er kraftige fallvinder som oppstår som et resultat av gravitasjon og høydeforskjeller.\nKatabatiske vinder er kraftige fallvinder som oppstår i forbindelse med kraftige tordenstormer.",
    },
    {
      number: 18,
      title: "Tropiske sykloner",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\nOppgave 18\nOppgave 18: Tropiske sykloner\n\nFiguren viser en kraftig tropisk syklon i det vestlige Stillehavet. Det er tre piler merket med tall, som viser tre tenkte baner for denne syklonens videre forflytning.\n\nHentet fra https://earth.nullschool.net/\nKryss av for den banen som det er mest sannsynlig at syklonen følger:\nbane 1\nbane 2\nbane 3",
    },
    {
      number: 19,
      title: "Utvikling av et værsystem",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "REA3043 Geofag 2\nOppgave 19\nOppgave 19: Utvikling av et værsystem\nDisse tre analysekartene viser alle samme værsystem, men på litt ulike tidspunkter. Analysekartene står i tilfeldig rekkefølge.\nHentet fra https://www.met.no/vaer-og-klima/meteorologens-analysekart\nHva er en sannsynlig rekkefølge på disse kartene?\nKart 1 viser det tidligste tidspunktet, kart 2 det neste, og så viser kart 3 det seneste tidspunktet.\nKart 2 viser det tidligste tidspunktet, kart 3 det neste, og så viser kart 1 det seneste tidspunktet.\nKart 3 viser det tidligste tidspunktet, kart 1 det neste, og så viser kart 2 det seneste tidspunktet.\nKart 1 viser det tidligste tidspunktet, kart 3 det neste, og så viser kart 2 det seneste tidspunktet.\nKart 2 viser det tidligste tidspunktet, kart 1 det neste, og så viser kart 3 det seneste tidspunktet.\nKart 3 viser det tidligste tidspunktet, kart 2 det neste, og så viser kart 1 det seneste tidspunktet.",
    },
    {
      number: 20,
      title: "Tidevann",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "REA3043 Geofag 2\nOppgave 20\nOppgave 20: Tidevann\nTidevann oppstår som følge av\nstormsentre og kraftig vind som blåser inn mot kysten\nklimaendringenes påvirkning på havnivået\nanomalier i jordens gravitasjonsfelt\nvekselvirkninger mellom jordens, månens og solens gravitasjonskrefter",
    },
    {
      number: 21,
      title: "Varmeutveksling mellom hav og atmosfære",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\nOppgave 21\nOppgave 21: Varmeutveksling mellom hav og atmosfære\n\nI denne oppgaven finner du fem figurer. Det er tre deloppgaver som skal besvares direkte i tekstboksene nedenfor. Det kan være lurt å lese gjennom alle deloppgavene før du begynner å svare. \n\nFigur 1: Varmeutveksling\nFigur 2: Atmosfæretemperatur\nFigur 3: Havtemperatur\nFigur 4: Vindstyrke\nFigur 5: Fuktighet\n\nFigur 1 viser netto varmeutveksling mellom havet og atmosfæren. I denne figuren betyr positive verdier at varmen går fra atmosfære til hav, og negative verdier betyr at varmen går fra hav til atmosfære.\n\n \n\nDe svarte boksene markerer områder med vestlige grensestrømmer (vestlig forsterkning av havstrømmer).\n\nGS = Golfstrømmen\n\nKOE = Kuroshiostrømmen\n\nARC = Agulhas-strømmen\n\nEAC = Østaustralske strøm\n\nBMC = Brasilstrømmen og Falklandsstrømmen møtes\n\n \n\n \n\nKilde: Hentet den 15. april 2023 fra https://oaflux.whoi.edu/heat-flux/heat-flux-plots/ \nForrige\nPDF\n\tSide 1 av 5\nNeste\na)\nTa utgangspunkt i figur 1.\nBeskriv hvor vi finner områder med størst varmeutveksling mellom hav og atmosfære, både varmeutveksling fra hav til atmosfære og omvendt.",
    },
    {
      number: 22,
      title: "Klimaendringer, permafrost og metan",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "REA3043 Geofag 2\nOppgave 22\nOppgave 22: Klimaendringer, permafrost og metan\n\na) Gjør rede for ulike faktorer som påvirker utbredelsen av permafrost.\n\nb) Gjør rede for hvorfor forskerne er svært bekymret for strålingspådrivet som metan utgjør.\n\nc) Forklar hvordan permafrost kan brukes som en klimaindikator.\n\nd) Det frigjøres hele tiden metan fra myrer som ikke ligger i permafrostområder. Forklar hvorfor vi er mindre bekymret for dette metanet enn vi er for metan som frigjøres ved tining av myrer i permafrostområder, sett i lys av global oppvarming.\n\ne) Vurder mulige bærekraftige løsninger for å redusere utslipp fra forskjellige kilder til metan.\n\nPå neste side skal du laste opp svarene til oppgave 22.\n\nJeg bekrefter at jeg besvarer denne oppgaven i et dokument som jeg laster opp i den siste oppgaven.",
    },
  ],
};
