import type { ExamSet } from "../types";

export const h2024: ExamSet = {
  slug: "h2024",
  label: "Høst 2024",
  season: "H",
  year: 2024,
  kind: "eksamen",
  complete: false,
  officialUrl: "https://kandidat.udir.no/epsmateriell/eksamen?fagkode=REA3043&malform=nb-NO&semester=H&ar=2024&eksamensdeltype=Eksamen",
  themes: [
    "Kategori 1",
    "Kategori 2",
    "Kategori 3",
  ],
  tasks: [
    {
      number: 1,
      title: "farevarsel om vind",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\nOppgave 1 – farevarsel om vind\nOppgave 1 – farevarsel om vind\n\nFiguren nedenfor viser et farevarsel for sterk vind i Sør-Norge fra Meteorologisk institutt.\n\n \n\n \n\nHvilket av disse tre værkartene fra yr.no passer best til farevarselet i kartet ovenfor? \nKlikk hvor som helst i det riktige værkartet; kart A, B eller C.",
    },
    {
      number: 2,
      title: "jordrotasjon",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\nOppgave 2 – jordrotasjon\nOppgave 2 – jordrotasjon\n\nJorden roterer om sin egen akse. \n\nNedenfor finner du ulike påstander om hvordan jordrotasjonen påvirker hav- og luftstrømmene. \n\n \n\n1. Havstrømmer bøyes av til venstre på den sørlige halvkule.\n\n2. Luftstrømmer bøyes av til venstre på den nordlige halvkule.\n\n3. Luftstrømmer bøyes av til høyre på den sørlige halvkule.\n\n4. Jordrotasjonens påvirkning på hav- og luftstrømmene er sterkest ved ekvator.\n\n5. Jordrotasjonens påvirkning på hav- og luftstrømmene er større jo nærmere polene man kommer.\n\n6. Når vind blåser fra nord mot sør på den nordlige halvkule, bøyes vindene av mot venstre. \n\nMarker alternativet som er riktig:\n\nPåstand 1 og 5 er sanne.\nPåstand 1 og 2 er sanne.\nPåstand 3 og 6 er sanne.\nPåstand 3 og 4 er sanne.",
    },
    {
      number: 3,
      title: "lavtrykkssenter",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\nOppgave 3 – lavtrykkssenter\nOppgave 3 – lavtrykkssenter\nSatellittbildet nedenfor viser situasjonen i Nord-Atlanteren onsdag 6. mars. Du skal finne lavtrykkssenteret på dette bildet.\nKlikk i bildet nærmest mulig sentrum av lavtrykkssenteret.\n\nBildekilde: https://www.met.no/vaer-og-klima/satellittbilder",
    },
    {
      number: 4,
      title: "massetetthet i havet",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\nOppgave 4 – massetetthet i havet\nOppgave 4 – massetetthet i havet\n\nFiguren nedenfor er en tetthetsprofil som viser hvordan massetettheten i havet kan variere med dybden.\n\n      \n\nMarker de to alternativene som viser sannsynlige årsaker til at massetettheten varierer relativt lite fra 500 meter og dypere:\n\nDu kan velge maksimalt 2 alternativer\n\nDet er svært liten variasjon i saliniteten fra 500 meter og dypere. \nDet er svært liten variasjon i temperaturen fra 500 meter og dypere.\nVannet er kraftig komprimert på dyp større enn 500 meter.\nSollyset når ikke dypere enn 500 meter.",
    },
    {
      number: 5,
      title: "nedbør",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\nOppgave 5 – nedbør\nOppgave 5 – nedbør\n\nFiguren nedenfor viser global fordeling av total årsnedbør (i centimeter) i 2022, med tilhørende fargeskala. \n\n  \n\nAvgjør om påstanden nedenfor er sann eller usann:\n\n«I 2022 var det mye mer nedbør langs den intertropiske konvergenssonen enn langs polarfronten.»\n\nVelg riktig alternativ:\nPåstanden er sann.\nPåstanden er usann.",
    },
    {
      number: 6,
      title: "vindretning",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\nOppgave 6 – vindretning\nOppgave 6 – vindretning\n\nVideoen nedenfor viser vindretningen et sted på den sørlige halvkule. \n\n \n\nspill av\n00:00\nslå av lyd\nfullskjerm\nSPILL AV\nmediaspiller\n\nVideo fra https://earth.nullschool.net/, hentet 8.3.2024.\n\nMarker det alternativet som viser hvilket trykksenter vi ser i den midtre del av videoen:\nLavtrykk\nHøytrykk",
    },
    {
      number: 7,
      title: "temperatur ved bakken ut fra satellittbilde",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\nOppgave 7 – temperatur ved bakken ut fra satellittbilde\nOppgave 7 – temperatur ved bakken ut fra satellittbilde\n\nNedenfor ser du et satellittbilde som viser skydekket i nordlige deler av Atlanterhavet. I bildet er det markert tre oransje bokser som markerer områder på jordoverflaten. Se bort fra at det noen steder er land og noen steder er hav. \n\nKlikk på den boksen som viser området som sannsynligvis har høyest overflatetemperatur av disse tre:\n\nBildekilde: https://www.met.no/vaer-og-klima/satellittbilder",
    },
    {
      number: 8,
      title: "tidevannskraft",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "REA3043 Geofag 2\nOppgave 8 – tidevannskraft\nOppgave 8 – tidevannskraft\n\nAlle energikilder har noen fordeler og ulemper, og noen av dem er listet opp nedenfor. Du skal avgjøre hvilke av disse som stemmer om tidevannskraft:\n\nUstabil\nForutsigbar\nFremdeles ganske dyr teknologi\nGrundig utviklet og billig teknologi\nPåvirker ikke flora og fauna\nHar noe påvirkning på flora og fauna\nKryss av for riktig alternativ:\nPåstand 1, 3 og 5 stemmer om tidevannskraft.\nPåstand 2, 3 og 6 stemmer om tidevannskraft.\nPåstand 1, 4 og 6 stemmer om tidevannskraft.\nPåstand 2, 4 og 5 stemmer om tidevannskraft.",
    },
    {
      number: 10,
      title: "strålingsbalanse",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\nOppgave 10 – strålingsbalanse\nOppgave 10 – strålingsbalanse\n\nFiguren nedenfor viser netto stråling (strålingsbalansen) i W/m² i september 2008. \n\n \n\nKilde: NASA. Hentet 9.3.24 fra https://earthobservatory.nasa.gov/features/EnergyBalance\n   \n\nDu skal bruke figuren for å avgjøre hvilke av påstandene 1–4 som er riktige:\n\n1. Områdene langs ekvator mottar mer stråling enn de sender ut.\n\n2. Polområdene sender ut mer stråling enn de mottar.\n\n3. Områdene langs ekvator sender ut mer stråling enn de mottar.\n\n4. Polområdene mottar mer stråling enn de sender ut.\n\nMarker alternativet der begge påstandene er riktige:\nPåstand 1 og 4\nPåstand 2 og 3\nPåstand 3 og 4\nPåstand 1 og 2",
    },
    {
      number: 13,
      title: "konsekvenser av global oppvarming",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "REA3043 Geofag 2\nOppgave 13 – konsekvenser av global oppvarming\nOppgave 13 – konsekvenser av global oppvarming\n\nTo kjente konsekvenser av global oppvarming er temperaturøkning i atmosfæren og havnivåstigning. Havet har per i dag absorbert over 90 prosent av den ekstra energien som er tilført klimasystemet.\n\nMarker alternativet med den mest sannsynlige årsaken til at temperaturøkningen i atmosfæren er betydelig raskere enn havnivåstigningen.\nDet er bare de øverste 25 meterne av havet som har fanget opp den ekstra energien og utvidet seg.\nDen ekstra energien fordeles ned i dypet og påvirker ikke havnivået.\n93 prosent av stigningen i havnivå kommer av smelting av isbreer og innlandsiser. Bare 7 prosent kommer fra økt temperatur i havet. \nHavnivåstigningen er koblet mot prosesser som er mye tregere enn temperaturøkningen i atmosfæren.",
    },
    {
      number: 17,
      title: "vindkraft og energi",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "REA3043 Geofag 2\nOppgave 17 – vindkraft og energi\nOppgave 17 – vindkraft og energi\n\nEnergien i vind avhenger av vindfarten opphøyd i tredje potens. \n\n \n𝐸\n=\n𝑘\n⋅\n𝑣\n3\n\nder E er energien, k er en konstant som avhenger av tetthet, areal og tid, og v er vindfarten.\n\nMarker alternativet som gjør denne setningen riktig: \nEn økning i vindfart fra 5 m/s til 10 m/s vil medføre at energien ...\n… er 2 ganger så stor (dobling).\n… er 4 ganger så stor (firedobling).\n… er 8 ganger så stor (åttedobling).\n… er 16 ganger så stor (sekstendobling).",
    },
    {
      number: 20,
      title: "sedimentkjerne fra havbunn",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\nOppgave 20 – sedimentkjerne fra havbunn\nOppgave 20 – sedimentkjerne fra havbunn \n\nI denne oppgaven skal du jobbe med en sedimentkjerne fra grensen mellom Norskehavet og Barentshavet. Sedimentkjernen har fått navnet GS14-190-01PC. \n\n \n\nFigur 1 viser kart i ulik målestokk hvor plasseringen for kjerneprøven er markert. Figur 1a viser også to andre sedimentprøvestasjoner, vi skal ikke jobbe med disse i denne oppgaven.\n\nFigur 2 viser ulike proxydata fra sedimentkjernen GS14-190-01PC.\n\nFigur 3 viser fordeling av planktonmarkører ved ulike typer sjøisdekke i nordområdene. \n\nFigur 1: Kart over forskningsområdet\nFigur 2: Proxydata fra sedimentkjernen\nFigur 3: Planktonmarkører knyttet til ulike sjøisdekker\n\nFigur 1 viser et kart over forskningsområdet. \n\n1a viser dagens topografi og geografi. Stasjoner hvor det er samlet inn havbunnsprøver, er markert med grønne stjerner. Den aktuelle kjerneprøven (GS14-190-01PC) i denne oppgaven er lokalisert i den røde firkanten markert med fig. 1b. Den beige linjen viser maksimal utbredelse av innlandsisen under Weichsel-istiden.\n\n1b er zoomet mer inn mot GS14-190-01PC og viser mer detaljert batymetri (havdybde). Den beige linjen nær 500 meters dyp viser maksimal utbredelse av innlandsisen under Weichsel-istiden. Noe informasjon i figuren er fjernet fordi det ikke er aktuelt i denne oppgaven.\n\nFiguren er hentet 22. juni 2024 hos Knies, J., Köseoğlu, D., Rise, L., Baeten, N., Bellec, V. K., Bøe, R., … Belt, S. T. (2018). «Nordic Seas polynyas and their role in preconditioning marine productivity during the Last Glacial Maximum». Nature Communications, 9(1), 3959. https://doi.org/10.1038/s41467-018-06252-8 og er redigert av Utdanningsdirektoratet.\n\nForrige\nPDF\n\tSide 1 av 3\nNeste\n\nDu ser i figur 1a og b at kjerneprøven er tatt like utenfor der det var maksimal isutbredelse under siste istid (LGM). \n\na) Gjør rede for hva forskere kan finne ut ved å ta en sedimentprøve fra havbunnen fra posisjonen der sedimentprøve GS14-190-01PC er hentet.",
    },
    {
      number: 21,
      title: "værsystemer og konsekvenser av klimaendringer",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\nOppgave 21 – værsystemer og konsekvenser av klimaendringer\nOppgave 21 – værsystemer og konsekvenser av klimaendringer\n\na) Du står ved foten av et fjell og kjenner at det blåser ned fra fjellet. Bruk din geofaglige kompetanse til å gjøre rede for om dette er katabatisk vind eller fønvind. \n\n \n\nb) Nedenfor ser du figur 1b fra artikkelen i forberedelsesdelen, oversatt til norsk. Ta utgangspunkt i situasjonen som er skissert i figur 1b. Anta at vi befinner oss i Sør-Norge. Vurder hvordan en global oppvarming vil påvirke prosessene som inngår i situasjonen. \n\n \n\nIllustrasjon av klassisk fønvind-situasjon. Figuren hentet fra forberedelsesartikkelen, oversatt til norsk av Utdanningsdirektoratet. Kilde: Mamen, J. (2023). Fønvind: Når «sommeren» avlegger et besøk vinterstid. Naturen, 147(2), 95–102. https://doi.org/10.18261/naturen.147.2.6\n \n\nc) Ifølge forberedelsesartikkelen vil klimaendringene kunne endre lavtrykksbanene. Gjør rede for mulige årsaker til at lavtrykkene tar en nordligere bane når det er lite is i Arktis. \n\nKart 1: Dette kartet viser hvor Jostedalsbreen (merket med tallet 1) og Sunndalsøra (merket med tallet 2) ligger i forhold til hverandre.\n\n \n\nHentet fra https://norgeskart.no\n   \n\nKart 2: Dette kartet viser topografien rundt Jostedalsbreen. \n\n \n\nHentet fra http://norgeskart.no\n \n\nd) Studer faren for snøskred i fjellområdene rundt Jostedalsbreen 2. januar 2020 under fønvindsituasjonen som er beskrevet i forberedelsesartikkelen. Du kan anta at vindretningen er lik i hele området. Vurder i hvilke områder snøskredfaren øker betydelig i løpet av 2. januar 2020.\n\nJeg bekrefter at jeg besvarer denne oppgaven i et dokument som jeg laster opp i den siste oppgaven.",
    },
  ],
};
