import type { ExamSet } from "../types";

export const h2025: ExamSet = {
  slug: "h2025",
  label: "Høst 2025",
  season: "H",
  year: 2025,
  kind: "eksamen",
  complete: false,
  officialUrl: "https://kandidat.udir.no/epsmateriell/eksamen?fagkode=REA3043&malform=nb-NO&semester=H&ar=2025&eksamensdeltype=Eksamen",
  fasitSource: "udir",
  themes: [
    "Interaktive oppgaver",
    "Skriveoppgaver",
  ],
  tasks: [
    {
      number: 1,
      title: "strålingsbalansen",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\nOppgave 1\nOppgave 1 – strålingsbalansen\n\nFiguren nedenfor illustrerer strålingsbalansen ved jordoverflaten. Den viser at det faktisk er energibalanse.\n\nKilde: Bjerknes Centre for Climate Research. Hentet 30. april 2025 fra https://bjerknes.uib.no/laer-om-klima-2/faktasider/drivhuseffekten-og-jordens-klima.\nHvilken av påstandene nedenfor stemmer overens med det vi ser i figuren?\nDet kommer prosentvis like mye energi inn fra solen som det sendes ut fra jordoverflaten.\nDet kommer prosentvis like mye energi ned mot jordoverflaten som det som sendes ut fra jordoverflaten.\nFiguren er riktig hvis vi ser bort fra drivhuseffekten.\nDet kommer prosentvis mindre energi inn til drivhusgassene enn de sender ut.",
    },
    {
      number: 2,
      title: "forbedre klimamodell",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "REA3043 Geofag 2\nOppgave 2\nOppgave 2 – forbedre klimamodell\n\nEn klimaforsker observerer at en klimamodell systematisk gir for høye temperaturer i arktiske områder sammenlignet med paleoklimatiske data fra Holocen. \n\nHvilken av mekanismene nedenfor er ikke godt nok representert i modellen?\nsnø- og isalbedo\nmetanutslipp fra permafrost \nutbredelse av boreal skog\naerosoleffekter fra vulkansk aktivitet",
    },
    {
      number: 3,
      title: "nedbør",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\nOppgave 3\nOppgave 3 – nedbør\n\nI værkartet nedenfor er det markert tre steder med tallene 1, 2 og 3.\n\n \n\nKilde: Meteorologisk institutt. Hentet 5. november 2024 fra https://www.met.no/vaer-og-klima/meteorologens-analysekart. \n \nPå hvilket av disse tre stedene er det høyest sannsynlighet for at det er kraftig nedbør akkurat på dette tidspunktet?\nDet er størst sannsynlighet for kraftig nedbør på stedet merket med 1.\nDet er størst sannsynlighet for kraftig nedbør på stedet merket med 2.\nDet er størst sannsynlighet for kraftig nedbør på stedet merket med 3.\nDet er like stor sannsynlighet for kraftig nedbør alle disse tre stedene.",
    },
    {
      number: 4,
      title: "tetthet i havet",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\nOppgave 4\nOppgave 4 – tetthet i havet \n\nFiguren nedenfor viser overflatetettheten i verdenshavene. \n\n \n\nKilde: Figur 6.3.1 i Chapter 6: Physical Oceanography. (2023). I P. Webb, Introduction to Oceanography. Hentet fra https://rwu.pressbooks.pub/webboceanography/.\nKryss av for om påstandene nedenfor er sanne eller usanne. \nKryss av for om påstandene nedenfor er sanne eller usanne. \n\tSann\tUsann\nVi finner det tyngste overflatevannet i Indiahavet.\n\nHovedårsaken til at overflatevannet i Middelhavet har høy tetthet, er høy fordampning.\n\nVi finner de høyeste verdiene for tetthet i kystnære områder.\n\nVi finner de laveste verdiene for havoverflatens tetthet i tropiske områder.",
    },
    {
      number: 5,
      title: "forskning på forhistorisk klima",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\nOppgave 5\nOppgave 5 – forskning på forhistorisk klima\n\nBildet nedenfor viser et utsnitt av en trestamme med årringer. Årringene er merket med bokstavene A–K, som representerer hvert sitt år. Nederst i bildet ligger det en linjal med centimetermål.\n\nKilde: Utdanningsdirektoratet\n \n\nDersom denne tresorten vokser best ved høye temperaturer, hvilket år var mest sannsynlig det kaldeste?\n\n \nla stå tom\nÅr A\nÅr B\nÅr C\nÅr E\nÅr H\nÅr I\nÅr K\n \n\nDersom denne tresorten vokser best når det er mye nedbør, hvilket år var mest sannsynlig det våteste?\n\n \nla stå tom\nÅr A\nÅr B\nÅr C\nÅr E\nÅr H\nÅr I\nÅr K",
    },
    {
      number: 6,
      title: "corioliseffekten",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\nOppgave 6\nOppgave 6 – corioliseffekten\n\nPå verdenskartet nedenfor er det tegnet inn fem sirkler.\n\nTrykk på sirkelen der corioliseffekten er sterkest. \n\nKilde: Free World Maps. Hentet 22. april 2025 fra https://www.freeworldmaps.net/.",
    },
    {
      number: 7,
      title: "dyphavsstrømmer",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "REA3043 Geofag 2\nOppgave 7\nOppgave 7 – dyphavsstrømmer\nHva er den primære drivkraften bak dyphavsstrømmer i verdenshavene?\nvindmønstre på havoverflaten\njordens rotasjon (corioliseffekten)\nforskjeller i vannets tetthet på grunn av temperatur og salinitet\ntidevannskrefter fra månen og solen",
    },
    {
      number: 8,
      title: "fjordvann",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "Oppgave 8 – fjordvann\n\nI figuren nedenfor ser du en skjematisk framstilling av hvordan havvann fordeler seg i fjorder. I høyre side av bildet ser du en elv som renner ut i fjorden, og at vannet som kommer fra elven, legger seg over de andre lagene med vann.\n\nKilde: Arctic Monitoring and Assessment Programme. Hentet 11. mars 2025 fra https://www.amap.no/documents/doc/sketch-of-main-circulation-pattern-in-a-fjord/306. Tilpasset av Utdanningsdirektoratet.\n \nHva er den viktigste grunnen til at vannet som kommer ut i fjorden fra elven, legger seg øverst?\nVannet fra elven er kaldere enn kystvannet.\nVannet fra elven er varmere enn kystvannet.\nVannet fra elven har lavere salinitet enn kystvannet.\nVannet fra elven har høyere salinitet enn kystvannet.",
    },
    {
      number: 10,
      title: "eksentrisitet",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "Oppgave 10 – eksentrisitet\n\nJordbanens eksentrisitet er en av de tre Milanković-syklusene.\n\nFiguren nedenfor viser hvordan jordbanens eksentrisitet har variert over perioden fra 1,0 til 2,0 millioner år siden. \n\nDet er flere faktorer som avgjør om vi får istider på jorden, men i denne oppgaven skal du bare ta hensyn til eksentrisiteten. \n\nKilde: Science files. Hentet 11. mars 2025 fra https://sciencefiles.org/2019/09/15/milankovitch-zyklen-sonnenverursachter-klimawandel-es-wird-kalter/. Tilpasset av Utdanningsdirektoratet.\nI hvilken av periodene nedenfor er det størst sannsynlighet for at det var istid på jorden?\nfor 1,07 millioner år siden\nfor 1,61 millioner år siden\nfor 1,68 millioner år siden\nfor 1,95 millioner år siden",
    },
    {
      number: 13,
      title: "referanseperioder",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\nOppgave 13\nOppgave 13 – referanseperioder\n\nI figurene nedenfor kan du se to ulike scenarioer for hvor mye varmere det vil bli 2 meter over bakken i 2050. \n\nBegge figurene bruker samme modell (CMIP5), og begge regner med RCP4,5. Forskjellen på figurene er at de har ulik referanseperiode. Figur A har 1920–1940 som referanseperiode, mens figur B har 2010–2024 som referanseperiode. De to figurene har ulike svar på hvor stor temperaturanomalien i 2050 vil bli.\n\nSkalaen er oppgitt i °C.\n\nKilde: Climate Reanalyzer. Hentet 22. april 2025 fra https://climatereanalyzer.org/research_tools/monthly_maps/. Tilpasset av Utdanningsdirektoratet.\n \nHva forteller figurene oss om forskjellen på disse to referanseperiodene?\n1920–1940 var en varmere periode enn 2010–2024.\nBegge referanseperiodene var like varme.\n1920–1940 var en kaldere periode enn 2010–2024.",
    },
    {
      number: 17,
      title: "alpin og arktisk permafrost",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "REA3043 Geofag 2\nOppgave 17\nOppgave 17 – alpin og arktisk permafrost\n\nAlpin permafrost finnes i høytliggende fjellområder rundt om på kloden. Eksempler på slike fjellområder er Himalaya, Alaska, Alpene og Jotunheimen. \n\nArktisk permafrost dekker store geografiske områder. Eksempler på dette er Sibir, nordlige deler av Canada og Finnmark.\n\nPermafrost som tiner på grunn av global oppvarming, får ulike konsekvenser, der noen er mer alvorlige enn andre. \n\nHvilken av konsekvensene nedenfor utgjør den minste trusselen for mennesker og infrastruktur i framtiden?\n\nstore mengder utslipp av metan fra alpin permafrost som tiner\nskred i løsmasser når arktisk permafrost tiner\nisskred fra ustabile isbreer i områder med alpin permafrost",
    },
    {
      number: 20,
      title: "svekkelse av AMOC",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "REA3043 Geofag 2\nOppgave 20\nOppgave 20 – svekkelse av AMOC\n\nGolfstrømmen utgjør den vestlige delen av den store subtropiske gyren i Nord-Atlanteren. Golfstrømmen eller Golfstrømsystemet er en del av den termohaline sirkulasjonen i Atlanterhavet. Den termohaline sirkulasjonen gir opphav til omveltningssirkulasjonen i Atlanterhavet, kjent som Atlantic Meridional Overturning Circulation (AMOC) på engelsk. \n\nAMOC er et viktig system av havstrømmer i Atlanterhavet. Dette systemet fungerer som en gigantisk varmepumpe: Varmt overflatevann strømmer nordover, blir avkjølt, synker ned i dypet og strømmer så sørover igjen. Denne sirkulasjonen er helt avgjørende for klimaet vårt, spesielt i Nord-Europa.\n\nEt 3D-blikk på havsirkulasjonen i Atlanterhavet sett fra 26 grader nord. I øvre lag frakter Golfstrømmen varmt vann nordover. Den subtropiske gyren sirkulerer med klokken, og den subpolare gyren sirkulerer mot klokken. Vertikalt kjøles varmt overflatevann ned og synker som en del av omveltningssirkulasjonen (AMOC). (Grafikk: J. Skrefsrud / H. Asbjørnsen. Kilde: Asbjørnsen, 2023).\n\nHvilken av årsakene nedenfor kan føre til at AMOC svekkes?\n\nTilførsel av smeltevann i polare områder fører til mindre stratifisering i overflatelaget, noe som bidrar til vertikal blanding og dypvannsdannelse.\nHavvannets salinitet i polare områder øker som en konsekvens av global oppvarming.\nRedusert trykkgradient mellom polare og tropiske breddegrader gir svakere vindsystemer, som kan svekke AMOC ved å redusere nordlig transport av varmt vann.\nØkt overflatetemperatur i Nord-Atlanteren fører til tettere vannmasser, som dermed synker mindre og svekker AMOC.",
    },
    {
      number: 21,
      title: "strålingsbalansen og karbonkretsløpet",
      kind: "skrive",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\nOppgave 21\nOppgave 21 – strålingsbalansen og karbonkretsløpet\n\n \n\nDenne oppgaven er knyttet til vedlegget i starten av eksamenssettet.\n\n \n\nOppgaven består av en kortsvarsoppgave og en langsvarsoppgave. \n\nKortsvarsoppgave – strålingsbalansen\nKilde: Bjerknes Centre for Climate Research. Hentet 30. april 2025 fra https://bjerknes.uib.no/laer-om-klima-2/faktasider/drivhuseffekten-og-jordens-klima.\n\nFiguren ovenfor illustrerer strålingsbalansen i en stabil tilstand. Ta utgangspunkt i denne figuren og gjør rede for hvilke prosesser i strålingsbalansen som endres under global oppvarming.",
    },
    {
      number: 22,
      title: "permafrost",
      kind: "skrive",
      needsFigure: true,
      prompt: "Oppgave 22 – permafrost \n\n \n\nDenne oppgaven består av to kortsvarsoppgaver. \n\nKortsvarsoppgave – konsekvenser av tining av permafrost\n\nI deler av de arktiske områdene tiner permafrosten som en konsekvens av global oppvarming. I figur 1 nedenfor ser man hvilke områder som har permafrost i dag (blå og grønn farge), og hvilke områder som kan beholde permafrosten fram mot 2060 (grønn farge).\n\nFigur 1. Fordeling av målt permafrost (2000–2014) i blått og modellert framskriving (RCP4,5)(2041–2060) i grønt. Her er også borehull vist som sirkler farget etter temperatur ved bakkeoverflaten (MAGT). To områder markert med svarte streker er forstørret for å illustrere detaljer. Kilde: https://www.nature.com/articles/s41467-018-07557-4/figures/1.\n \n\nFigur 2 nedenfor er et forstørret utsnitt av figur 1 og viser et område nord i Russland. På figuren er det tegnet på fire ulike bosetninger, merket med kryss og bokstavene A–D. Disse bosetningene eksisterer kanskje ikke i virkeligheten, men de er plassert der av hensyn til denne oppgaven.\n\nA = bosetning på kysten i blått område\nB = bosetning på kysten i grønt område\nC = bosetning i innlandet i blått område\nD = bosetning i innlandet i grønt område\n\nFigur 2. Utsnitt av figur 1. Fordeling av målt permafrost (2000–2014) i blått og modellert framskriving (RCP4,5)(2041–2060) i grønt. Hvitt markerer havområder. Fire tenkte bosetninger er markert med x og bokstavene A–D. Kilde: https://www.nature.com/articles/s41467-018-07557-4/figures/1.\n\nVurder hver av de fire påstandene nedenfor, og avgjør om den er sann, usann eller umulig å avgjøre ut fra de tilgjengelige opplysningene. \n\nBegrunn alle vurderingene med geofaglig argumentasjon.\n\nDe som bor i A, må gjøre større tiltak med tanke på naturfarer de neste 30 årene enn de som bor i B.\nDe som bor i A, må gjøre større tiltak med tanke på naturfarer de neste 30 årene enn de som bor i C.\nDet er like stor fare for naturfarer i C og D de neste 30 årene.\nSjøisutbredelsen i Arktis har ingen betydning for hyppigheten av naturfarer i A.\nNår vi snakker om naturfarer i denne oppgaven, er det naturfarer knyttet til havet, atmosfæren og kryosfæren, altså naturfarer som er aktuelle i geofag 2.",
    },
    {
      number: 23,
      title: "sirkulasjon i atmosfære og hav",
      kind: "skrive",
      needsFigure: true,
      prompt: "Oppgave 23 – sirkulasjon i atmosfære og hav\n \n\nDenne oppgaven består av to kortsvarsoppgaver. \n\nKortsvarsoppgave – havstrømmene i Sørishavet\n\nFigur 1 nedenfor viser overflatestrømmene i Sørishavet. Nærmest Antarktis finner vi Den antarktiske kyststrømmen (på figuren er den kalt «East Wind Drift»), og litt lenger nord ligger strømmen som kalles enten Sørishavsstrømmen eller Den antarktiske sirkumpolare strøm (på figuren er den kalt «Antartic Circumpolar Current (West Wind drift)»). \n\nFigur 1: Antarctic: Ocean Circulation. (u.å.). Dive and Discover. Hentet 12. februar 2025 fra https://divediscover.whoi.edu/polar-regions/antarctic-ocean-circulation/. Modifisert av Utdanningsdirektoratet.\n\nGjør rede for hvordan den globale atmosfæriske sirkulasjonen påvirker overflatestrømmene i Sørishavet.",
    },
  ],
};
