import type { ExamSet } from "../types";

export const v2025: ExamSet = {
  slug: "v2025",
  label: "Vår 2025",
  season: "V",
  year: 2025,
  kind: "eksamen",
  complete: true,
  officialUrl: "https://kandidat.udir.no/epsmateriell/eksamen?fagkode=REA3043&malform=nb-NO&semester=V&ar=2025&eksamensdeltype=Eksamen",
  themes: [
    "Interaktive oppgaver",
    "Skriveoppgaver",
  ],
  tasks: [
    {
      number: 1,
      title: "havstrømmer og vær i Norge",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "REA3043 Geofag 2\nOppgave 1\nOppgave 1 – havstrømmer og vær i Norge\n\nHva vil skje med været langs vestkysten av Norge dersom Den nordatlantiske strømmen stopper opp eller svekkes kraftig på grunn av global oppvarming?\n\nMarker rett alternativ.\nVestkysten av Norge vil sannsynligvis få lavere temperatur og mindre nedbør.\nVestkysten av Norge vil sannsynligvis få lavere temperatur og mer nedbør.\nVestkysten av Norge vil sannsynligvis få høyere temperatur og mindre nedbør.\nVestkysten av Norge vil sannsynligvis få høyere temperatur og mer nedbør.",
    },
    {
      number: 2,
      title: "AMOC",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "REA3043 Geofag 2\nOppgave 2\nOppgave 2 – AMOC\n\nHvorfor kan global oppvarming føre til at AMOC (omveltningssirkulasjonen i Atlanterhavet) kollapser?\n\nMarker det alternativet som forklarer det best.\nGlobal oppvarming vil føre til økt fordamping og dermed økt salinitet i havvannet. Dermed vil alt vannet få like høy densitet, og sirkulasjonen vil kollapse.\nGlobal oppvarming vil føre til at innlandsisen på Grønland smelter. Dermed tilføres det mye kaldt ferskvann i havet, noe som kan få sirkulasjonen til å kollapse.\nGlobal oppvarming vil føre til økt nedbør i form av regn i de nordlige delene av Atlanterhavet. Dermed kan det ikke dannes sjøis, og dette vil føre til at det ikke skjer noen dypvannsdannelse.",
    },
    {
      number: 3,
      title: "marine hetebølger",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "REA3043 Geofag 2\nOppgave 3\nOppgave 3 – marine hetebølger\n\nMarine hetebølger er perioder der havoverflatetemperaturen er høyere enn vanlig.\n\n \n\nNedenfor er det fire påstander om marine hetebølger.\n\nMye solinnstråling og redusert skydekke kan være årsaker til marine hetebølger.\nSvak vind, lite bølger og svake havstrømmer kan gi sterk stratifisering i havet. Dette er gunstige forhold for dannelse av marine hetebølger.\nI perioder med La Niña-forhold oppstår det ofte marine hetebølger.\nMarine hetebølger kan føre til svakere tropiske orkaner.\n \nHvilke påstander om marine hetebølger stemmer? Velg riktig alternativ.\npåstand 2 og 3\npåstand 1 og 3\npåstand 1 og 2\npåstand 2 og 4",
    },
    {
      number: 4,
      title: "strålingspådriv",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\nOppgave 4\nOppgave 4 – strålingspådriv\n\nFiguren nedenfor viser ulike årsaker til endring i strålingspådriv.\n\n \n\nHentet 5.1.24 fra https://no.wikipedia.org/wiki/Str%C3%A5lingsp%C3%A5driv Figuren er modifisert av Udir.\n\n \n\nHvordan påvirkes klimaet på jorden om vi øker innholdet av ozon i 20–30 km høyde over bakken?\nDen globale temperaturen vil synke mye.\nDen globale temperaturen vil ikke påvirkes i noen særlig grad.\nDen globale temperaturen vil synke mye.",
    },
    {
      number: 5,
      title: "albedo",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\nOppgave 5\nOppgave 5 – albedo \n\n \n\nMarker om påstandene i tabellen nedenfor er rette eller gale.\n\nDu må lage opptil 3 koblinger\n\nMarker om påstandene i tabellen nedenfor er rette eller gale.\n\tRett\tGalt\nLavere global albedo fører til økt absorpsjon av solenergi på jorden.\n\nNår permafrost tiner, vil albedoen alltid bli lavere fordi mer sollys blir absorbert og overflaten blir varmet opp.\n\nDet er mulig å bruke satellitter til å måle albedo.",
    },
    {
      number: 6,
      title: "energi fra sola",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\nOppgave 6\nOppgave 6 – energi fra sola\n\nFiguren nedenfor viser mottatt solenergi på ulike breddegrader gjennom et år. Hver av grafene tilsvarer energi mottatt på en bestemt breddegrad.\n\nSolinnstråling gjennom året. Figur hentet den 4.10.24 fra https://www.researchgate.net/figure/The-solar-radiation-received-at-local-noon-each-day-of-the-year-depends-on-the-latitude_fig2_322416914. Figuren er modifisert av Utdanningsdirektoratet.\n \nTa utgangspunkt i figuren ovenfor og huk av slik at du kobler sammen de riktige breddegradene og grafene i tabellen nedenfor.\n\nDu må lage opptil 3 koblinger\n\nTa utgangspunkt i figuren ovenfor og huk av slik at du kobler sammen de riktige breddegradene og grafene i tabellen nedenfor.\n\tGrønne grafer med streker\tOransje graf med trekanter\tSvart graf med rundinger\nInnstråling ved ekvator\n\nInnstråling på sørlig halvkule\n\nInnstråling på nordlig halvkule",
    },
    {
      number: 7,
      title: "farevarsel for Finnmark",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\nOppgave 7\nOppgave 7 – farevarsel for Finnmark\nNedenfor er et analysekart fra Meteorologisk institutt (MET). Vi skal se nærmere på Finnmark innenfor den svarte ringen i figuren. Analysekartet er fra tirsdag klokken 06.00.\n\nAnalysekart fra Meteorologisk institutt, hentet 1.10.24 fra https://www.met.no/vaer-og-klima/meteorologens-analysekart\n \n\nTirsdag klokken 06.00 ble det sendt ut et farevarsel for de kommende timene. Nedenfor er det vist tre ulike farevarsler. Du skal vurdere hvilket farevarsel som ble sendt ut denne dagen.\n\nFigur 1 hentet 1.10.24 fra https://slaps.met.no/cap-images/3a1da270-3c74-4287-b712-535dcbe1d4df.png. Figur 2 hentet 1.10.24 fra https://www.ifinnmark.no/farevarsel-fra-meteorologen/s/5-81-2038861. Figur 3 hentet 1.10.24 fra https://kronstadposten.no/farevarsel-om-skogbrannfare-i-vest-finnmark.\n \nMarker alternativet som viser farevarselet som ble sendt ut tirsdag klokken 06.00.\n1\n2\n3",
    },
    {
      number: 8,
      title: "lufttrykk",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\nOppgave 8\nOppgave 8 – lufttrykk\n\nNedenfor ser du en animasjon som viser trykkfelt over store deler av Stillehavet. Fargene viser lufttrykket ved havnivå. \n\nEt par sekunder ut i animasjonen markeres ekvatorsonen med svart, og et trykksenter markeres med hvitt. \n\n \n\nspill av\n00:00\nslå av lyd\nfullskjerm\nSPILL AV\nmediaspiller\nMarker den riktige påstanden.\nDet ekvatorielle lavtrykksbeltet ligger litt nord for ekvator. Dette forteller oss at det er sommer på den nordlige halvkule.\nDet er høytrykk rundt ekvator. Det betyr at det er sommer på den nordlige halvkule.\nSirkulasjonen rundt trykksenteret som er markert med hvitt, går med klokken. Det må derfor være et høytrykkssenter.\nBlåfargen er tydelig i Sørishavet. Det betyr at blåfarge er høytrykk.",
    },
    {
      number: 9,
      title: "isotopforhold i sedimentkjerne",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "REA3043 Geofag 2\nOppgave 9\nOppgave 9 – isotopforhold i sedimentkjerne\n\nEn forsker studerer isotopforholdet mellom 18O og 16O i kalkskall fra foraminiferer i en sedimentkjerne. \n\nHvilken slutning kan forskeren trekke hvis andelen 18O øker i forhold til 16O oppover i kjernen?\nHavtemperaturen har sunket.\nHavtemperaturen har steget.\nHavnivået har steget.\nSaltholdigheten i havet har økt.",
    },
    {
      number: 10,
      title: "den lille istiden",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\nOppgave 10\nOppgave 10 – den lille istiden\n\nDen lille istiden var en kald periode i Europa som varte fra midten av 1500-tallet til midten av 1800-tallet. \n\nNedenfor ser du seks påstander om hvilke faktorer som var avgjørende for den lille istiden.\n\nVulkanutbrudd: Det var flere kraftige vulkanutbrudd som førte til mange aerosoler i atmosfæren.\nSolflekker: Av ukjente årsaker var det svært liten solflekkaktivitet i denne perioden.\nDen nordatlantiske oscillasjon (NAO): En langvarig periode med negativ NAO-indeks ga kalde forhold i Europa.\nPlatetektonikk: Kontinentenes plassering lå til rette for en kaldere periode.\nLa Niña: Det var flere år på rad med La Niña.\nAstronomiske variasjoner: De tre Milankovič-syklusene førte til en kald periode.\nHvilke påstander er de mest sannsynlige årsakene til den lille istiden?\npåstand 4, 5 og 6\npåstand 1, 5 og 6\npåstand 1, 2 og 3\npåstand 3, 4 og 6",
    },
    {
      number: 11,
      title: "polare lavtrykk",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\nOppgave 11\nOppgave 11 – polare lavtrykk\n\nNedenfor er det fire påstander om hvorfor det er vanskelig å varsle polare lavtrykk, og du skal avgjøre hvilke som er sanne.\n\n1. Polare lavtrykk er vanskelige å varsle siden de raskt blir sterke.\n\n2. Det er vanskelig å varsle polare lavtrykk siden de som regel dannes i områder der det er få folk og få målestasjoner.\n\n3. Siden de polare lavtrykkene dannes langt inne på sjøisen, er de vanskelige å registrere.\n\n4. Polare lavtrykk er så små at de ikke vises på satellittbilder, og dette gjør at de er vanskelige å varsle.\n\nMarker rett alternativ.\nPåstand 1 og 2 er sanne.\nPåstand 2 og 3 er sanne.\nPåstand 3 og 4 er sanne.\nPåstand 4 og 1 er sanne.\nPåstand 2 og 4 er sanne.\nPåstand 3 og 1 er sanne.",
    },
    {
      number: 12,
      title: "sjøisutbredelse",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\nOppgave 12\nOppgave 12 – sjøisutbredelse\n\nFigurene nedenfor viser sjøisutbredelse (i millioner kvadratkilometer) gjennom året ved polene på nordlig og sørlig halvkule i perioden fra 1980 til oktober 2024. Ulike farger tilsvarer sjøisutbredelse i ulike tiår. \n\nI denne oppgaven skal du avgjøre om påstandene om sjøisutbredelse i tabellen under figurene er sanne eller usanne. Noen av påstandene er knyttet til figurene nedenfor.\n\n \n\nFigur: Global sjøisindeks (fra EUMETSAT OSI SAF), daglige tidsserier for nordlig og sørlig halvkule. Hentet 1.10.24 fra https://cryo.met.no/nb/sjoe-is-indeks\n \n\nMarker hvilke påstander som er sanne, og hvilke som er usanne.\n\nDu må lage opptil 5 koblinger\n\nMarker hvilke påstander som er sanne, og hvilke som er usanne.\n\n\tSann\tUsann\nFiguren til høyre viser sjøisutbredelse på den nordlige halvkulen.\n\nDen årlige variasjonen i sjøisutbredelse (i millioner km2) er like stor på begge figurene.\n\nFiguren til venstre viser større årstidsvariasjon i sjøisutbredelse enn figuren til høyre.\n\nEndringer i sjøisutbredelse påvirker i liten grad lufttemperaturen.\n\nIfølge figuren til venstre har sjøisutbredelsen vært lavere i september måned i perioden 2010 til 2024 enn i perioden 1980 til 2000.",
    },
    {
      number: 13,
      title: "værkart og vindstyrke",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\nOppgave 13\nOppgave 13 – værkart og vindstyrke\n\nDette værkartet fra yr.no viser værsituasjonen i Nord-Atlanteren. Tre steder er merket av med bokstavene X (Island), Y (Nord-Irland) og Z (vest i Norge).\n\n   \nPå hvilket av disse stedene er vinden sterkest?  \nVinden er sterkest ved bokstaven X på Island.\nVinden er sterkest ved bokstaven Y i Nord-Irland.\nVinden er sterkest ved bokstaven Z vest i Norge.\nVinden er like sterk alle disse tre stedene.",
    },
    {
      number: 14,
      title: "salinitet",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\nOppgave 14\nOppgave 14 – salinitet\n\nKartet nedenfor viser den gjennomsnittlige saliniteten i havene.\n\nHentet 5.11.24 fra https://www.sciencelearn.org.nz/resources/686-ocean-salinity. Figuren er modifisert av Utdanningsdirektoratet.\n \n\nHer er fire påstander om kartet ovenfor. Du skal avgjøre om de er sanne eller usanne.\n\n1) Det er mest salt i havvannet der mange elver munner ut.\n\n2) Det er mer salt i havvannet der fordampingen er høyere enn nedbørsmengden.\n\n3) Det er mer salt i havvannet i de områdene som har mye nedbør.\n\n4) Det er mer salt i kaldt havvann enn i varmt.\n\nMarker rett alternativ.\nPåstand 1 og 2 er sanne, 3 og 4 er usanne.\nPåstand 1 og 3 er sanne, 2 og 4 er usanne.\nPåstand 2 er sann, de andre er usanne.\nPåstand 3 er sann, de andre er usanne.\nPåstand 4 er sann, de andre er usanne.\nAlle påstandene er sanne.\nPåstand 1, 3 og 4 er sanne, 2 er usann.\nAlle påstandene er usanne.",
    },
    {
      number: 15,
      title: "klimagasser",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "REA3043 Geofag 2\nOppgave 15\nOppgave 15 – klimagasser\nHvorfor fører en økt mengde klimagasser i atmosfæren til at den globale temperaturen øker?\nfordi klimagassene stopper solinnstrålingen\nfordi klimagassene reduserer albedoen på jordoverflaten\nfordi klimagassene øker den langbølgede utstrålingen fra jorden\nfordi klimagassene absorberer den utgående langbølgede strålingen fra jorden",
    },
    {
      number: 16,
      title: "temperaturforhold i atmosfæren",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "REA3043 Geofag 2\nOppgave 16\nOppgave 16 – temperaturforhold i atmosfæren\nTemperaturen i troposfæren er høyest ved bakkenivå under normale forhold. Den viktigste årsaken til dette er at ...\n solinnstrålingen varmer opp nedre del av troposfæren direkte\n utstrålingen fra jorden varmer opp nedre del av troposfæren\n varmeledning fra jordoverflaten varmer opp nedre del av troposfæren\n ozon ved bakkenivå absorberer utstråling fra jorden",
    },
    {
      number: 17,
      title: "været i stratosfæren",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "REA3043 Geofag 2\nOppgave 17\nOppgave 17 – været i stratosfæren\nHva er en mulig forklaring på at det ikke dannes skyer og nedbør i stratosfæren?\nMengden vanndamp er tilstrekkelig, men temperaturen stiger med høyden.\nDenne delen av atmosfæren regnes som ustabil.\nTemperaturen stiger med høyden, og denne delen av atmosfæren regnes som ustabil.\nTemperaturen faller med høyden, men mengden av vanndamp er ekstremt liten.",
    },
    {
      number: 18,
      title: "tropiske orkaner og dødelighet",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "REA3043 Geofag 2\nOppgave 18\nOppgave 18 – tropiske orkaner og dødelighet\n\nHvilken av faktorene nedenfor forårsaker størst tap av menneskeliv i en tropisk orkan?\n\nhagl\n\nvind\n\nlyn\nstormflo",
    },
    {
      number: 19,
      title: "permafrost",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "REA3043 Geofag 2\nOppgave 19\nOppgave 19 – permafrost\n\nUlike faktorer spiller en viktig rolle i å opprettholde permafrosten i et område.\n\nVelg den faktoren du mener har størst betydning.\net høyt innhold av vann i bakken som fryser til is om vinteren, fordi is øker varmeledningen mellom bakken og atmosfæren\net tynt torvdekke isolerer lite og øker varmeledningen mellom bakken og atmosfæren\net tykt snødekke tidlig på vinteren reduserer varmeledningen mellom bakken og atmosfæren\nliten mengde solinnstråling kombinert med tørre forhold i bakken om sommeren",
    },
    {
      number: 20,
      title: "sirkulasjon i Nord-Atlanteren",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "REA3043 Geofag 2\nOppgave 20\nOppgave 20 – sirkulasjon i Nord-Atlanteren\n\nLes påstandene nedenfor om AMOC og sirkulasjonen i Nord-Atlanteren.\n\nMarker hvilke påstander som er sanne, og hvilke som er usanne.\n\nDu må lage opptil 5 koblinger\n\nMarker hvilke påstander som er sanne, og hvilke som er usanne.\n\tSant\tUsant\nGolfstrømmen går hele veien fra Karibia og inn i Norskehavet.\n\nAMOC er overflatestrømmer drevet av vind.\n\nGolfstrømsystemet er et vertikalt sirkulasjonssystem i havet.\n\nDe subtropiske gyrene drives av både storstilte vindsystemer og gravitasjonskrefter i havet.\n\nAMOC kan stoppe opp uten at den subtropiske gyren stopper opp.",
    },
    {
      number: 21,
      title: "skyer, klima og fronter",
      kind: "skrive",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\nOppgave 21\nOppgave 21 – skyer, klima og fronter\na) Skytyper koblet til ulike fronter\n\nNedenfor ser du to bilder av ulike skyer. I denne oppgaven skal du koble disse skytypene med ulike fronter. \n\nBilde 1. Kilde: https://outforia.com/types-of-clouds/\n \n\n \n\nBilde 2. Kilde: Ames Tribune @ Pinterest\n \n\nEtt av bildene viser skyer du ser når en kaldfront er på vei mot deg. \n\nEtt av bildene viser skyer du ser når en varmfront er på vei mot deg.\n\nKortsvarsoppgave: Gjør rede for hvordan de to ulike skytypene på bildene ovenfor kan knyttes til henholdsvis en varmfront og en kaldfront.",
    },
    {
      number: 22,
      title: "paleoklima, AMOC og modeller",
      kind: "skrive",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\nOppgave 22\nOppgave 22 – paleoklima, AMOC og modeller\na) Klimaforskere modellerer ulike tilstander av AMOC\n\nForskere har identifisert fire forskjellige stabile tilstander for AMOC:\n\n1. Avslått: ingen dypvannsdannelse i Nord-Atlanteren\n2. Svak: konveksjon hovedsakelig sør for 55° N\n3. Dagens: dypvannsdannelse i Labradorhavet, Grønlandshavet og Norskehavet\n4. Sterk: konveksjon som strekker seg inn i Arktis\n\nFigur 1 nedenfor presenterer to figursett som viser modellerte data for de fire tilstandene. \n\na, b, c og d viser maksimal isutbredelse (grå linje) og i tillegg hvor dypt konveksjonen i havet går, altså hvor dypt blandingslaget går.\ne, f, g og h viser styrken på AMOC i Sv (Sverdrup). Positive verdier betyr at strømmen er nordgående, mens negative verdier betyr at strømmen er sørgående.\n \n\n \n\nFigur 1 er hentet fra Willeit, M. og Ganopolski, A. (2024). Generalized stability landscape of the Atlantic meridional overturning circulation. Earth System Dynamics, 15(6), 1417–1434. https://doi.org/10.5194/esd-15-1417-2024 \n       \n\nForskerne undersøkte hvordan AMOC reagerer på endringer i atmosfærisk CO2-konsentrasjon og ferskvannstilførsel til Nord-Atlanteren. Generelt fant de at\n\nhøyere CO2-nivåer favoriserer sterkere AMOC-tilstander\nøkt ferskvannstilførsel svekker AMOC\n\nFigur 2 nedenfor viser sammensettinger av CO2-nivåer og ferskvannstilførsel ved de ulike stabile tilstandene av AMOC. \n\nDen horisontale aksen viser styrken på ferskvannstilførselen, og den vertikale viser CO2-nivåene i atmosfæren. Fargekoden angir hvor sterke havstrømmer det er (gitt i Sv) i de ulike stabile AMOC-tilstandene. Prikken markerer ingen endring i ferskvannstilførsel og førindustriell verdi av CO2.\n\n \n\nFigur 2 er hentet fra Willeit, M. og Ganopolski, A. (2024). Generalized stability landscape of the Atlantic meridional overturning circulation. Earth System Dynamics, 15(6), 1417–1434. https://doi.org/10.5194/esd-15-1417-2024\n   \n\nNedenfor finner du fire påstander om de ulike AMOC-tilstandene. To av påstandene er sanne, og to er usanne.\n\nNår AMOC er avslått, er det ingen dypvannsdannelse i Nord-Atlanteren.\nEn sterk AMOC oppstår bare dersom CO2-nivåene er lavere enn 280 ppm.\nVed høye CO2-konsentrasjoner (over 400 ppm) krever en sterk AMOC-tilstand en større negativ ferskvannstilførsel for å være stabil enn de andre tilstandene.\nSjøisutbredelsen i Nord-Atlanteren er størst i den sterke AMOC-tilstanden.\nKortsvarsoppgave: Du skal gjøre rede for de to påstandene som du mener er sanne. Begrunn svaret ditt med utgangspunkt i figurene ovenfor.",
    },
    {
      number: 23,
      title: "konsekvenser av klimaendringer",
      kind: "skrive",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\nOppgave 23\nOppgave 23 – konsekvenser av klimaendringer\nNaturfarer og klimaendringer i Norge\na)\n\nRapporten Klima i Norge 2100 kom ut i 2015. Et av hovedfunnene i denne rapporten er at årsnedbøren i Norge vil øke med ca. 18 prosent innen år 2100, med et spenn mellom 7 og 23 prosent.  \n\nKortsvarsoppgave: Velg en del av Norge du kjenner, og gjør rede for hvordan en økning i årsnedbøren der vil kunne påvirke risikoen for naturfarer.",
    },
  ],
};
