import type { ExamSet } from "../types";

export const v2026: ExamSet = {
  slug: "v2026",
  label: "Vår 2026",
  season: "V",
  year: 2026,
  kind: "eksamen",
  complete: true,
  officialUrl: "https://kandidat.udir.no/epsmateriell/eksamen?fagkode=REA3043&malform=nb-NO&semester=V&ar=2026&eksamensdeltype=Eksamen",
  fasitSource: "udir",
  themes: [
    "Ekstremvær i Europa",
    "Våre nære havområder og feltdata",
    "Istider og klimaendringer",
    "Vekselvirkninger og energi",
  ],
  tasks: [
    {
      number: 1,
      title: "Ekstremvær i Europa",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "REA3043 Geofag 2\n / Tema 1 – Ekstremvær i Europa\nOppgave 1\nOppgave 1 – Ekstremvær i Europa\n\nOppgave 1 av 6 til tema 1. \n\nDu skal svare på oppgaven nederst på siden.\n\nVærvarsling\nNedenfor er et analysekart som viser en situasjon med et sterkt lavtrykk i Norskehavet. Dette lavtrykket vil nå fastlandet i Norge i løpet av dagen. Metrologene frykter at dette kan føre til ekstremvær med veldig kraftig vind. \n \nEt sted i Nordland er merket med «X».\nAnalysekart\nKilde: Meteorologisk institutt. Hentet fra https://www.met.no/vaer-og-klima/meteorologens-analysekart.\n\n \n\nOppgave\n\nHvilken vindretning vil det sannsynligvis være på stedet merket med «X» i Nordland når senteret i dette lavtrykket treffer land?\n\nVinden vil komme fra nordøst.\nVinden vil komme fra nordvest.\nVinden vil komme fra nord.\nVinden vil komme fra sørvest.\nVinden vil komme fra øst.",
    },
    {
      number: 2,
      title: "Ekstremvær i Europa",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\n / Tema 1 – Ekstremvær i Europa\nOppgave 2\nOppgave 2 – Ekstremvær i Europa\n\nOppgave 2 av 6 til tema 1. \n\nDu skal svare på oppgaven nederst på siden.\n\nMarine hetebølger\nEn marin hetebølge er en periode med unormalt høye vanntemperaturer. Slike perioder kan vare fra noen dager til flere måneder. Marine hetebølger er et stadig mer vanlig fenomen i europeiske farvann, fra Barentshavet i nord til Middelhavet i sør, og utgjør en alvorlig trussel mot marine økosystemer. \nMarin hetebølge i Middelhavet\n\nI august 2024 var det marin hetebølge i Middelhavet. Nedenfor finner du to figurer som inneholder informasjon om denne marine hetebølgen. Figurene handler om temperaturer i havoverflaten og om temperaturanomalier i havoverflaten sommeren 2024. Referanseperioden er 1991–2020.\n\nKilde: The Copernicus Climate Change Service (C3S). Hentet 16. oktober 2025 fra https://climate.copernicus.eu/esotc/2024/european-ocean#:~:text=Mediterranean%20marine%20heatwave-,Figure%2011.2.,-(Left)%20Daily%20sea (modifisert av Utdanningsdirektoratet).\nOppgave\n\nHer er fem påstander om denne hetebølgen i Middelhavet i august 2024. Du skal avgjøre hvilke av dem som er sanne:\n\nI august 2024 var overflatetemperaturen i Middelhavet nesten 10 °C varmere enn det langsiktige gjennomsnittet.\nDen høyeste målte temperaturen i august 2024 var 28,67 °C, og dette er den høyeste temperaturen som er registrert i Middelhavet siden 1991.\nSlike hetebølger kommer oftest av økt vulkansk aktivitet på havbunnen, og dette var også tilfellet i Middelhavet i august 2024.\nLite vind og fravær av skyer i en periode kan øke faren for at slike marine hetebølger oppstår.\nPå grunn av havstrømmene i Middelhavet ble hele Middelhavet like hardt rammet av denne marine hetebølgen.\n\nHvilke påstander er sanne?\n\nPåstand 1 og 4 er sanne.\nPåstand 2 og 3 er sanne.\nPåstand 2 og 4 er sanne.\nPåstand 4 og 5 er sanne.\nPåstand 1 og 5 er sanne.",
    },
    {
      number: 3,
      title: "Ekstremvær i Europa",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "REA3043 Geofag 2\n / Tema 1 – Ekstremvær i Europa\nOppgave 3\nOppgave 3 – Ekstremvær i Europa\n\nOppgave 3 av 6 til tema 1. \n\nDu skal svare på oppgaven nederst på siden.\n\nHetebølger i Spania\nSpania har de siste årene opplevd en økning i antall hetebølger, noe som har fått betydelige konsekvenser for både naturen og samfunnet. Urbanisering, klimaendringer og endringer i atmosfæresirkulasjon er blant faktorene som påvirker utviklingen.\nOppgave\n\nHvilken av følgende sammenhenger mellom årsak og virkning er mest korrekt i forbindelse med disse hetebølgene i Spania?\n\nØkt urbanisering fører til lavere temperaturer i byene, som reduserer risikoen for hetebølger.\nØkt global middeltemperatur bidrar til hyppigere hetebølger, som igjen kan føre til økt vannmangel og tørke.\nØkt vegetasjonsdekke i tørre områder fører til mer skogbranner, som igjen fører til mer ekstremvær og høyere dødelighet.\nRedusert solinnstråling på grunn av luftforurensning fører til mer intense hetebølger.",
    },
    {
      number: 4,
      title: "Ekstremvær i Europa",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\n / Tema 1 – Ekstremvær i Europa\nOppgave 4\nOppgave 4 – Ekstremvær i Europa\n\nOppgave 4 av 6 til tema 1. \n\nDu skal svare på oppgaven nederst på siden.\n\nTropiske orkaner\nKartet nedenfor viser utviklingen av den tropiske orkanen Gabrielle i Atlanterhavet september 2025, både hvilken bane den fulgte, og hvordan intensiteten utviklet seg. Orkanen startet i havet utenfor Vest-Afrika og bevegde seg nordvestover mot Bahamas, før den svingte i en mer nordøstlig retning mot Europa. Den gjorde en del skade på Asorene, men var svekket og gjorde lite skade på fastlandet. Det er uvanlig at slike tropiske sykloner når Europa.\nOrkanen Gabrielle\nKilde: Wikipedia. Hentet 2. februar 2026 fra https://en.wikipedia.org/wiki/Hurricane_Gabrielle_(2025).\nOppgave \n\nHva er den viktigste årsaken til at sterke tropiske sykloner sjelden forekommer i Europa?\n\nFor at de tropiske syklonene skal nå Europa, må de gå i en bane østover. Denne retningen gjør at corioliseffekten blir forsterket så mye at den overstiger trykkgradientkraften, og da dør orkanen ut. Dette ser vi på kartet for orkanen Gabrielle – straks orkanens bane svinger østover, svekkes orkanen.\nNår de tropiske syklonene kommer langt nok nord, blir de tatt av vestavindene og ført mot Europa. Vestavindene blåser hardt nok til at de svekker eller løser opp syklonen helt før den når Europa.\nNår en tropisk syklon kommer langt nok nord, vil den etter hvert komme over kaldere havområder. Syklonen mister da energitilførsel og dør ut. Slike stormer kan kun nå Europa i de årene der overflatetemperaturen er mye høyere enn normalt.",
    },
    {
      number: 5,
      title: "Ekstremvær i Europa",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "REA3043 Geofag 2\n / Tema 1 – Ekstremvær i Europa\nOppgave 5\nOppgave 5 – Ekstremvær i Europa\n\nOppgave 5 av 6 til tema 1. \n\nDu skal svare på oppgaven nederst på siden.\n\nJetstrømmer og kuldeperioder\n\nSterke og langvarige kuldeperioder er ekstremvær som utgjør en stor fare for mennesker i hele Europa. \n\nBanen til den polare jetstrømmen kan være en årsak til slike kuldeperioder.\n\nBanen til den polare jetstrømmen vil sannsynligvis bli påvirket av global oppvarming.\n\nOppgave\n\nHvordan vil global oppvarming påvirke hyppigheten av kuldebølger i Europa?\n\nØkt global temperatur vil sannsynligvis føre til flere og mer langvarige kuldebølger.\nØkt global temperatur vil sannsynligvis ikke påvirke kuldebølgene.\nØkt global temperatur vil føre til færre kuldebølger, og de kuldebølgene som kommer, vil vare kortere.",
    },
    {
      number: 6,
      title: "Ekstremvær i Europa",
      kind: "skrive",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\n / Tema 1 – Ekstremvær i Europa\nOppgave 6\nOppgave 6 – Ekstremvær i Europa\n\nOppgave 6 av 6 til tema 1. \n\nDu skal svare på oppgaven nederst på siden.\n\nEkstremværet Gyda og atmosfæriske elver\n\n12. og 13. januar 2022 førte ekstremværet Gyda til store skader i Norge. Dette ekstremværet ble omtalt som en atmosfærisk elv.\n\nPrognosekart\nFarevarsel\n\nPrognosekartet nedenfor ble laget mandag 10.01.22 og viser prognosen for onsdag 12.01.22.\n\nBlå farge viser fuktighet i atmosfæren. Mørk blå farge viser mer fuktighet enn lys blå farge. \n\nKilde: Norum, H. (2022, 14. januar). Ekstremvær som «Gyda» vil gi enda mer regn i framtida. NRK. Hentet 16. februar 2026 fra https://www.nrk.no/norge/ekstremvaer-som-_gyda_-vil-gi-enda-mer-regn-i-framtida-1.15809578 \nForrige fane\nNeste fane\nOppgave\n\nTa utgangspunkt i prognosekartet og farevarselet. Gjør rede for hvorfor Meteorologisk institutt varslet ekstreme nedbørsmengder på Vestlandet og i Trøndelag i forbindelse med Gyda.",
    },
    {
      number: 7,
      title: "Våre nære havområder og feltdata",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\n / Tema 2 – Våre nære havområder og feltdata\nOppgave 7\nOppgave 7 – Våre nære havområder og feltdata\n\nOppgave 1 av 6 til tema 2. \n\nDu skal svare på oppgaven nederst på siden.\n\nHavets tetthet \nEksperiment i klasserommet\nKilde: Mirjam Glessner, Geofysisk institutt, Universitetet i Bergen\n\nLæreren din har sagt at det er viktig at du forstår prosessene om havets tetthet for å forstå prosessene i Grønlandshavet.\n\nDu har derfor fått plassert to glass foran deg med romtemperert vann. Det ene glasset er ferskvann, og det andre er saltvann, men du vet ikke hvilket glass som inneholder ferskvann eller saltvann.\n\nSå blir det plassert en tesil i hvert glass. Denne tesilen inneholder en isbit av ferskvann som er farget med konditorfarge. Resultatet ser du i bildet til høyre.\n\nOppgave\n\nHvilken påstand om eksperimentet er riktig?\n\nGlasset til venstre må inneholde ferskvann fordi det kalde smeltevannet legger seg langs bunnen.\nGlasset til høyre må inneholde ferskvann fordi smeltevannet fra tesilen blander seg godt med ferskvannet.\nDet er umulig å si hvilket glass som inneholder ferskvann, basert på disse to bildene.",
    },
    {
      number: 8,
      title: "Våre nære havområder og feltdata",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "REA3043 Geofag 2\n / Tema 2 – Våre nære havområder og feltdata\nOppgave 8\nOppgave 8 – Våre nære havområder og feltdata\n\nOppgave 2 av 6 til tema 2. \n\nDu skal svare på oppgaven nederst på siden.\n\nTemperatur-salinitetsdiagram (T-S-diagram)\n\nHavet består av ulike vannmasser som har karakteristiske verdier for temperatur og salinitet. Disse egenskapene gir hver vannmasse et unikt «fingeravtrykk», slik at vi kan spore hvor vannet kommer fra, og hvordan det beveger seg. For å sammenligne vannmasser brukes ofte et temperatur-salinitetsdiagram (T-S-diagram), hvor salinitet plottes på x-aksen og temperatur på y-aksen. I slike diagrammer vises også linjer for konstant tetthet (isopyknaler), som hjelper oss å forstå hvordan tettheten varierer med temperatur og salinitet.\n\nEnheten for isopyknalene i diagrammet nedenfor er gitt i antall kg/dm3, altså antall kg per liter. Ferskvann veier 1,00 kg/dm3 ved 4 °C. Du ser ut fra verdiene i diagrammet at sjøvannet er litt tyngre enn ferskvann. \n\nTil venstre for diagrammet finner du en tabell med informasjon du trenger til å svare på oppgaven. \n\nTabell og diagram\n\nVannmasse A og B er typiske vannmasser man kan finne i Grønlandshavet.\n\nBruk verdiene for vannmassene sammen med T-S-diagrammet nedenfor til å svare på spørsmålet.\n\nVannmasse\tTemperatur (ºC)\tSalinitet (PSU)\nA\t1\t29,7\nB\t−0,8\t29,4\nOppgave\nHva vil sannsynligvis skje når vannmasse A og B møtes?\nVannmasse A er lettere enn vannmasse B og vil legge seg over vannmasse B.\nVannmasse A er tyngre enn vannmasse B og vil legge seg under vannmasse B.",
    },
    {
      number: 9,
      title: "Våre nære havområder og feltdata",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\n / Tema 2 – Våre nære havområder og feltdata\nOppgave 9\nOppgave 9 – Våre nære havområder og feltdata\n\nOppgave 3 av 6 til tema 2. \n\nDu skal svare på oppgaven nederst på siden.\n\nCTD-data fra felt\n\nEn CTD er et elektronisk måleinstrument som brukes i havet for å måle grunnleggende egenskaper i vannsøylen. Navnet er en forkortelse for de engelske ordene Conductivity (konduktivitet/ledningsevne), Temperature (temperatur) og Depth (dybde). Et CTD-instrument har sensorer som måler:\n\nKonduktivitet: Vannets evne til å lede elektrisk strøm. Dette målet brukes til å beregne saltholdigheten (saliniteten) i vannet. Saltvann leder strøm bedre enn ferskvann.\nTemperatur: Vanntemperaturen på ulike dyp.\nTrykk: Det hydrostatiske trykket i vannet. Dette trykket øker jevnt med dybden og brukes til å bestemme nøyaktig hvor dypt instrumentet er.\n\nKlassen din har fått tilgang på data fra en CTD som har vært brukt på to forskjellige tokt i Grønlandshavet. Du vet at det ene toktet var i april 2020, og det andre var i august 2020. Forskerne på de to ulike toktene skulle studere prosessene i det øverste laget i Grønlandshavet. Vertikalprofilene av temperatur og salinitet går derfor bare ned til 175 meters dyp. \n\nStuder profilene i fanene nedenfor, og bestem hvilke profiler som er fra august, og hvilke som er fra april.\n\nTemperaturprofiler\nSalinitetsprofiler\n\nLegg merke til at skalaen på temperaturaksen er ulik på de to grafene.\n\nKilde til CTD-dataene som er brukt i oppgaven:\n\nOMG (2020). OMG CTD Conductivity Temperature Depth. Ver. 1. PO.DAAC, CA, USA. Datasett hentet den 23. oktober 2025 fra https://doi.org/10.5067/OMGEV-CTDS1\n\nFigurene er laget av Utdanningsdirektoratet.\n\nForrige fane\nNeste fane\nOppgave\n\nVelg riktig alternativ for april og august.\n\n \nla stå tom\nTemperaturprofil A og salinitetsprofil C\nTemperaturprofil A og salinitetsprofil D\nTemperaturprofil B og salinitetsprofil C\nTemperaturprofil B og salinitetsprofil D\n er fra april.\n\n \nla stå tom\nTemperaturprofil A og salinitetsprofil C \nTemperaturprofil A og salinitetsprofil D\nTemperaturprofil B og salinitetsprofil C\nTemperaturprofil B og salinitetsprofil D\n er fra august.",
    },
    {
      number: 10,
      title: "Våre nære havområder og feltdata",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "REA3043 Geofag 2\n / Tema 2 – Våre nære havområder og feltdata\nOppgave 10\nOppgave 10 – Våre nære havområder og feltdata\n\nOppgave 4 av 6 til tema 2. \n\nDu skal svare på oppgaven nederst på siden.\n\nArktisk forsterkning av global oppvarming\n\nGrønlandshavet er en del av Arktis. Tilbakekoblingseffekter gir forsterket oppvarming i Arktis.\n\nOppgave\nHvilke faktorer er medvirkende til at Arktis varmes opp raskere enn andre regioner? Kryss av for hvilke faktorer som er medvirkende, og hvilke faktorer som ikke er medvirkende.\nHvilke faktorer er medvirkende til at Arktis varmes opp raskere enn andre regioner? Kryss av for hvilke faktorer som er medvirkende, og hvilke faktorer som ikke er medvirkende.\n\tMedvirkende faktor\tIkke medvirkende faktor\nArktis har høyere innhold av vanndamp enn tropene, noe som forsterker oppvarmingen.\n\nI Arktis er det en sterk vertikal blanding i troposfæren, som forsterker drivhuseffekten.\n\nSmelting av is og snø reduserer overflatens albedo, noe som øker varmeopptaket.\n\nArktis har mer klimagasser enn noen annen region på jorden.\n\nI Arktis fører den globale oppvarmingen til endringer i den vertikale temperaturgradienten, noe som forsterker oppvarmingen.",
    },
    {
      number: 11,
      title: "Våre nære havområder og feltdata",
      kind: "skrive",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\n / Tema 2 – Våre nære havområder og feltdata\nOppgave 11\nOppgave 11 – Våre nære havområder og feltdata\n\nOppgave 5 av 6 til tema 2. \n\nDu skal svare på oppgaven nederst på siden.\n\nDannelse av monsterbølger\n\nHavbølger dannes primært når vind overfører energi til havoverflaten gjennom friksjon. Størrelsen på bølger avhenger av tre hovedfaktorer: vindstyrken, hvor lenge vinden har blåst (varighet), og avstanden vinden blåser over åpent hav (strøklengde eller fetch). Jo større disse tre faktorene er, jo større blir bølgene.\n\nNoen ganger dannes monsterbølger (også kalt ekstrembølger eller freak waves). Dette er unormalt store havbølger som reiser seg tilsynelatende spontant fra havet og kan være mer enn dobbelt så høye som omliggende bølger. \n\nFaktorer som kan forsterke bølger til å bli ekstreme:\n\nHavstrømmer (oseanografi): Hvis et bølgesystem flytter seg mot en sterk, motgående havstrøm, så vil havstrømmen bremse bølgene. Da minker bølgelengden, og bølgene vil vokse seg høyere og brattere. Agulhas-strømmen utenfor Sør-Afrika er et klassisk eksempel – i perioden 1990–2003 ble 20 skip ødelagt av bølger langs denne strømmen når bølger fra stormer i Sørishavet møtte den kraftige havstrømmen.\nBatymetri: Bølger påvirkes av havdybden. Når bølgene flytter seg over områder der havdybden endrer seg brått, så kan bølgeenergien konsentreres på et mindre område og skape større bølger. \nKombinasjoner: Havstrømmer, batymetri og vindgenererte bølger kan samvirke for å skape store bølger.\nOppgave \n\nI denne oppgaven skal du både klikke på ett punkt i et kart og forklare hvorfor du har valgt punktet. \n\nMonsterbølger kan dannes flere steder innenfor området vist i kartet nedenfor. Du skal sette et punkt i et område hvor du anser at det er stor sannsynlighet for at monsterbølger dannes. Du skal gjøre et valg basert på prosessene som er nevnt ovenfor. Plasseringen av punktet er ikke avgjørende for oppgaven, det er begrunnelsen som er viktig.\n\nBegrunn valget i tekstboksen nederst på siden. \n\nDu skal forklare hvorfor forholdene på dette stedet gir gode forhold for at det kan dannes monsterbølger, med tanke på vind, havstrømmer og batymetri.\n\nKlikk på et punkt hvor du anser at det er stor sannsynlighet for at monsterbølger dannes. \n\nSkriv begrunnelsen din her.",
    },
    {
      number: 12,
      title: "Våre nære havområder og feltdata",
      kind: "skrive",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\n / Tema 2 – Våre nære havområder og feltdata\nOppgave 12\nOppgave 12 – Våre nære havområder og feltdata\n\nOppgave 6 av 6 til tema 2. \n\nDu skal svare på oppgaven nederst på siden.\n\nTolke forskningsdata\n\nStudier av ulike vannmasser i Grønlandshavet kan fortelle hvordan havet reagerer på global oppvarming. I Grønlandshavet studerer man særlig polart vann og atlantisk vann, og man undersøker hvordan disse reagerer på klimaendringer.\n\nFiguren i fanen nedenfor består av seks grafer. Datamaterialet er innhentet på ulike forsknings- og feltarbeid. Dataene er representert på ulike måter:\n\nSvarte linjer: gjennomsnittsverdier av data samlet inn gjennom hele året\n\nOransje linjer: glidende gjennomsnitt over fem år av data samlet inn i sommermånedene juli, august og september\n\nGrå prikker: gjennomsnittsverdier av data samlet inn i sommermånedene juli, august og september\n\nGrafene a, c og e viser temperatur.\nGrafene b, d og f viser salinitet.\nGrafene a og b viser verdier fra de øverste 0–20 meterne av vannsøylen.\nGrafene c og d viser verdier for polart vann.\nGrafene e og f viser verdier for atlantisk vann.\nGrafer\nKilde: Gjelstrup, C. V. B., og Stedmon, C. A. (2024). A switch in thermal and haline contributions to stratification in the Greenland Sea during the last four decades. Progress in Oceanography, 225, 103283. https://doi.org/10.1016/j.pocean.2024.103283\nOppgave\n\nPåstander knyttet til figurene ovenfor og konsekvenser av klimaendringer i Grønlandshavet:\n\nTemperaturen i de øverste 20 meterne i Grønlandshavet har økt kraftig fra 2015 til 2020 grunnet global oppvarming.\nEndringen i temperaturen i de øverste 20 meterne kan skyldes økt tilførsel av smeltevann fra innlandsisen på Grønland.\nAtlantisk vann i Grønlandshavet har blitt saltere over tid. Den økte saliniteten kan kobles til et varmere klima.\nPolart vann er mer salt enn Atlanterhavsvann. Dette skyldes at det felles ut salt når sjøis dannes.\n\nHvilke av påstandene er sanne, og hvilke er usanne? Begrunn svaret.",
    },
    {
      number: 13,
      title: "Istider og klimaendringer",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\n / Tema 3 – Istider og klimaendringer\nOppgave 13\nOppgave 13 – Istider og klimaendringer\n\nOppgave 1 av 6 til tema 3. \n\nDu skal svare på oppgaven nederst på siden.\n\nPerihelium og årstidsvariasjoner\n\nNedenfor finner du ulike påstander om hvordan jordaksens presesjon, og dermed tidspunktet for perihelium og aphelium, påvirker årstidsvariasjoner og istider. Du skal avgjøre hvilke av alternativene som er sanne.\n\nHvis jorden ligger i perihelium ved vintersolverv på den nordlige halvkule, så gir det relativt små årstidsvariasjoner på den nordlige halvkule.\nHvis jorden ligger i aphelium ved sommersolverv på den nordlige halvkule, så gir det relativt store årstidsvariasjoner på den sørlige halvkule.\nHvis jorden ligger i aphelium ved vintersolverv på den nordlige halvkule, så er det mindre sannsynlig med en istid på den nordlige halvkule.\nOppgave\nKryss av for om påstandene er sanne eller usanne. Du må ha alt riktig for å få poeng.\nKryss av for om påstandene er sanne eller usanne. Du må ha alt riktig for å få poeng.\n\tSann\tUsann\nPåstand 1\n\nPåstand 2\n\nPåstand 3",
    },
    {
      number: 14,
      title: "Istider og klimaendringer",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "REA3043 Geofag 2\n / Tema 3 – Istider og klimaendringer\nOppgave 14\nOppgave 14 – Istider og klimaendringer\n\nOppgave 2 av 6 til tema 3. \n\nDu skal svare på oppgaven nederst på siden.\n\nMilanković-sykluser og breddegrad\n\nMilanković-syklusene utgjør et betydelig strålingspådriv. Betydningen av dette strålingspådrivet varierer sterkt med breddegraden. Ved ekvator er betydningen svakest, og ved 65°N er den sterkest.\n\nOppgave\n\nHvilket utsagn er riktig når det gjelder betydningen av Milanković-syklusene ved 65°N i forhold til ved ekvator?\n\nMilanković-syklusene har mest betydning ved 65°N fordi temperaturen der alltid er lavere enn ved ekvator, og kaldere områder reagerer sterkere på klimaendringer.\nVed 65°N gir Milanković-syklusene store endringer i hvor sterk sommersola er. Ved ekvator er solinnstrålingen jevn hele året, så endringene blir små og har mindre betydning for klimaet.\n\nJordas rotasjonshastighet er lavere ved 65°N enn ved ekvator, noe som forsterker klimaeffekten ved 65°N.\n\nJordas avstand til sola endres mer ved 65°N enn ved ekvator gjennom året, dette gjør at Milanković-syklusene får størst betydning ved 65°N.",
    },
    {
      number: 15,
      title: "Istider og klimaendringer",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "REA3043 Geofag 2\n / Tema 3 – Istider og klimaendringer\nOppgave 15\nOppgave 15 – Istider og klimaendringer\n\nOppgave 3 av 6 til tema 3. \n\nDu skal svare på oppgaven nederst på siden.\n\nSelvforsterkende klimaendringer\nI overgangen fra en mellomistid til en istid blir klimaet kjøligere. Noen mekanismer forsterker en slik nedkjøling.\nOppgave\n\nHvordan bidrar tilbakekoblingsmekanismer til selvforsterkende nedkjøling?\n\nTlbakekoblingsmekanismer begrenser alltid endringen ved å bringe systemet tilbake i balanse.\nPositive tilbakekoblinger øker nedkjølingen ytterligere. \nI et klima som blir kaldere vil negative tilbakekoblingsmekanismer dominere systemet, noe som forsterker avkjøling.\nTilbakekoblingsmekanismer forsvinner når CO₂-nivåene blir lavere.",
    },
    {
      number: 16,
      title: "Istider og klimaendringer",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\n / Tema 3 – Istider og klimaendringer\nOppgave 16\nOppgave 16 – Istider og klimaendringer\n\nOppgave 4 av 6 til tema 3. \n\nDu skal svare på oppgaven nederst på siden.\n\nTemperatur, havnivå og isvolum\nData fra iskjerner\n\nGrafene nedenfor viser henholdsvis variasjoner i lufttemperatur (øverst), overflatetemperatur i havet, havnivå og endring i isvolum (nederst) på Antarktis for 800 000 år siden og frem til i dag, rekonstruert fra iskjerner i Antarktis. \n\nKilde: Chandler, D.M., Langebroek, P.M., Reese, R. et al. (2025) Antarctic Ice Sheet tipping in the last 800,000 years warns of future ice loss. Commun Earth Environ 6, 420 (2025). https://www.nature.com/articles/s43247-025-02366-2?fromPaywallRec=true.\n\n                       \n\nOppgave\n\nTa utgangspunkt i grafene ovenfor. \n\nHva er den mest sannsynlige årsaken til at isvolumet i Antarktis alltid var større for 750 000–450 000 år siden enn det er i dag?\n\nKlimaet var betydelig varmere i denne perioden på grunn av positive tilbakekoblingsmekanismer.\nUsikkerheten i dataene er betydelig redusert i denne perioden.\nKlimaet var kjøligere på grunn av negative tilbakekoblingsmekanismer.\nKlimaet var kjøligere på grunn av positive tilbakekoblingsmekanismer.",
    },
    {
      number: 17,
      title: "Istider og klimaendringer",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\n / Tema 3 – Istider og klimaendringer\nOppgave 17\nOppgave 17 – Istider og klimaendringer\n\nOppgave 5 av 6 til tema 3. \n\nDu skal svare på oppgaven nederst på siden.\n\nInnlandsis og permafrost\nUtbredelsen av permafrost i de siste 125 000 årene\n\nFiguren viser utbredelsen av permafrost i både volum og areal i de siste 125 000 årene i Eurasia og Nord-Amerika. I omtrent den samme tidsperioden var det istid på jorda, hvor innlandsisen dekket store deler av den nordlige halvkule.\n\nKilde: Opel T. et.al. (2024) Ancient permafrost and past permafrost in the Northern Hemisphere, USGS Publications Warehouse. https://www.usgs.gov/publications/ancient-permafrost-and-past-permafrost-northern-hemisphere.\nOppgave\n\nHvilken påstand om utbredelsen av permafrost i Nord-Amerika og Eurasia er riktig?\n\nI Nord-Amerika har det vært mye større snømengder enn i Eurasia i perioden. Dette er årsaken til at utbredelsen av permafrost har vært størst i Nord-Amerika.\nPlatetektoniske bevegelser er årsaken til at Eurasia har hatt den største utbredelsen av permafrost i perioden.\nInnlandsisens store utbredelse i Eurasia har vært årsaken til den store utbredelsen av permafrost i dette området.\nPermafrosten har hatt mye mindre utbredelse i Nord-Amerika på grunn av innlandsisens store utbredelse i dette området.",
    },
    {
      number: 18,
      title: "Istider og klimaendringer",
      kind: "skrive",
      needsFigure: false,
      prompt: "REA3043 Geofag 2\n / Tema 3 – Istider og klimaendringer\nOppgave 18\nOppgave 18 – Istider og klimaendringer\n\nOppgave 6 av 6 til tema 3.\n\nDu skal svare på oppgaven nederst på siden.\n\nIstider og naturfarer\nI en overgang fra istid til mellomistid forsvinner store arealer med sjøis.\nOppgave\n\nVurder hvilke naturfarer som øker i omfang eller styrke som følge av redusert sjøis i en slik overgang.",
    },
    {
      number: 19,
      title: "Vekselvirkninger og energi",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\n / Tema 4 – Vekselvirkninger og energi\nOppgave 19\nOppgave 19 – Vekselvirkninger og energi\n\nOppgave 1 av 5 til tema 4. \n\nDu skal svare på oppgaven nederst på siden.\n\nMassebalanse ved to isbreer i Norge\n\nNedenfor finner du to figurer som viser massebalansen (i meter vannekvivalenter) til isbreene Ålfotbreen og Hellstugubreen i Norge, henholdsvis i periodene 1963–2023 og 1962–2022. Breene ligger på samme breddegrad (61°N). \n\nI denne oppgaven skal du bare se på verdiene etter år 2000.\n\nMassebalanse til isbreene\nKilde: Norges vassdrags- og energidirektorat (NVE). Hentet 2. februar 2026 fra https://glacier.nve.no/Glacier/viewer/CI/no/nve/ClimateIndicatorInfo/2078?name=%C3%85lfotbreen og https://glacier.nve.no/Glacier/viewer/CI/no/nve/ClimateIndicatorInfo/2768?name=Hellstugubreen. \n\n \n\nOppgave\nHvilken påstand er rett om Hellstugubreen og Ålfotbreen?\n\nHellstugubreen får mer vinternedbør enn Ålfotbreen.\n\nEndringen i massebalanse gjennom tidsperiodene i figurene tyder på at den globale temperaturen har økt. \n\nVolumet av breen øker når sommerbalansen er større enn vinterbalansen. \nVinterbalansen til de to breene tyder på at Hellstugubreen ligger vest for Ålfotbreen.",
    },
    {
      number: 20,
      title: "Vekselvirkninger og energi",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "REA3043 Geofag 2\n / Tema 4 – Vekselvirkninger og energi\nOppgave 20\nOppgave 20 – Vekselvirkninger og energi\n\nOppgave 2 av 5 til tema 4. \n\nDu skal svare på oppgaven nederst på siden.\n\nNAO og endring i isbreers massebalanse\nDen nord-atlantisk oscillasjon (NAO) påvirker massebalansen til isbreer på Vestlandet i Norge.\nOppgave\n\nHvilken av påstandene nedenfor gir en mest korrekt beskrivelse av hvordan NAO påvirker massebalansen til isbreer på Vestlandet i Norge?\n\nNegativ NAO gir kalde og tørre vintre på Vestlandet, som gir lite snøfall og negativ massebalanse.\nNegativ NAO gir kalde og våte vintre på Vestlandet, som gir mye våt snø og negativ massebalanse.\nPositiv NAO gir milde og tørre vintre på Vestlandet, med mer regn og mindre snø, noe som gir positiv massebalanse.\nPositiv NAO gir kalde og tørre vintre på Vestlandet, noe som øker snømengden og fører til positiv massebalanse.",
    },
    {
      number: 21,
      title: "Vekselvirkninger og energi",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "REA3043 Geofag 2\n / Tema 4 – Vekselvirkninger og energi\nOppgave 21\nOppgave 21 – Vekselvirkninger og energi\n\nOppgave 3 av 5 til tema 4. \n\nDu skal svare på oppgaven nederst på siden.\n\nKatabatisk vind\nTopografi kan gi opphav til ulike typer vind. \nOppgave\n\nKryss av for hvilke påstander som er riktige, og hvilke som er feil.\n\nKryss av for hvilke påstander som er riktige, og hvilke som er feil.\n\n\tRiktig\tFeil\n\nKatabatisk vind dannes når fuktig luft tvinges opp over et fjell, kjøles ned og deretter varmes opp når den synker igjen.\n\nDet dannes ofte katabatiske vinder på lesiden av fjell som er dekket av isbreer.\n\nKatabatisk vind i fjellområder fører ofte til at det dannes skyer.",
    },
    {
      number: 22,
      title: "Vekselvirkninger og energi",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA3043 Geofag 2\n / Tema 4 – Vekselvirkninger og energi\nOppgave 22\nOppgave 22 – Vekselvirkninger og energi\n\nOppgave 4 av 5 til tema 4. \n\nDu skal svare på oppgaven nederst på siden.\n\nFønvind og temperatur\n\nFiguren nedenfor viser en idealisert situasjon med et fjell der foten av fjellet ligger ved havnivået. Fjellet er 2000 meter høyt. Det blåser inn mot fjellet, noe som skaper orografisk nedbør. Skyene dannes i 800 meters høyde.\n\nI denne oppgaven skal du regne med en tørradiabatisk temperaturgradient på 1 °C / 100 m og en våtadiabatisk temperaturgradient på 0,5 °C / 100 m.\n\nDu skal regne ut hva temperaturen er ved toppen av fjellet (2000 m høyde) og ved foten av fjellet på lesiden (0 m høyde). Du vet at temperaturen ved foten av fjellet på losiden er 14 °C.\n\nFigur\n\nFiguren viser en idealisert situasjon med et fjell der foten av fjellet ligger ved havnivået.\n\nOppgave\n\nMarker rett alternativ:\n\nTemperaturen på toppen av fjellet er 4 °C, og temperaturen ved foten av fjellet på lesiden er 24 °C.\nTemperaturen på toppen av fjellet er 0 °C, og temperaturen ved foten av fjellet på lesiden er 20 °C.\nTemperaturen på toppen av fjellet er −3 °C, og temperaturen ved foten av fjellet på lesiden er 17 °C.\nTemperaturen på toppen av fjellet er −6 °C, og temperaturen ved foten av fjellet på lesiden er 14 °C.",
    },
    {
      number: 23,
      title: "Vekselvirkninger og energi",
      kind: "skrive",
      needsFigure: false,
      prompt: "REA3043 Geofag 2\n / Tema 4 – Vekselvirkninger og energi\nOppgave 23\nOppgave 23 – Vekselvirkninger og energi\n\nOppgave 5 av 5 til tema 4. \n\nDu skal svare på oppgaven nederst på siden.\n\nKlimaendringer og energiproduksjon \n\nNorge må øke produksjonen av fornybar energi for å dekke energibehovet de neste 50 årene. \n\nOppgave\nVurder hvor sannsynlige de fire påstandene nedenfor er:\nEt varmere klima vil gi mer solenergi i Norge.\nSmeltende isbreer vil gi mer vannkraft i Norge.\nEt varmere klima vil gi stabile fønvinder på lesiden av norske fjell, noe som kan sikre stabil energiproduksjon fra vindturbiner.\nGlobal oppvarming vil føre til mer vind, noe som kan øke produksjonen av vindkraft i Norge.",
    },
  ],
};
