import type { ExamSet } from "../types";

export const v2024: ExamSet = {
  slug: "v2024",
  label: "Vår 2024",
  season: "V",
  year: 2024,
  kind: "eksamen",
  complete: true,
  officialUrl: "https://kandidat.udir.no/epsmateriell/eksamen?fagkode=REA3043&malform=nb-NO&semester=V&ar=2024&eksamensdeltype=Eksamen",
  themes: [
    "Kategori 1",
    "Kategori 2",
    "Kategori 3",
  ],
  tasks: [
    {
      number: 1,
      title: "Vindstyrke",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA 3043 Geofag 2\nOppgave 1: Vindstyrke\nOppgave 1 Vindstyrke\nNedenfor finner du et analysekart fra yr.no der det er markert tre steder med symbolene trekant, firkant og sirkel.\nHentet 24.10.2023 fra https://www.met.no/vaer-og-klima/meteorologens-analysekart\n \nDersom vi bare ser på de tre stedene som er merket med symboler, hvor finner vi den sterkeste vinden?\nAlle tre stedene har like sterk vind.\nStedet merket med firkant og stedet merket med sirkel har den sterkeste vinden.\nStedet merket med trekant og stedet merket med firkant har den sterkeste vinden.\nStedet merket med sirkel har den sterkeste vinden.\nStedet merket med firkant har den sterkeste vinden.\nStedet merket med trekant har den sterkeste vinden.",
    },
    {
      number: 2,
      title: "Drivhusgasser",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "REA 3043 Geofag 2\nOppgave 2 Drivhusgasser\nOppgave 2: Drivhusgasser\nTeksten nedenfor handler om drivhusgasser. Velg riktig ord i nedtrekksmenyene slik at den fullstendige teksten blir geofaglig korrekt.\n\n \nla stå tom\nCO2\nN2O\nCH4\n  har i millioner av år blitt fjernet fra atmosfæren gjennom prosesser som dypvannsdannelse og nedslamming av organisk materiale på havbunnen. Ved nedbryting eller brenning av organisk materiale med liten tilgang på oksygen, kan vi få dannet\nla stå tom\nO3\nCH4\nO2\n, som er den nest viktigste klimagassen fra menneskelig aktivitet. Av drivhusgassene CO2, CH4 og H2O, har\nla stå tom\nCO2\nCH4\nH2O\n  kortest levetid i atmosfæren.",
    },
    {
      number: 3,
      title: "Lavtrykk og varmfront",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA 3043 Geofag 2\nOppgave 3: Lavtrykk og varmfront\nOppgave 3 Lavtrykk og varmfront\n\nNedenfor er det fire bilder (A–D) som viser temperaturen rundt et lavtrykk, med tilhørende forslag til plassering av varmfront. \n\nKilde: Windy.com\n \n\nFiguren ovenfor viser ulike plasseringer av varmfronten i forbindelse med et lavtrykk med tilhørende temperaturskala.\n\nHvilken plassering virker mest fornuftig?\nA\nB\nC\nD",
    },
    {
      number: 4,
      title: "Biomasse",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA 3043 Geofag 2\nOppgave 4: Biomasse\nOppgave 4 Biomasseproduksjon\n\nDenne figuren viser hvor mye klorofyll som finnes på ulike steder i havet i oktober måned. Dette forteller oss hvor mye biomasse som blir produsert på ulike steder.\n\nHentet fra: https://earthobservatory.nasa.gov/global-maps/MY1DMM_CHLORA\n \n\nNedenfor er det noen utsagn som du skal ta stilling til. \n\na) Det er andre faktorer enn direkte sollys som dominerer produksjonen av biomasse.\n\nb) Det er ofte stor produksjon av biomasse i områder med oppvelling.\n\nc) Det er oftest høyest produksjon av biomasse i de varmeste områdene.\n\nd) Det er som regel lavere produksjon av biomasse i områder med kraftige strømmer.\n\nHvilke av disse utsagnene er sanne?\n\nBåde a og b er sanne.\nBåde c og d er sanne.\nBåde a, b og d er sanne.\nBåde b, c og d er sanne.\nAlle fire utsagnene er sanne.",
    },
    {
      number: 5,
      title: "Tropisk orkan",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA 3043 Geofag 2\nOppgave 5: Tropisk orkan\nOppgave 5 Tropisk orkan\n\nBildet nedenfor er et satellittbilde av skydekket i en tropisk orkan. Pilen markerer plasseringen av en tenkt øy.  \n\nBildet er hentet 10.11.2023 fra https://obxstuff.com/blogs/guides/category-5-hurricane-wind-speed.\n\nHvilke av disse påstandene er sanne om hvordan forholdene er på denne tenkte øya akkurat i det øyeblikket bildet er tatt?\n\nPå øya er det nesten vindstille nå.\nPå øya er det sterk vind nå.\nPå øya regner det kraftig akkurat nå.\nPå øya er det ikke nedbør akkurat nå.\nVannstanden rundt øya er sannsynligvis lav nå.\nVannstanden rundt øya er sannsynligvis høy nå.\nKryss av ved det alternativet der de sanne påstandene står:\n1, 3 og 5 er sanne påstander.\n1, 4 og 5 er sanne påstander.\n1, 4 og 6 er sanne påstander.\n2, 3 og 5 er sanne påstander.\n2, 4 og 6 er sanne påstander.\n2, 3 og 6 er sanne påstander.",
    },
    {
      number: 6,
      title: "Vind og havstrømmer",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA 3043 Geofag 2\nOppgave 6: Vind og havstrømmer\nOppgave 6 Vind og havstrømmer\n\nFiguren nedenfor viser et lavtrykk over havet vest for Storbritannia. Hastigheten på vinden er angitt med fargeskala nederst i bildet. Bokstavene A til F angir ulike posisjoner.\n\n    \n\nHvor mener du overflatestrømmene i havet har størst hastighet av de gitte posisjonene A, B, C, D, E og F?\nA og B\nC og F\nD og E\nE og F",
    },
    {
      number: 7,
      title: "Utstråling fra jorden",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA 3043 Geofag 2\nOppgave 7: Utstråling fra jorden\nOppgave 7 Stråling fra jordoverflaten i Saharaørkenen\n\nFigurene nedenfor viser: \n\nA: Utstrålingsspekteret fra jordoverflaten ved Sahara. Førsteaksen viser bølgelengden, og andreaksen viser strålingsintensiteten. Temperatur er oppgitt i kelvin (K).\n\nB: Tre grafer som representerer absorbsjonen til ulike klimagasser. Førsteaksen viser bølgelengden, og andreaksen er mengden absorbert stråling. \n\nFørsteaksen til begge figurene har sammenfallende bølgelengder. \n\n   \nHentet fra http://climatorealist.neowordpress.fr/greenhouse-effect/\n  \n\nFigur A viser tydelig at noe av strålingen absorberes av klimagassene. Figur B viser hvilke gasser som absorberer den utgående strålingen. \n\nBlå (stiplet), rød (heltrukken) og svart (heltrukken med kryss) graf representerer ulike klimagasser.\n\nSett kryss ved rett alternativ\nCO2 = rød, O3 med flere = blå, H2O = svart\nCO2 = blå, O3 med flere = svart, KFK = rød\nH2O = blå, CO2 = rød, O3 med flere = svart\nNO2 = blå, H2O = rød, CO2 = svart",
    },
    {
      number: 8,
      title: "Innlandsis og vindretning",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA 3043 Geofag 2\nOppgave 8: Innlandsis og vindretning\nOppgave 8 Innlandsis og vindretning\n\nFiguren nedenfor illustrerer en stor øy med innlandsis, med nunataker som stikker opp. Øya er sett fra siden, og den bølgete linjen nederst representerer havoverflaten. Fire piler markerer fire mulige vindretninger.\n\nKlikk på den pilen som viser den mest sannsynlige vindretningen som selve innlandsisen skaper:",
    },
    {
      number: 9,
      title: "Ekmantransport",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "REA 3043 Geofag 2\nOppgave 9: Ekmantransport\nOppgave 9 Ekmantransport\n\nNedenfor ser du et kart over Australia, og vi skal i denne oppgaven konsentrere oss om Australias vestkyst.\n\nHentet 02.02.2024 fra https://www.albatros.no/reisemaal/australia-og-stillehavet/australia/kart\n \n\n \n\n \n\nDersom det blåser vind fra sør langs vestkysten av Australia, vil dette kunne forårsake overflatestrømmer i havet.\n\nHvilken retning vil disse overflatestrømmene ha?\n\nNordlig retning\n\nØstlig retning\n\nSørlig retning\n\nVestlig retning",
    },
    {
      number: 10,
      title: "Havets tetthet",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "REA 3043 Geofag 2\nOppgave 10: Havets tetthet\nOppgave 10 Havets tetthet\n\nNedenfor er fire utsagn om overflatevannet i havet ved ekvator.\n\nVannet ved ekvator har lav tetthet fordi det har ...\n\nA) ... høy temperatur.\n\nB) ... lav temperatur.\n\nC) ... høy salinitet.\n\nD) ... lav salinitet.\n\n \nHvilken av disse er sanne?\nA og C er sanne.\nA og D er sanne.\nB og C er sanne.\nB og D er sanne.",
    },
    {
      number: 11,
      title: "Havstrømmer",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "REA 3043 Geofag 2\nOppgave 11: Havstrømmer\nOppgave 11 Havstrømmer\n\nNedenfor er fire påstander om havstrømmer:\n\nDen termohaline sirkulasjonen er viktig for transport av energi rundt på jordkloden.\nMindre fordamping fra havområder bidrar til å drive overflatestrømmene.\nDypvannsdannelse kan skje når temperaturen synker og/eller saltkonsentrasjonen øker.\nFerskvannstilførsel bidrar til å øke transporthastigheten i den termohaline sirkulasjonen.\nHvilke av alternativene om havstrømmer er korrekte?\n1 og 2\n2 og 4\n3 og 4\n1 og 3",
    },
    {
      number: 12,
      title: "Tropiske orkaner",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "REA 3043 Geofag 2\nOppgave 12: Tropiske orkaner\nOppgave 12 Tropiske orkaner\n\nTeksten nedenfor handler om tropiske orkaner. Marker riktig alternativ i nedtrekksmenyen, slik at teksten blir geofaglig korrekt.\n\nTropiske orkaner er \nla stå tom\nhøytrykk\nlavtrykk\n som oppstår \nla stå tom\npå ekvator\nlitt nord eller sør for ekvator\nnær polene\n. Tropiske orkaner får tilført energi fra\nla stå tom\nvanndamp\nstore temperaturforskjeller\ncorioliskraften\n. En vanlig konsekvens av tropiske orkaner er\nla stå tom\npent vær\nstormflo\nsmå nedbørsmengder\n . Tropiske orkaner oppstår ofte\nla stå tom\nutenfor kysten av Sør-Amerika\ni Mexicogolfen\npå ekvator\n. Når tropiske orkaner beveger seg inn over landområder, vil vindstyrken\nla stå tom\nforbli uendret\nøke\navta\n.",
    },
    {
      number: 13,
      title: "Strålingspådriv",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "REA 3043 Geofag 2\nOppgave 13: Strålingspådriv\nOppgave 13 Strålingspådriv\n\nGlobal oppvarming kan føre til at store områder som tidligere var dekket av havis, blir isfrie. Slike hendelser ...\n\nkan føre til positivt strålingspådriv\n\nkan føre til negativt strålingspådriv\n\nvil ikke føre til endringer i strålingsbalansen",
    },
    {
      number: 14,
      title: "Permafrost",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA 3043 Geofag 2\nOppgave 14: Permafrost\nOppgave 14 Permafrost \n\nFigurene nedenfor viser dybden til nullgradersisotermen fra et borehull på Jansonhaugen på Svalbard i tidsperioden 1998–2023.\n\n \n\nHentet 24.10.23 fra frost.met.no\n   \nMarker det utsagnet som er riktig i forhold til figuren.\nFiguren viser at det aktive laget i permafrosten på Jansonhaugen har blitt tynnere i tidsperioden.\nFiguren viser at permafrosten på Jansonhaugen har blitt dypere i tidsperioden. \nFiguren kan ikke fortelle oss noe om permafrostens tilstand på Jansonhaugen.\nFiguren viser at permafrosten på Jansonhaugen har blitt svekket i tidsperioden.",
    },
    {
      number: 15,
      title: "Nedbør",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA 3043 Geofag 2\nOppgave 15: Nedbør\nOppgave 15 Nedbør \nPå bildet nedenfor ser du et kart over en tenkt øy. Øya ligger ute i et hav, langt fra land. Kartet har to horisontale stiplede linjer. Den øverste viser 20 grader sørlig bredde, og den nederste viser 25 grader sørlig bredde. De svarte heltrukne linjene er høydekurver med en ekvidistanse på 500 meter. \n\n \n\nKilde: Utdanningsdirektoratet\n \nPå hvilken side av denne øya er det mest nedbør?\nPå den nordøstlige siden\nPå den sørøstlige siden\nPå den sørvestlige siden\nPå den nordvestlige siden",
    },
    {
      number: 16,
      title: "Snøskred og vær",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA 3043 Geofag 2\nOppgave 16: Snøskred og vær\nOppgave 16 Snøskred og vær\n\nFiguren nedenfor viser meteorologiske data fra to målestasjoner i Trysil i tidsperioden 1. til 17. januar. Datoene er plassert på førsteaksen. Øverste figur viser høyeste middelvind per døgn, med blå kurve for målestasjonen oppe på Trysilfjellet og rød kurve for målestasjonen nede i dalen. Nest øverste figur viser middeltemperaturen per døgn for de samme to målestasjonene, blå for Trysilfjellet og rød for dalen. De to nederste figurene handler om målt nedbør i området. Nedbør (døgn) viser total nedbør per døgn. Nedbør (30 døgn) viser akkumulert nedbør.\n\n \n\nHentet fra seklima.met.no\n \n\n17. januar 2023 gikk det et større snøskred i Trysilfjellet.\n\nHvilke værmessige faktorer i denne tidsperioden bidro til at dette skredet kunne gå?\nFallende temperatur, økende nedbør og lite vind i tidsperioden før skredet gikk.\nStigende temperatur, svak vind og moderat nedbør i tidsperioden før skredet gikk.\nModerat nedbør, kraftig vind og stigende temperatur i tidsperioden før skredet gikk.\nØkende vind, minkende nedbør og fallende temperatur i tidsperioden før skredet gikk.",
    },
    {
      number: 17,
      title: "Klimadiagram",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA 3043 Geofag 2\nOppgave 17: Klimadiagram\nOppgave 17 Klimadiagram\n\nNedenfor finner du 6 klimadiagram. På venstre side står temperaturen i grader celcius, oppgitt med røde tall. Disse korresponderer med den røde linjen. På høyre side står nedbør i mm, oppgitt med blå tall. På førsteaksen står de ulike månedene.\n\nKlikk et sted på det klimadiagrammet som er hentet fra et sted med typisk innlandsklima:",
    },
    {
      number: 18,
      title: "Den lille istid",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "Oppgave 18 Den lille istid\nOppgave 18 Den lille istid\n\nDen lille istid var en kald periode i Europa som varte fra midten av 1500-tallet til midten av 1800-tallet.\n\nUnder ser du en rekke påstander om hvilke faktorer som var avgjørende for den lille istid.\n\nPlatetektonikk: Kontinentenes plassering var ideell for en kaldere periode\nVulkanutbrudd: Det var flere kraftige vulkanutbrudd som førte til mange aerosoler i atmosfæren\nLa Niña: Flere år på rad med La Niña\nSolflekker: Av ukjente årsaker var det svært liten solflekkaktivitet i denne perioden\nAstronomiske variasjoner: De tre Milankovič-syklusene sørget for en kald periode\nNordatlantiske oscillasjon (NAO): Langvarig periode med negativ NAO-indeks som ga kalde forhold i Europa\nHvilke påstander er de mest sannsynlige årsakene til den lille istid?\nPåstand 1, 3 og 5\nPåstand 2, 3 og 5\nPåstand 2, 4 og 6\nPåstand 1, 5 og 6",
    },
    {
      number: 19,
      title: "Jetstrømmer",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA 3043 Geofag 2\nOppgave 19: Jetstrømmer\nOppgave 19 Jetstrømmer\n\nFiguren nedenfor viser jetstrømmen en vinterdag over de nordlige delene av Europa. De ulike fargene viser vindhastigheten i mph (engelske mil per time) – se skala til høyre.\n\nHentet 15.09.2019 fra https://www.netweather.tv/charts-and-data/jetstream.\n \n\nNedenfor er det noen påstander om værsituasjonen i Norge på dette tidspunktet. \n\nA) Det er mildt i de sørvestlige delene.\n\nB) Det er mildt i de helt nordligste delene. \n\nC) Det er kaldt i de sørvestlige delene.\n\nD) Det er kaldt i de helt nordøstligste delene.\n\nE) Det er fuktig i de midtre delene.\n\nF) Det er kaldt i de sørøstlige delene.\n\n \nHva er sannsynligvis sant?\nB, C og F er sanne.\nA, D og E er sanne.\nA, B og F er sanne.\nC, D og E er sanne.",
    },
    {
      number: 20,
      title: "ENSO",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "REA 3043 Geofag 2\nOppgave 20: ENSO\nOppgave 20 ENSO\n\nFlere hendelser rundt omkring i verden kan koples til ENSO:\n\nTørke og skogbranner herjet Indonesia i 1997–1998.\nFlom førte til at 150 000 mennesker i Paraguay, Uruguay og Argentina måtte flytte i 2010.\nFlom i Øst-Afrika førte til dødelige utbrudd av malaria og diaré i 2019.\nFlom i Europa 2021 førte til store økonomiske skader.\nTørke i Peru 2022 førte til at innsjøer tørket helt inn.\nHvilke av disse fem hendelsene kan koples til kraftige El Niño-situasjoner?\nHendelse 1, 2 og 3 kan knyttes til El Niño-situasjoner.\nHendelse 1, 3 og 4 kan knyttes til El Niño-situasjoner.\nHendelse 2, 3 og 5 kan knyttes til El Niño-situasjoner.\nHendelse 3, 4 og 5 kan knyttes til El Niño-situasjoner.",
    },
    {
      number: 21,
      title: "Værvarsel",
      kind: "interaktiv",
      needsFigure: true,
      prompt: "REA 3043 Geofag 2\nOppgave 21: Værvarsel\nOppgave 21 Værvarsel\n\nI de ulike fanene nedenfor finner du informasjon, kart og bilder du trenger for å svare på de tre oppgavene som står under fanene. Oppgavene nedenfor handler om været på Blindern en tirsdag. Alle kartene og figurene som er merket med «tirsdag», refererer til den samme tirsdagen. De som er merket med «mandag», refererer til dagen før tirsdag.\n\nInformasjon om målestasjonen\nAnalysekart\nSatellittbilder\nObservasjoner\nRadarplott\nJetstrøm\n\nI denne fanen finner du tre skjermbilder tatt av en animasjon av satellittbilder, det betyr at \"spill av\"-knappen i bildet ikke er aktiv. Det øverste bildet er fra midnatt natt til tirsdag, det midterste er fra tirsdag klokken 06.00 og det nederste tirsdag klokken 09.00:\n\nKilde: https://www.met.no/vaer-og-klima/satellittbilder  \n\nVis bildetekst\n\nForrige\nPDF\n\tSide 3 av 6\nNeste\na) Forklar hvordan du mener at været var på Blindern denne tirsdagen klokka 09.00.",
    },
    {
      number: 22,
      title: "her skal du laste opp et dokument",
      kind: "interaktiv",
      needsFigure: false,
      prompt: "REA 3043 Geofag 2\nInformasjon om eksamen\nEksamen i REA3043 Geofag 2\nMateriellet fra forberedelsesdagen\n\nMateriellet fra forberedelsesdagen finner du i starten av dette oppgavesettet.\n\nEksamen varer i 5 timer\n\nOppgavene blir vektet slik:\n\nKategori 1 – ca. 20 %\nKategori 2 – ca. 30 %\nKategori 3 – ca. 50 %\nOppgave 22 – her skal du laste opp et dokument\nTillatte hjelpemidler under eksamen\n\nHjelpemidler er for eksempel faglitteratur, ordbøker og kalkulator.\n\nDu kan bruke alle hjelpemidler, med noen unntak:\n\nDu har kun tilgang til noen utvalgte nettressurser.\nDu kan ikke bruke hjelpemidler som gjør det mulig å kommunisere. Det betyr at du ikke kan bruke mobiltelefon, programvare for samskriving, chat eller lignende.\nDu kan ikke bruke automatisk tekstgenerator som chatbot eller tilsvarende teknologi.\nDu må oppgi kildene du bruker\n\nDu må oppgi eventuelle kilder du bruker i svaret ditt, slik at sensor kan finne fram til dem. Det innebærer at du må skrive\n\nnavn på forfatter og tittel på bøker og annen litteratur\nnettadresse og dato for når du hentet informasjonen fra internett\n\nEksamenssvaret ditt blir kontrollert for plagiat. Hvis du ikke har oppgitt kilder du har brukt, kan det påvirke vurderingen av svaret ditt.\n\nLevering av eksamen \n\nDu skal svare på noen oppgaver direkte i oppgavesettet og oppgave 22 i et dokument som du laster opp til slutt, i oppgave 23.\n\nSvar på oppgaver i oppgavesettet:\nSvarene du skriver direkte i oppgavesettet, blir lagret automatisk og blir levert når du klikker på «Avslutt og lever»-knappen til sist i oppgavesettet.\nSvar på oppgaver utenfor oppgavesettet:\nSvarene du skriver utenfor oppgavesettet, må du samle i ett dokument som du laster opp til slutt. Hvordan du gjør dette, ser du i oppgave 23.​​​​​",
    },
  ],
};
